<x-layouts.office title="Dispatch">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-[.12em] text-brand-blue">Control plane</p><h1 class="mt-1 text-3xl font-bold">Dispatch</h1><p class="mt-2 text-slate-600">{{ $date->format('l, F j, Y') }} · {{ $activeOrganization->timezone }}</p></div>@if($activeMembership->hasCapability('dispatch.manage'))<a class="button-primary" href="{{ route('office.service-tickets.create') }}">New service ticket</a>@endif</div>
    <div class="mt-6 grid grid-cols-7 gap-2" aria-label="Seven day workload">
        @foreach($week as $day)<a href="{{ route('office.dispatch.index', ['date'=>$day['date']->format('Y-m-d')]) }}" class="surface min-h-20 p-2 text-center {{ $day['date']->isSameDay($date) ? 'border-brand-blue bg-blue-50' : '' }}"><span class="block text-xs font-bold uppercase text-slate-500">{{ $day['date']->format('D') }}</span><span class="mt-1 block font-bold">{{ $day['date']->format('j') }}</span><span class="mt-1 block text-xs text-slate-500">{{ $day['count'] }} visits</span></a>@endforeach
    </div>
    <form method="GET" class="surface mt-5 grid gap-3 p-4 md:grid-cols-5"><input type="hidden" name="date" value="{{ $date->format('Y-m-d') }}"><div><label class="form-label" for="assignee">Assignee</label><select class="form-input" id="assignee" name="assignee"><option value="">All</option>@foreach($memberships as $membership)<option value="{{ $membership->id }}" @selected((string)request('assignee')===(string)$membership->id)>{{ $membership->user->name }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option>@foreach($visitStatuses as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div><label class="form-label" for="priority">Priority</label><select class="form-input" id="priority" name="priority"><option value="">All</option>@foreach($priorities as $value=>$label)<option value="{{ $value }}" @selected(request('priority')===$value)>{{ $label }}</option>@endforeach</select></div><div class="flex items-end"><button class="button-secondary w-full">Apply filters</button></div><div class="flex items-end"><a class="button-secondary w-full" href="{{ route('office.dispatch.index', ['date'=>$date->format('Y-m-d')]) }}">Clear</a></div></form>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
        <section><h2 class="text-lg font-bold">Scheduled</h2><div class="surface mt-3 divide-y divide-slate-200">@forelse($visits as $visit)<a href="{{ route('office.service-tickets.show', $visit->serviceTicket) }}" class="grid min-h-20 gap-2 p-4 hover:bg-slate-50 sm:grid-cols-[120px_1fr_180px] sm:items-center"><strong class="text-brand-blue">{{ $visit->scheduledStartLocal()->format('g:i A') }}</strong><span><strong class="block">{{ $visit->serviceTicket->ticket_number }} · {{ $visit->serviceTicket->title }}</strong><span class="text-sm text-slate-500">{{ $visit->serviceTicket->customer->display_name }} · {{ $visit->serviceLocation->name }}</span></span><span class="text-sm text-slate-600">{{ $visit->assignments->map(fn($a)=>($a->is_lead?'Lead: ':'').$a->membership->user->name)->join(', ') }}</span></a>@empty<div class="p-8 text-center text-sm text-slate-500">No scheduled visits for this day.</div>@endforelse</div></section>
        <section><h2 class="text-lg font-bold">Unscheduled backlog</h2><div class="surface mt-3 divide-y divide-slate-200">@foreach($ticketBacklog as $ticket)<a href="{{ route('office.service-tickets.show', $ticket) }}" class="block min-h-20 p-4 hover:bg-slate-50"><strong class="block text-brand-orange">{{ $ticket->ticket_number }} · No visit</strong><span class="mt-1 block font-semibold">{{ $ticket->title }}</span><span class="mt-1 block text-sm text-slate-500">{{ $ticket->customer->display_name }}</span></a>@endforeach @forelse($backlog as $visit)<a href="{{ route('office.visits.edit', $visit) }}" class="block min-h-20 p-4 hover:bg-slate-50"><strong class="block text-brand-blue">{{ $visit->serviceTicket->ticket_number }}</strong><span class="mt-1 block font-semibold">{{ $visit->serviceTicket->title }}</span><span class="mt-1 block text-sm text-slate-500">{{ $visit->serviceTicket->customer->display_name }}</span></a>@empty @if($ticketBacklog->isEmpty())<div class="p-6 text-sm text-slate-500">No unscheduled work.</div>@endif @endforelse</div></section>
    </div>
</x-layouts.office>
