@props(['title'])
<x-layouts.office :title="$title" width="detail">
    @if(session('status'))<x-office.alert type="success">{{ session('status') }}</x-office.alert>@endif
    @if($errors->any())<x-office.alert variant="error"><p class="font-bold">Settings need attention</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-office.alert>@endif
    <x-office.primary-toolbar title="Settings" description="Manage organization, billing, invoice, and commercial defaults." eyebrow="Administration" />
    <nav class="mt-6 flex gap-2 overflow-x-auto border-b border-slate-200" aria-label="Settings">
        @if($activeMembership->hasCapability('organization.settings.manage'))<a href="{{ route('office.settings.organization.edit') }}" @if(request()->routeIs('office.settings.organization.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-4 text-sm font-bold {{ request()->routeIs('office.settings.organization.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600' }}">Organization</a>@endif
        @if($activeMembership->hasCapability('billing.settings.manage') || $activeMembership->hasCapability('payments.view'))<a href="{{ route('office.settings.billing.edit') }}" @if(request()->routeIs('office.settings.billing.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-4 text-sm font-bold {{ request()->routeIs('office.settings.billing.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600' }}">Billing</a>@endif
        @if($activeMembership->hasCapability('billing.settings.manage'))<a href="{{ route('office.settings.invoices.edit') }}" @if(request()->routeIs('office.settings.invoices.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-4 text-sm font-bold {{ request()->routeIs('office.settings.invoices.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600' }}">Invoices</a>@endif
        @if($activeMembership->hasCapability('opportunities.admin'))<a href="{{ route('office.settings.commercial.edit') }}" @if(request()->routeIs('office.settings.commercial.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-4 text-sm font-bold {{ request()->routeIs('office.settings.commercial.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600' }}">Commercial</a>@endif
        @if($activeMembership->hasCapability('proposal.templates.manage'))<a href="{{ route('office.commercial-library.index') }}" class="inline-flex min-h-11 shrink-0 items-center border-b-2 border-transparent px-4 text-sm font-bold text-slate-600">Proposal library</a>@endif
    </nav>
    <div class="mt-6">{{ $slot }}</div>
</x-layouts.office>
