@php($editing=isset($package))
<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="form-label" for="package_code">Package code</label><input class="form-input" id="package_code" name="package_code" value="{{ old('package_code',$package->package_code ?? '') }}" required></div>
    <div><label class="form-label" for="name">Package name</label><input class="form-input" id="name" name="name" value="{{ old('name',$package->name ?? '') }}" required></div>
    <div><label class="form-label" for="category_id">Category</label><select class="form-input" id="category_id" name="category_id"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$package->category_id ?? '')===(string)$category->id)>{{ $category->name }}{{ $category->active ? '' : ' — inactive' }}</option>@endforeach</select></div>
    <div><label class="form-label" for="sales_uom_id">Sales unit</label><select class="form-input" id="sales_uom_id" name="sales_uom_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)old('sales_uom_id',$package->sales_uom_id ?? '')===(string)$unit->id)>{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}{{ $unit->active ? '' : ' — inactive' }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Integrated Smart Home TV Rough-In is sold per Location.</p></div>
</div>
<div class="mt-5"><label class="form-label" for="customer_description">Customer description</label><textarea class="form-textarea" id="customer_description" name="customer_description" rows="3">{{ old('customer_description',$package->customer_description ?? '') }}</textarea><p class="mt-1 text-xs text-slate-500">Only Package-level information is customer-facing by default.</p></div>
<div class="mt-5"><label class="form-label" for="internal_description">Internal description</label><textarea class="form-textarea" id="internal_description" name="internal_description" rows="4">{{ old('internal_description',$package->internal_description ?? '') }}</textarea><p class="mt-1 text-xs text-slate-500">Document the standard assembly, assumptions, and exclusions.</p></div>
@if($canManagePricing)
<fieldset class="mt-7 border-t border-slate-200 pt-6"><legend class="text-lg font-bold text-slate-950">Pricing and tax</legend><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><label class="form-label" for="pricing_model">Pricing model</label><select class="form-input" id="pricing_model" name="pricing_model" required>@foreach(App\Models\CatalogPackage::PRICING_MODELS as $model)<option value="{{ $model }}" @selected(old('pricing_model',$package->pricing_model ?? 'flat')===$model)>{{ Str::headline($model) }}</option>@endforeach</select></div><div><label class="form-label" for="default_price">Default package price</label><input class="form-input" id="default_price" name="default_price" inputmode="decimal" value="{{ old('default_price',isset($package) && $package->default_price_cents !== null ? number_format($package->default_price_cents/100,2,'.','') : '') }}"><p class="mt-1 text-xs text-slate-500">Price per selected sales unit. Quote-required Packages have no default.</p></div></div><label class="mt-4 flex min-h-11 items-center gap-3"><input type="checkbox" name="taxable" value="1" @checked(old('taxable',$package->taxable ?? true))><span>Taxable by default</span></label></fieldset>
@else
<div class="mt-7 rounded-lg border border-slate-300 bg-slate-50 p-4 text-sm text-slate-700"><strong>Pricing is protected.</strong> Only a pricing manager can change Package price or tax defaults.</div>
@endif
<label class="mt-6 flex min-h-11 items-center gap-3"><input type="checkbox" name="active" value="1" @checked(old('active',$package->active ?? true))><span>Active and available for future selection</span></label>
