<x-layouts.office title="Catalog packages" width="workspace">
    @if(session('status'))<x-office.alert type="success">{{ session('status') }}</x-office.alert>@endif
    @php($packageFilters = collect(['q','category','pricing_model','status'])->filter(fn ($key) => filled(request($key))))
    <form method="GET" aria-label="Package filters">
    <x-office.primary-toolbar title="Products & Services" description="Maintain customer-facing packages with internal product and service recipes." eyebrow="Catalog">
        <x-slot:search><label class="sr-only" for="q">Search packages</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" type="search" placeholder="Search name or code"></x-slot:search>
        <x-slot:filters><x-office.filter-panel :active-count="$packageFilters->count()"><div class="grid gap-3 sm:grid-cols-3"><div><label class="form-label" for="category">Category</label><select class="form-input" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="form-label" for="pricing_model">Pricing</label><select class="form-input" id="pricing_model" name="pricing_model"><option value="">All models</option>@foreach(App\Models\CatalogPackage::PRICING_MODELS as $model)<option value="{{ $model }}" @selected(request('pricing_model')===$model)>{{ Str::headline($model) }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div></div><div class="mt-4 flex justify-end gap-2"><a class="button-secondary" href="{{ route('office.catalog.packages.index') }}">Clear all</a><button class="button-primary">Apply filters</button></div></x-office.filter-panel></x-slot:filters>
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:primaryAction><a class="button-primary" href="{{ route('office.catalog.packages.create') }}">Add package</a></x-slot:primaryAction>
        @endif
        @if($packageFilters->isNotEmpty())
            <x-slot:chips>@foreach($packageFilters as $key)<x-office.filter-chip :label="Str::headline($key).': '.Str::headline(request($key))" :remove-url="route('office.catalog.packages.index', request()->except([$key, 'page']))" />@endforeach<a class="inline-flex min-h-9 items-center px-2 text-xs font-bold text-brand-blue underline" href="{{ route('office.catalog.packages.index') }}">Clear all</a></x-slot:chips>
        @endif
    </x-office.primary-toolbar>
    </form>
    <x-office.catalog-tabs />
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Catalog packages</caption><thead><tr><th scope="col">Package</th><th scope="col">Category</th><th scope="col">Sales unit</th><th scope="col">Price</th><th scope="col">Components</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>
        @forelse($packages as $package)<tr><td><a class="font-bold text-brand-blue" href="{{ route('office.catalog.packages.show',$package) }}">{{ $package->package_code }}</a><p class="mt-0.5 font-semibold text-slate-950">{{ $package->name }}</p></td><td>{{ $package->category?->name ?? 'Uncategorized' }}</td><td>{{ $package->salesUom->name }}</td><td>{{ $package->default_price_cents === null ? 'Quote required' : '$'.number_format($package->default_price_cents/100,2) }}</td><td>{{ $package->components_count }}</td><td><span class="{{ $package->active ? 'status-success' : 'status-muted' }}">{{ $package->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.packages.show',$package) }}">Open</a></td></tr>
        @empty<tr><td colspan="7" class="p-3"><x-office.state-panel title="No packages found" message="Create a package or adjust the filters." /></td></tr>@endforelse
    </tbody></table></div>
    <div class="office-mobile-list">@forelse($packages as $package)<article class="office-mobile-card"><div class="flex items-start justify-between gap-3"><div><a class="font-bold text-brand-blue" href="{{ route('office.catalog.packages.show',$package) }}">{{ $package->package_code }}</a><h2 class="mt-1 font-bold text-slate-950">{{ $package->name }}</h2></div><span class="{{ $package->active ? 'status-success' : 'status-muted' }}">{{ $package->active ? 'Active' : 'Inactive' }}</span></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="font-semibold text-slate-500">Price</dt><dd>{{ $package->default_price_cents === null ? 'Quote required' : '$'.number_format($package->default_price_cents/100,2) }}</dd></div><div><dt class="font-semibold text-slate-500">Recipe</dt><dd>{{ $package->components_count }} components</dd></div></dl><a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.packages.show',$package) }}">Open package</a></article>@empty<x-office.state-panel title="No packages found" message="Create a package or adjust the filters." />@endforelse</div>
    <div class="mt-5">{{ $packages->links() }}</div>
</x-layouts.office>
