<nav class="mb-6 flex gap-2 overflow-x-auto border-b border-slate-200" aria-label="Catalog sections">
    @if($activeMembership->hasCapability('catalog.view'))
        <a href="{{ route('office.catalog.services.index') }}" @if(request()->routeIs('office.catalog.services.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.services.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Services</a>
        <a href="{{ route('office.catalog.products.index') }}" @if(request()->routeIs('office.catalog.products.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.products.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Products</a>
        <a href="{{ route('office.catalog.packages.index') }}" @if(request()->routeIs('office.catalog.packages.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.packages.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Packages</a>
        <a href="{{ route('office.catalog.categories.index') }}" @if(request()->routeIs('office.catalog.categories.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.categories.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Categories</a>
        <a href="{{ route('office.catalog.units.index') }}" @if(request()->routeIs('office.catalog.units.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.units.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Units</a>
        @if($activeMembership->hasCapability('catalog.pricing.manage'))<a href="{{ route('office.catalog.labor-roles.index') }}" @if(request()->routeIs('office.catalog.labor-roles.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.catalog.labor-roles.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Labor costs</a>@endif
    @endif
    @if($activeMembership->hasCapability('subscriptions.view'))<a href="{{ route('office.subscriptions.index') }}" @if(request()->routeIs('office.subscriptions.*')) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center border-b-2 px-3 text-sm font-bold {{ request()->routeIs('office.subscriptions.*') ? 'border-brand-blue text-brand-blue-dark' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Customer Services</a>@endif
</nav>
