<x-layouts.office title="Add recurring Service" width="form">
    <a href="{{ route('office.customers.show',$customer) }}#customer-services" class="inline-flex min-h-11 items-center text-sm font-bold text-brand-blue">â† {{ $customer->display_name }}</a>
    <x-office.page-header title="Add recurring Service" description="Create a tracked Customer enrollment from an active recurring Catalog Service." />
    @if($errors->any())<div class="mb-5 rounded-lg border border-red-300 bg-red-50 p-4 text-sm text-red-900" role="alert"><strong>Review the highlighted fields.</strong></div>@endif
    <form method="POST" action="{{ route('office.customers.subscriptions.store',$customer) }}" class="surface space-y-7 p-5 sm:p-6">@csrf
        <fieldset><legend class="text-lg font-bold">Service and scope</legend><div class="mt-4 grid gap-5 sm:grid-cols-2">
            <div class="sm:col-span-2"><label class="form-label" for="catalog_service_id">Recurring Service</label><select class="form-input" id="catalog_service_id" name="catalog_service_id" required data-subscription-service><option value="">Choose a recurring Service</option>@foreach($services as $service)<option value="{{ $service->id }}" data-default-price="{{ $service->default_price_cents === null ? '' : number_format($service->default_price_cents/100,2,'.','') }}" @selected(old('catalog_service_id')==$service->id)>{{ $service->name }} ({{ $service->service_code }}) Â· {{ $service->default_price_cents === null ? 'Price required' : '$'.number_format($service->default_price_cents/100,2) }} every {{ $service->billing_interval }} {{ Str::plural($service->billing_cadence,$service->billing_interval) }}</option>@endforeach</select>@error('catalog_service_id')<p class="form-error">{{ $message }}</p>@enderror @if($services->isEmpty())<p class="mt-2 text-sm text-amber-800">Create an active recurring Catalog Service before adding an enrollment.</p>@endif</div>
            <div><label class="form-label" for="catalog_service_variant_id">Service Variant</label><select class="form-input" id="catalog_service_variant_id" name="catalog_service_variant_id" data-subscription-variant><option value="">No Variant</option>@foreach($services as $service)@foreach($service->variants as $variant)<option value="{{ $variant->id }}" data-service-id="{{ $service->id }}" @selected(old('catalog_service_variant_id')==$variant->id)>{{ $service->name }} â€” {{ $variant->customer_label ?: $variant->label }}</option>@endforeach @endforeach</select>@error('catalog_service_variant_id')<p class="form-error">{{ $message }}</p>@enderror</div>
            <div><label class="form-label" for="service_location_id">Service location</label><select class="form-input" id="service_location_id" name="service_location_id"><option value="">Customer-wide</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('service_location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select>@error('service_location_id')<p class="form-error">{{ $message }}</p>@enderror</div>
        </div></fieldset>
        <fieldset class="border-t border-slate-200 pt-6"><legend class="text-lg font-bold">Dates and amount</legend><div class="mt-4 grid gap-5 sm:grid-cols-2">
            <div><label class="form-label" for="start_date">Start date</label><input class="form-input" id="start_date" name="start_date" type="date" value="{{ old('start_date',now()->toDateString()) }}" required>@error('start_date')<p class="form-error">{{ $message }}</p>@enderror</div>
            <div><label class="form-label" for="end_date">Optional end date</label><input class="form-input" id="end_date" name="end_date" type="date" value="{{ old('end_date') }}">@error('end_date')<p class="form-error">{{ $message }}</p>@enderror</div>
            <div><label class="form-label" for="next_billing_date">Next billing date</label><input class="form-input" id="next_billing_date" name="next_billing_date" type="date" value="{{ old('next_billing_date') }}"><p class="mt-1 text-xs text-slate-500">Tracking only. This date does not generate an Invoice.</p>@error('next_billing_date')<p class="form-error">{{ $message }}</p>@enderror</div>
            <div><label class="form-label" for="billing_amount">Amount override</label><input class="form-input" id="billing_amount" name="billing_amount" inputmode="decimal" value="{{ old('billing_amount') }}" placeholder="Use Catalog default"><p class="mt-1 text-xs text-slate-500">Leave blank to snapshot the current Catalog amount.</p>@error('billing_amount')<p class="form-error">{{ $message }}</p>@enderror</div>
            <div class="sm:col-span-2"><label class="form-label" for="billing_amount_reason">Amount override reason</label><textarea class="form-textarea" id="billing_amount_reason" name="billing_amount_reason" rows="2">{{ old('billing_amount_reason') }}</textarea>@error('billing_amount_reason')<p class="form-error">{{ $message }}</p>@enderror</div>
        </div></fieldset>
        <div class="border-t border-slate-200 pt-6"><label class="form-label" for="internal_notes">Internal enrollment notes</label><textarea class="form-textarea" id="internal_notes" name="internal_notes" rows="4">{{ old('internal_notes') }}</textarea>@error('internal_notes')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div class="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-slate-700"><strong>Tracking foundation only.</strong> Saving this enrollment does not create an Invoice, payment attempt, recurring charge, Service Ticket, or Visit.</div>
        <div class="flex flex-wrap gap-3"><button class="button-primary" @disabled($services->isEmpty())>Create enrollment</button><a href="{{ route('office.customers.show',$customer) }}#customer-services" class="button-secondary">Cancel</a></div>
    </form>
</x-layouts.office>
