<x-layouts.office title="Customer Services" width="workspace">
    @php($subscriptionFilters = collect(['q','status'])->filter(fn ($key) => filled(request($key))))
    <form method="GET" aria-label="Customer Service filters">
    <x-office.primary-toolbar title="Customer Services" description="Track recurring Service enrollments without generating invoices or charging payment methods." eyebrow="Catalog">
        <x-slot:search><label class="sr-only" for="q">Search Customer Services</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" placeholder="Search customer, location, service, or code"></x-slot:search>
        <x-slot:filters><x-office.filter-panel :active-count="$subscriptionFilters->count()"><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All statuses</option>@foreach(App\Models\CustomerServiceEnrollment::STATUSES as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="mt-4 flex justify-end gap-2"><a href="{{ route('office.subscriptions.index') }}" class="button-secondary">Clear all</a><button class="button-primary">Apply filters</button></div></x-office.filter-panel></x-slot:filters>
        @if($subscriptionFilters->isNotEmpty())
            <x-slot:chips>@foreach($subscriptionFilters as $key)<x-office.filter-chip :label="Str::headline($key).': '.Str::headline(request($key))" :remove-url="route('office.subscriptions.index', request()->except([$key, 'page']))" />@endforeach</x-slot:chips>
        @endif
    </x-office.primary-toolbar>
    </form>
    <x-office.catalog-tabs />
    <div class="office-table-wrap"><table class="office-data-table"><thead><tr><th>Customer</th><th>Service</th><th>Scope</th><th>Cadence</th><th>Amount</th><th>Status</th><th><span class="sr-only">Open</span></th></tr></thead><tbody>@forelse($enrollments as $enrollment)<tr><td><a class="font-bold text-slate-950 hover:text-brand-blue" href="{{ route('office.customers.show',$enrollment->customer) }}">{{ $enrollment->customer->display_name }}</a></td><td><strong>{{ $enrollment->service_name_snapshot }}</strong><span class="block text-xs text-slate-500">{{ $enrollment->service_code_snapshot }}</span></td><td>{{ $enrollment->serviceLocation?->name ?: 'Customer-wide' }}</td><td>Every {{ $enrollment->billing_interval }} {{ Str::plural($enrollment->billing_cadence,$enrollment->billing_interval) }}</td><td>${{ number_format($enrollment->billing_amount_cents/100,2) }}</td><td><span class="{{ $enrollment->status === 'active' ? 'status-active' : ($enrollment->status === 'paused' ? 'status-hold' : 'status-inactive') }}">{{ ucfirst($enrollment->status) }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.subscriptions.show',$enrollment) }}">Open<span class="sr-only"> {{ $enrollment->service_name_snapshot }} for {{ $enrollment->customer->display_name }}</span></a></td></tr>@empty<tr><td colspan="7" class="p-3"><x-office.state-panel title="No Customer Services found" message="No recurring Customer Services match these filters." /></td></tr>@endforelse</tbody></table></div>
    <div class="office-mobile-list">@forelse($enrollments as $enrollment)<a href="{{ route('office.subscriptions.show',$enrollment) }}" class="office-mobile-card"><div class="flex justify-between gap-3"><strong>{{ $enrollment->customer->display_name }}</strong><span class="{{ $enrollment->status === 'active' ? 'status-active' : ($enrollment->status === 'paused' ? 'status-hold' : 'status-inactive') }}">{{ ucfirst($enrollment->status) }}</span></div><p class="mt-2 font-semibold">{{ $enrollment->service_name_snapshot }}</p><p class="mt-1 text-sm text-slate-500">{{ $enrollment->serviceLocation?->name ?: 'Customer-wide' }} &middot; ${{ number_format($enrollment->billing_amount_cents/100,2) }}</p></a>@empty<x-office.state-panel title="No Customer Services found" message="No recurring Customer Services match these filters." />@endforelse</div>
    <div class="mt-5">{{ $enrollments->links() }}</div>
</x-layouts.office>
