<x-layouts.office title="Customer Services" width="workspace">
    <x-office.page-header title="Customer Services" description="Track recurring Service enrollments without generating invoices or charging payment methods." />
    <x-office.catalog-tabs />
    <form method="GET" class="office-filter-toolbar">
        <div class="min-w-0 flex-1"><label class="form-label" for="q">Search</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" placeholder="Customer, location, Service, or code"></div>
        <div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All statuses</option>@foreach(App\Models\CustomerServiceEnrollment::STATUSES as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
        <button class="button-primary">Filter</button>
        @if(request()->hasAny(['q','status']))<a href="{{ route('office.subscriptions.index') }}" class="button-secondary">Clear</a>@endif
    </form>
    <div class="office-table-wrap"><table class="office-data-table"><thead><tr><th>Customer</th><th>Service</th><th>Scope</th><th>Cadence</th><th>Amount</th><th>Status</th><th><span class="sr-only">Open</span></th></tr></thead><tbody>@forelse($enrollments as $enrollment)<tr><td><a class="font-bold text-slate-950 hover:text-brand-blue" href="{{ route('office.customers.show',$enrollment->customer) }}">{{ $enrollment->customer->display_name }}</a></td><td><strong>{{ $enrollment->service_name_snapshot }}</strong><span class="block text-xs text-slate-500">{{ $enrollment->service_code_snapshot }}</span></td><td>{{ $enrollment->serviceLocation?->name ?: 'Customer-wide' }}</td><td>Every {{ $enrollment->billing_interval }} {{ Str::plural($enrollment->billing_cadence,$enrollment->billing_interval) }}</td><td>${{ number_format($enrollment->billing_amount_cents/100,2) }}</td><td><span class="{{ $enrollment->status === 'active' ? 'status-active' : ($enrollment->status === 'paused' ? 'status-hold' : 'status-inactive') }}">{{ ucfirst($enrollment->status) }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.subscriptions.show',$enrollment) }}">Open<span class="sr-only"> {{ $enrollment->service_name_snapshot }} for {{ $enrollment->customer->display_name }}</span></a></td></tr>@empty<tr><td colspan="7" class="office-detail-empty">No recurring customer Services match these filters.</td></tr>@endforelse</tbody></table></div>
    <div class="office-mobile-list">@forelse($enrollments as $enrollment)<a href="{{ route('office.subscriptions.show',$enrollment) }}" class="office-mobile-card"><div class="flex justify-between gap-3"><strong>{{ $enrollment->customer->display_name }}</strong><span class="{{ $enrollment->status === 'active' ? 'status-active' : ($enrollment->status === 'paused' ? 'status-hold' : 'status-inactive') }}">{{ ucfirst($enrollment->status) }}</span></div><p class="mt-2 font-semibold">{{ $enrollment->service_name_snapshot }}</p><p class="mt-1 text-sm text-slate-500">{{ $enrollment->serviceLocation?->name ?: 'Customer-wide' }} Â· ${{ number_format($enrollment->billing_amount_cents/100,2) }}</p></a>@empty<p class="office-detail-empty">No recurring customer Services match these filters.</p>@endforelse</div>
    <div class="mt-5">{{ $enrollments->links() }}</div>
</x-layouts.office>
