<x-layouts.office :title="$enrollment->service_name_snapshot" width="detail">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-lg border border-red-300 bg-red-50 p-4 text-sm text-red-900" role="alert"><strong>Review the highlighted fields.</strong></div>@endif
    <x-office.record-header :title="$enrollment->service_name_snapshot" :back-href="route('office.subscriptions.index')" back-label="Customer Services" :description="$enrollment->service_code_snapshot.($enrollment->variant_label_snapshot ? ' Â· '.$enrollment->variant_label_snapshot : '')">
        <x-slot:badges><span class="{{ $enrollment->status === 'active' ? 'status-active' : ($enrollment->status === 'paused' ? 'status-hold' : 'status-inactive') }}">{{ ucfirst($enrollment->status) }}</span></x-slot:badges>
    </x-office.record-header>
    <x-office.catalog-tabs />
    <div class="office-detail-grid"><div class="office-detail-main">
        <section class="office-detail-section p-5"><h2 class="office-detail-section-title">Enrollment</h2><dl class="office-detail-definition mt-5"><div><dt>Customer</dt><dd><a class="font-bold text-brand-blue" href="{{ route('office.customers.show',$enrollment->customer) }}#customer-services">{{ $enrollment->customer->display_name }}</a></dd></div><div><dt>Service location</dt><dd>{{ $enrollment->serviceLocation?->name ?: 'Customer-wide' }}</dd></div><div><dt>Starts</dt><dd>{{ $enrollment->start_date->format('M j, Y') }}</dd></div><div><dt>Ends</dt><dd>{{ $enrollment->end_date?->format('M j, Y') ?: 'No scheduled end' }}</dd></div><div><dt>Next billing date</dt><dd>{{ $enrollment->next_billing_date?->format('M j, Y') ?: 'Not scheduled' }}</dd></div></dl></section>
        @if($activeMembership->hasCapability('subscriptions.manage') && $enrollment->status !== 'canceled')
            <form method="POST" action="{{ route('office.subscriptions.update',$enrollment) }}" class="office-detail-section p-5">@csrf @method('PUT')<h2 class="office-detail-section-title">Manage enrollment</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="form-label" for="start_date">Start date</label><input class="form-input" id="start_date" name="start_date" type="date" value="{{ old('start_date',$enrollment->start_date->toDateString()) }}" required>@error('start_date')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="end_date">End date</label><input class="form-input" id="end_date" name="end_date" type="date" value="{{ old('end_date',$enrollment->end_date?->toDateString()) }}">@error('end_date')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="next_billing_date">Next billing date</label><input class="form-input" id="next_billing_date" name="next_billing_date" type="date" value="{{ old('next_billing_date',$enrollment->next_billing_date?->toDateString()) }}">@error('next_billing_date')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="billing_amount">Enrollment amount</label><input class="form-input" id="billing_amount" name="billing_amount" inputmode="decimal" value="{{ old('billing_amount',number_format($enrollment->billing_amount_cents/100,2,'.','')) }}" required>@error('billing_amount')<p class="form-error">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label class="form-label" for="billing_amount_reason">Amount change reason</label><textarea class="form-textarea" id="billing_amount_reason" name="billing_amount_reason" rows="2">{{ old('billing_amount_reason') }}</textarea>@error('billing_amount_reason')<p class="form-error">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label class="form-label" for="internal_notes">Internal notes</label><textarea class="form-textarea" id="internal_notes" name="internal_notes" rows="4">{{ old('internal_notes',$enrollment->internal_notes) }}</textarea></div></div><button class="button-primary mt-5">Save enrollment</button></form>
            <section class="office-detail-section p-5"><h2 class="office-detail-section-title">Status</h2><p class="mt-2 text-sm text-slate-600">Pausing preserves the enrollment and its current scope. Canceling ends it permanently; restarting requires a new enrollment.</p><div class="mt-4 flex flex-wrap gap-3">@if($enrollment->status==='active')<form method="POST" action="{{ route('office.subscriptions.transition',$enrollment) }}">@csrf<input type="hidden" name="status" value="paused"><input type="hidden" name="confirmation" value="1"><button class="button-secondary">Pause enrollment</button></form>@else<form method="POST" action="{{ route('office.subscriptions.transition',$enrollment) }}">@csrf<input type="hidden" name="status" value="active"><input type="hidden" name="confirmation" value="1"><button class="button-primary">Resume enrollment</button></form>@endif<form method="POST" action="{{ route('office.subscriptions.transition',$enrollment) }}" onsubmit="return confirm('Cancel this recurring Service enrollment? This does not refund payments or alter existing invoices.')">@csrf<input type="hidden" name="status" value="canceled"><input type="hidden" name="confirmation" value="1"><button class="button-danger">Cancel enrollment</button></form></div></section>
        @endif
    </div><aside class="office-detail-rail"><section class="office-detail-section p-5"><h2 class="office-detail-section-title">Commercial snapshot</h2><p class="mt-4 text-2xl font-bold">${{ number_format($enrollment->billing_amount_cents/100,2) }}</p><p class="mt-1 text-sm text-slate-600">Every {{ $enrollment->billing_interval }} {{ Str::plural($enrollment->billing_cadence,$enrollment->billing_interval) }} Â· {{ $enrollment->service_unit_name_snapshot }}</p><dl class="office-detail-definition mt-5"><div><dt>Tax default</dt><dd>{{ $enrollment->taxable_snapshot ? 'Taxable' : 'Non-taxable' }}</dd></div><div><dt>Catalog source</dt><dd>{{ $enrollment->catalogService ? 'Current source available' : 'Historical snapshot only' }}</dd></div></dl></section><section class="office-detail-section p-5"><h2 class="office-detail-section-title">Automation boundary</h2><p class="mt-3 text-sm text-slate-700">This record tracks enrollment intent and billing timing. It does not create invoices, charge Square or Stripe, schedule Visits, or save payment methods.</p></section></aside></div>
</x-layouts.office>
