<x-layouts.office title="New opportunity" width="form">
    <a class="text-sm font-bold text-brand-blue-dark" href="{{ route('office.opportunities.index') }}">← Opportunities</a><h1 class="mt-3 text-3xl font-bold">New opportunity</h1><p class="mt-2 text-slate-600">Capture the customer need and next commercial action. Quote construction is intentionally separate.</p>
    @if($errors->any())<div class="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 text-red-900" role="alert"><p class="font-bold">Opportunity needs attention</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('office.opportunities.store') }}" class="surface mt-6 space-y-5 p-5" data-offline-write>@csrf
        <div><label class="form-label" for="title">Opportunity title</label><input class="form-input" id="title" name="title" value="{{ old('title') }}" required></div>
        <div class="grid gap-4 md:grid-cols-2"><div><label class="form-label" for="customer_id">Customer</label><select class="form-input" id="customer_id" name="customer_id" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id')===(string)$customer->id)>{{ $customer->display_name }}</option>@endforeach</select></div><div><label class="form-label" for="stage_id">Stage</label><select class="form-input" id="stage_id" name="stage_id" required>@foreach($stages->whereNotIn('semantic_kind',['presented','won']) as $stage)<option value="{{ $stage->id }}" @selected((string)old('stage_id',$stages->firstWhere('semantic_kind','new')->id)===(string)$stage->id)>{{ $stage->name }}</option>@endforeach</select></div></div>
        <div class="grid gap-4 md:grid-cols-2"><div><label class="form-label" for="service_location_id">Service location (optional)</label><select class="form-input" id="service_location_id" name="service_location_id"><option value="">Customer-wide</option>@foreach($customers as $customer)@foreach($customer->serviceLocations as $location)<option value="{{ $location->id }}" @selected((string)old('service_location_id')===(string)$location->id)>{{ $customer->display_name }} — {{ $location->name }}</option>@endforeach @endforeach</select></div><div><label class="form-label" for="primary_contact_id">Primary contact (optional)</label><select class="form-input" id="primary_contact_id" name="primary_contact_id"><option value="">No contact selected</option>@foreach($customers as $customer)@foreach($customer->contacts as $contact)<option value="{{ $contact->id }}" @selected((string)old('primary_contact_id')===(string)$contact->id)>{{ $customer->display_name }} — {{ $contact->name }}</option>@endforeach @endforeach</select></div></div>
        <div class="grid gap-4 md:grid-cols-3"><div><label class="form-label" for="owner_user_id">Owner</label><select class="form-input" id="owner_user_id" name="owner_user_id"><option value="">Me</option>@foreach($members as $member)<option value="{{ $member->id }}" @selected((string)old('owner_user_id')===(string)$member->id)>{{ $member->name }}</option>@endforeach</select></div><div><label class="form-label" for="priority">Priority</label><select class="form-input" id="priority" name="priority">@foreach(App\Domain\Commercial\OpportunityWorkflow::PRIORITIES as $priority)<option value="{{ $priority }}" @selected(old('priority','normal')===$priority)>{{ str($priority)->headline() }}</option>@endforeach</select></div><div><label class="form-label" for="estimated_close_on">Estimated close</label><input class="form-input" id="estimated_close_on" type="date" name="estimated_close_on" value="{{ old('estimated_close_on') }}"></div></div>
        <div class="grid gap-4 md:grid-cols-2"><div><label class="form-label" for="estimated_value">Estimated value (USD)</label><div class="relative"><span class="pointer-events-none absolute inset-y-0 left-3 flex items-center text-slate-500" aria-hidden="true">$</span><input class="form-input pl-7" id="estimated_value" name="estimated_value" inputmode="decimal" value="{{ old('estimated_value','0.00') }}" placeholder="0.00" required></div><p class="mt-1 text-xs text-slate-500">Enter dollars and cents without commas.</p></div><div><label class="form-label" for="probability_override_percent">Probability override</label><div class="relative"><input class="form-input pr-9" id="probability_override_percent" name="probability_override_percent" inputmode="decimal" value="{{ old('probability_override_percent') }}" placeholder="Use stage default"><span class="pointer-events-none absolute inset-y-0 right-3 flex items-center text-slate-500" aria-hidden="true">%</span></div></div></div>
        <div><label class="form-label" for="next_action">Next action</label><input class="form-input" id="next_action" name="next_action" maxlength="500" value="{{ old('next_action') }}"></div>
        <div class="grid gap-4 md:grid-cols-3">@foreach(['lead_source'=>'Lead source','referral_source'=>'Referral source','classification'=>'Classification'] as $field=>$label)<div><label class="form-label" for="{{ $field }}">{{ $label }}</label><input class="form-input" id="{{ $field }}" name="{{ $field }}" value="{{ old($field) }}"></div>@endforeach</div>
        <div class="flex gap-3"><button class="button-primary">Create opportunity</button><a class="button-secondary" href="{{ route('office.opportunities.index') }}">Cancel</a></div>
    </form>
</x-layouts.office>
