<x-layouts.print :title="'Completion Summary '.$document['ticket_number']">
    @include('office.service-tickets.documents._toolbar', ['ticketId' => request()->route('serviceTicket')])
    <main class="print-sheet print-sheet-compact" data-print-document="completion-summary">
        @include('office.service-tickets.documents._header', ['profile' => 'COMPLETION SUMMARY', 'audience' => 'Customer service summary', 'ticketNumber' => $document['ticket_number'], 'stateLabel' => $document['status']])
        <section class="print-section"><h2>Who / Where</h2><div class="print-grid print-grid-2"><p><strong>Customer</strong><br>{{ $document['customer'] }}</p><p><strong>Service location</strong><br>{{ $document['location'] }}<br>{{ $document['address'] }}</p></div></section>
        <section class="print-section"><h2>What</h2><h3>{{ $document['title'] }}</h3>@php($completed = collect($document['work_items'])->where('status','completed'))@if($completed->isNotEmpty())<p><strong>Completed Work Items:</strong> {{ $completed->pluck('title')->join(', ') }}</p>@endif @php($followups = collect($document['work_items'])->filter(fn($item) => in_array($item['status'], ['needs_follow_up','transferred'])) )@if($followups->isNotEmpty())<p><strong>Follow-up:</strong> {{ $followups->map(fn($item) => $item['title'].($item['follow_up_ticket'] ? ' · '.$item['follow_up_ticket'] : ''))->join('; ') }}</p>@endif</section>
        <section class="print-section"><h2>When / Outcome</h2>@forelse($document['visits'] as $visit)<article class="print-record"><div class="print-record-heading"><h3>{{ $visit['label'] }}</h3><p>{{ $visit['status'] }}</p></div><p><strong>Technician(s):</strong> {{ implode(', ', $visit['technicians']) ?: 'Not recorded' }}</p>@if($visit['site_window']['start'])<p><strong>Actual on-site window:</strong> {{ $visit['site_window']['start']->timezone($visit['timezone'])->format('M j, Y g:i A') }} – {{ $visit['site_window']['end']->timezone($visit['timezone'])->format('g:i A T') }} · {{ $support->duration($visit['site_window']['duration_seconds']) }} elapsed</p>@else<p class="print-muted">No completed on-site window recorded.</p>@endif @if($visit['work_performed'])<div class="print-prose"><h3>Work performed</h3><p>{{ $visit['work_performed'] }}</p></div>@endif @if($visit['recommendations'])<div class="print-prose"><h3>Recommendations</h3><p>{{ $visit['recommendations'] }}</p></div>@endif @if($visit['outcome'])<p><strong>Outcome:</strong> {{ Str::headline($visit['outcome']) }}</p>@endif @include('office.service-tickets.documents._acknowledgment', ['acknowledgment' => $visit['acknowledgment'], 'timezone' => $visit['timezone']])</article>@empty<p class="print-empty">No service Visits recorded.</p>@endforelse</section>
        <footer class="print-document-footer"><span>{{ $document['ticket_number'] }}</span><span>Completion Summary</span><span>Customer copy</span></footer>
    </main>
</x-layouts.print>
