<x-layouts.print :title="'Customer Service Record '.$document['ticket']['number']">
    @include('office.service-tickets.documents._toolbar', ['ticketId' => request()->route('serviceTicket')])
    <main class="print-sheet" data-print-document="customer-service-record">
        @include('office.service-tickets.documents._header', ['profile' => 'CUSTOMER SERVICE RECORD', 'audience' => 'Customer-safe service history', 'ticketNumber' => $document['ticket']['number'], 'stateLabel' => $document['ticket']['status']])
        <section class="print-section"><h2>Customer / Site</h2><div class="print-grid print-grid-2"><dl class="print-data"><dt>Customer</dt><dd>{{ $document['customer']['name'] }}</dd>@if($document['contact'])<dt>Point of contact</dt><dd>{{ $document['contact']['name'] }}@if($document['contact']['role']) · {{ $document['contact']['role'] }}@endif</dd>@endif</dl><dl class="print-data"><dt>Location</dt><dd>{{ $document['site']['name'] }}</dd><dt>Address</dt><dd>{{ $document['site']['address'] }}</dd></dl></div></section>
        <section class="print-section"><h2>Requested Service</h2><h3>{{ $document['ticket']['title'] }}</h3><p class="print-preserve-lines">{{ $document['ticket']['summary'] ?: $document['ticket']['scope'] ?: 'No customer-facing scope recorded.' }}</p></section>
        <section class="print-section"><h2>Additional Work Items</h2>@forelse($document['work_items'] as $item)<article class="print-record"><div class="print-record-heading"><h3>{{ $item['title'] }}</h3><p>{{ Str::headline($item['status']) }}</p></div><p><strong>Visit / Follow-up:</strong> {{ implode(', ', $item['handled_visits']) ?: ($item['discovered_visit'] ?: 'Not assigned') }}@if($item['follow_up_ticket']) · Follow-up {{ $item['follow_up_ticket'] }}@endif</p></article>@empty<p class="print-empty">No Additional Work Items recorded.</p>@endforelse</section>
        <section class="print-section"><h2>Visit History</h2>@forelse($document['visits'] as $visit)<article class="print-record"><div class="print-record-heading"><h3>{{ $visit['label'] }}</h3><p>{{ $visit['status'] }}</p></div>@if($visit['return_of'])<p><strong>Follow-up to:</strong> {{ $visit['return_of'] }}</p>@endif <p><strong>Technician(s):</strong> {{ implode(', ', $visit['technicians']) ?: 'Not recorded' }}</p>@if($visit['site_window']['start'])<p><strong>On-site service window:</strong> {{ $visit['site_window']['start']->timezone($visit['timezone'])->format('M j, Y g:i A') }} – {{ $visit['site_window']['end']->timezone($visit['timezone'])->format('g:i A T') }} · {{ $support->duration($visit['site_window']['duration_seconds']) }} elapsed</p>@endif @if($visit['work_performed'])<div class="print-prose"><h3>Work performed</h3><p>{{ $visit['work_performed'] }}</p></div>@endif @if($visit['recommendations'])<div class="print-prose"><h3>Recommendations</h3><p>{{ $visit['recommendations'] }}</p></div>@endif @if($visit['parts'])<div class="print-subsection"><h3>Parts / Equipment</h3><ul>@foreach($visit['parts'] as $part)<li>{{ $part['quantity'] }} {{ $part['unit'] }} · {{ $part['description'] }}</li>@endforeach</ul></div>@endif @include('office.service-tickets.documents._acknowledgment', ['acknowledgment' => $visit['acknowledgment'], 'timezone' => $visit['timezone']])</article>@empty<p class="print-empty">No service history recorded.</p>@endforelse</section>
        <footer class="print-document-footer"><span>{{ $document['ticket']['number'] }}</span><span>Customer Service Record</span><span>Customer-safe record</span></footer>
    </main>
</x-layouts.print>
