<x-layouts.print :title="'Technician Work Order '.$ticket->ticket_number">
    @include('office.service-tickets.documents._toolbar', ['ticketId' => $ticket->id])
    <main class="print-sheet" data-print-document="technician-work-order">
        @include('office.service-tickets.documents._header', ['profile' => 'TECHNICIAN WORK ORDER', 'audience' => 'Field / site working copy', 'ticketNumber' => $ticket->ticket_number, 'stateLabel' => $ticket->status])
        @php($contact = $ticket->contact ?: $ticket->serviceLocation->primaryContact)
        <section class="print-section"><h2>Who / Where</h2><div class="print-grid print-grid-2"><dl class="print-data"><dt>Customer</dt><dd>{{ $ticket->customer->display_name }}</dd><dt>Point of contact</dt><dd>{{ $contact?->name ?? 'Not designated' }}@if($contact?->role) · {{ $contact->role }}@endif</dd><dt>Phone</dt><dd>{{ $contact?->phone ?: '—' }}</dd></dl><dl class="print-data"><dt>Service location</dt><dd>{{ $ticket->serviceLocation->name }}</dd><dt>Address</dt><dd>{{ $ticket->serviceLocation->formattedAddress() }}</dd><dt>Timezone</dt><dd>{{ $ticket->serviceLocation->timezone }}</dd></dl></div></section>
        <section class="print-section"><h2>What</h2><h3>{{ $ticket->title }}</h3><div class="print-grid print-grid-3 print-compact-meta"><p><strong>Priority</strong><br>{{ Str::headline($ticket->priority) }}</p><p><strong>Purpose</strong><br>{{ config('service_tickets.purposes.'.$ticket->purpose, Str::headline($ticket->purpose)) }}</p><p><strong>Source</strong><br>{{ Str::headline($ticket->source) }}</p></div><div class="print-prose"><h3>Primary scope</h3><p>{{ $ticket->description ?: 'No scope recorded.' }}</p></div></section>
        <section class="print-section"><h2>Additional Work Items</h2>@if($ticket->workItems->isEmpty())<p class="print-empty">No Additional Work Items recorded.</p>@else<table class="print-table"><thead><tr><th>Work Item</th><th>Status</th><th>Visit / Follow-up</th></tr></thead><tbody>@foreach($ticket->workItems as $item)<tr><td><strong>{{ $item->title }}</strong>@if($item->detail)<br>{{ $item->detail }}@endif</td><td>{{ Str::headline($item->status) }}</td><td>@if($item->discoveredVisit)Discovered {{ $item->discoveredVisit->displayNumber() }}<br>@endif @if($item->visits->isNotEmpty())Handled: {{ $item->visits->sortBy('ticket_visit_number')->map->displayNumber()->join(', ') }}<br>@endif @if($item->followUpServiceTicket)Follow-up: {{ $item->followUpServiceTicket->ticket_number }}@else No follow-up Ticket @endif</td></tr>@endforeach</tbody></table>@endif</section>
        <section class="print-section"><h2>When / Crew</h2>@forelse($ticket->visits as $visit)<article class="print-record"><div class="print-record-heading"><h3>{{ $visit->displayLabel() }}</h3><p>{{ Str::headline($visit->status) }}</p></div><div class="print-grid print-grid-2"><p><strong>Schedule</strong><br>{{ $visit->scheduledStartLocal()?->format('M j, Y g:i A T') ?? 'Unscheduled' }}@if($visit->scheduledEndLocal()) – {{ $visit->scheduledEndLocal()->format('g:i A T') }}@endif</p><p><strong>Crew</strong><br>{{ $visit->assignments->map(fn($a) => ($a->is_lead ? 'Lead: ' : '').$a->membership->user->name)->join(', ') ?: 'Not assigned' }}</p></div>@if($visit->timeEntries->isNotEmpty())<p class="mt-2"><strong>Actual captured time:</strong> {{ $support->duration($visit->timeEntries->sum(fn($entry) => $entry->effective_ended_at ? $entry->effectiveDurationSeconds() : 0)) }}</p>@endif @if($visit->currentCloseout?->parts->isNotEmpty())<div class="print-subsection"><h3>Known parts / materials</h3><ul>@foreach($visit->currentCloseout->parts as $part)<li>{{ $part->quantity }} {{ $part->unit }} · {{ $part->description }}</li>@endforeach</ul></div>@endif @if($visit->currentCloseout)<div class="print-subsection"><h3>Recorded acknowledgment</h3>@include('office.service-tickets.documents._acknowledgment', ['acknowledgment' => $support->acknowledgment($visit->currentCloseout, $ticket->id), 'timezone' => $visit->timezone])</div>@endif</article>@empty<p class="print-empty">No Visits scheduled.</p>@endforelse</section>
        <section class="print-section print-field-notes"><h2>Field Notes</h2><div role="group" aria-label="Blank area for handwritten field notes"></div></section>
        <section class="print-section print-signature-block"><h2>Hard-Copy Customer Acknowledgment</h2><p>{{ config('field_execution.ack_statement') }}</p><div class="print-paper-lines"><p>POC / Customer name: __________________________________________</p><p>Role / relationship: _____________________________________________</p><p>Signature: _____________________________________________________</p><p>Date / time: ___________________________________________________</p><p>Technician / witness: ___________________________________________</p></div><p class="print-muted">This paper block is a physical artifact only and does not satisfy the Portal's digital acknowledgment requirement.</p></section>
        <footer class="print-document-footer"><span>{{ $ticket->ticket_number }}</span><span>Technician Work Order</span><span>Live record</span></footer>
    </main>
</x-layouts.print>
