<section class="invoice-lower-section" aria-label="Invoice notes and totals">
    <div class="surface p-5">
        <h2 class="text-lg font-bold text-slate-950">Customer note</h2>
        @if($invoice->customer_note)<p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $invoice->customer_note }}</p>@else<p class="mt-3 text-sm text-slate-500">No customer note added.</p>@endif
        @if($invoice->isEditable())<button type="button" class="button-secondary mt-4" data-invoice-billing-open>Edit customer note</button>@endif
    </div>
    <div id="totals" class="surface scroll-mt-32 p-5">
        <h2 class="text-lg font-bold text-slate-950">Totals</h2>
        <dl class="mt-4 space-y-2"><div class="flex justify-between"><dt>Subtotal</dt><dd>${{ number_format($invoice->subtotal_cents / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Discount</dt><dd>&minus;${{ number_format($invoice->discount_total_cents / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Tax</dt><dd>${{ number_format($invoice->tax_total_cents / 100, 2) }}</dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-xl font-bold"><dt>Total</dt><dd>${{ number_format($invoice->total_cents / 100, 2) }}</dd></div></dl>
        @if($invoice->status === 'issued')<p class="mt-3 border-t border-slate-200 pt-3 text-sm">PDF: <strong>{{ ucfirst($invoice->pdf_status) }}</strong></p>@if($invoice->pdf_status === 'failed' && $activeMembership->hasCapability('invoices.issue'))<form method="POST" action="{{ route('office.invoices.pdf.retry', $invoice) }}" class="mt-2">@csrf<button class="button-secondary w-full">Retry PDF</button></form>@endif @endif
    </div>
</section>

<div class="space-y-3" data-invoice-supporting-details>
    <details id="approved-work" class="surface scroll-mt-32 overflow-hidden"><summary class="invoice-detail-summary">Approved Work &amp; Billing Sources</summary><div class="border-t border-slate-200 p-5"><div class="space-y-3">@forelse($invoice->closeoutLinks as $link)@php($partAdjustments = $link->review->adjustments->where('type', 'part')->keyBy('visit_part_proposal_id'))<article class="rounded-lg border border-slate-200 p-4"><p class="font-bold">{{ $link->visit->displayLabel() }} &middot; Closeout v{{ $link->closeout->version }}</p><p class="mt-1 text-sm text-slate-600">{{ ucfirst(str_replace('_', ' ', $link->closeout->outcome)) }} &middot; Approved <x-local-time :value="$link->review->decided_at" :timezone="$activeOrganization->timezone" /></p>@if($tripCharge = $link->review->tripCharge)<p class="mt-2 text-sm"><strong>Trip charge selected:</strong> {{ $tripCharge->catalog_name_snapshot }} &middot; {{ intdiv($tripCharge->recorded_travel_seconds, 60) }} recorded en-route minutes &middot; ${{ number_format($tripCharge->catalog_unit_price_cents / 100, 2) }}</p>@else<p class="mt-2 text-sm">Travel recorded: {{ $link->visit->timeEntries->where('category', 'travel')->sum(fn ($entry) => $entry->ended_at ? (int) ceil($entry->started_at->diffInSeconds($entry->ended_at) / 60) : 0) }} minutes &middot; no approved trip charge.</p>@endif @foreach($link->closeout->parts->whereNull('removed_at') as $part)@php($adjustment = $partAdjustments->get($part->id))@php($treatment = $adjustment?->approved_billing_treatment ?? $part->billing_treatment)<div class="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><p><strong>{{ $part->description }}</strong> &middot; {{ $adjustment?->approved_quantity ?? $part->quantity }} {{ $adjustment?->approved_unit ?? $part->unit }} &middot; {{ ucfirst(str_replace('_', ' ', $treatment)) }}</p>@if($treatment !== 'billable' && ! $adjustment?->excluded && ! $invoice->lines->contains('source_part_proposal_id', $part->id) && $invoice->isEditable())<form method="POST" action="{{ route('office.invoices.proposals.include', [$invoice, $part]) }}" class="mt-2 flex flex-wrap gap-2">@csrf<input class="form-input flex-1" name="override_reason" placeholder="Reason to change treatment to billable" aria-label="Billing treatment override reason" required><button class="button-secondary">Add as billable</button></form>@endif</div>@endforeach</article>@empty<p class="text-sm text-slate-500">No approved closeout sources are linked.</p>@endforelse</div></div></details>
    <details class="surface overflow-hidden"><summary class="invoice-detail-summary">Internal Billing Information</summary><div class="border-t border-slate-200 p-5 text-sm text-slate-700"><dl class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="font-semibold text-slate-500">Service Ticket</dt><dd class="mt-1"><a class="font-bold text-brand-blue" href="{{ route('office.service-tickets.show', $invoice->serviceTicket) }}">{{ $invoice->serviceTicket->ticket_number }}</a></dd></div><div><dt class="font-semibold text-slate-500">Billing Handoff</dt><dd class="mt-1">#{{ $invoice->billing_handoff_id }}</dd></div><div><dt class="font-semibold text-slate-500">Invoice generation</dt><dd class="mt-1">{{ $invoice->generation }}</dd></div><div><dt class="font-semibold text-slate-500">Closeout versions</dt><dd class="mt-1">{{ $invoice->closeoutLinks->count() }}</dd></div></dl><div class="mt-5 border-t border-slate-200 pt-4"><p class="font-semibold text-slate-500">Internal billing note</p><p class="mt-2 whitespace-pre-line">{{ $invoice->internal_note ?: 'No internal billing note added.' }}</p></div></div></details>
    <details class="surface overflow-hidden"><summary class="invoice-detail-summary">Audit History</summary><div class="border-t border-slate-200 p-5"><div class="space-y-3">@forelse($auditEvents as $event)<div><p class="text-sm font-semibold text-slate-700">{{ str_replace(['.', '_'], ' ', ucfirst($event->event_type)) }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name ?? 'System' }} &middot; <x-local-time :value="$event->occurred_at" :timezone="$activeOrganization->timezone" format="M j, g:i A T" /></p></div>@empty<p class="text-sm text-slate-500">No invoice history recorded.</p>@endforelse</div></div></details>
</div>
