@if($activeMembership->hasCapability('payments.view') && $invoice->status === 'issued')
    @php
        $openAttempt = $invoice->paymentAttempts->first(fn ($attempt) => $attempt->isOpen());
        $balanceCents = max(0, $invoice->balanceCents());
        $manualErrors = old('payment_form_context') === 'manual';
        $secureErrors = old('payment_form_context') === 'secure';
        $reopenOverlay = session('payment_overlay');
        $selectedConfiguration = $checkoutPaymentProvider ? ($paymentProviders[$checkoutPaymentProvider] ?? null) : null;
        $canSwitchProvider = $activeMembership->hasCapability('payments.settings.manage') && ! $invoice->electronic_payment_provider && ! $openAttempt;
        $alternativeProviders = $paymentProviders->filter(fn ($configuration, $provider) => $configuration->isReady() && $provider !== $checkoutPaymentProvider);
    @endphp

    <section id="payments" class="surface scroll-mt-32 p-5" aria-labelledby="payment-summary-heading" data-payment-summary>
        <div class="flex flex-wrap items-center justify-between gap-4">
            <button type="button" class="min-h-11 text-left" data-payment-overlay-open="payment-history-dialog">
                <span id="payment-summary-heading" class="block text-lg font-bold text-slate-950">Payment history</span>
                <span class="mt-1 block text-sm font-semibold text-brand-blue">{{ ucfirst(str_replace('_', ' ', $invoice->paymentState())) }} &middot; View transactions and receipts</span>
            </button>
            <div class="text-right"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Current balance</p><p class="mt-1 text-2xl font-bold text-slate-950">${{ number_format($balanceCents / 100, 2) }}</p></div>
        </div>
        @if($openAttempt)<button type="button" class="mt-4 w-full rounded-lg border border-amber-300 bg-amber-50 p-4 text-left" data-payment-overlay-open="secure-payment-dialog"><span class="block font-bold text-amber-950">{{ ucfirst($openAttempt->provider) }} payment link is {{ $openAttempt->status }}</span><span class="mt-1 block text-sm text-amber-900">Open the secure-payment workspace to present, refresh, or expire it.</span></button>@endif
    </section>

    @if($activeMembership->hasCapability('payments.record_manual') && ! $openAttempt && $balanceCents > 0)
        <dialog id="record-payment-dialog" class="payment-modal-dialog" data-payment-overlay data-auto-open="{{ $manualErrors ? 'true' : 'false' }}" aria-labelledby="record-payment-title">
            <form method="POST" action="{{ route('office.invoices.payments.manual', $invoice) }}" class="payment-modal-panel">@csrf
                <input type="hidden" name="payment_form_context" value="manual"><input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}">
                <header class="payment-modal-header"><div><p class="text-sm font-bold text-brand-blue">{{ $invoice->invoice_number }}</p><h2 id="record-payment-title" class="mt-1 text-xl font-bold">Record payment</h2></div><button type="button" class="button-secondary min-w-11 px-3" data-payment-overlay-close aria-label="Close record payment">Close</button></header>
                <div class="payment-modal-body">
                    @if($manualErrors)<div class="mb-5 rounded-lg border border-red-300 bg-red-50 p-4 text-red-900" role="alert"><p class="font-bold">Payment details need attention</p><p class="mt-1 text-sm">Review the marked fields and try again.</p></div>@endif
                    <div class="rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Balance due</p><p class="mt-1 text-3xl font-bold">${{ number_format($balanceCents / 100, 2) }}</p></div>
                    <fieldset class="mt-5" data-manual-payment-methods><legend class="form-label">Payment method</legend><div class="grid gap-3 sm:grid-cols-2"><label class="payment-method-choice"><input type="radio" name="method" value="cash" @checked(old('method', 'cash') === 'cash') required> Cash</label><label class="payment-method-choice"><input type="radio" name="method" value="check" @checked(old('method') === 'check') required> Check</label><label class="payment-method-choice"><input type="radio" name="method" value="credit_card" @checked(old('method') === 'credit_card') required> Credit Card &mdash; Square POS</label><label class="payment-method-choice"><input type="radio" name="method" value="debit_card" @checked(old('method') === 'debit_card') required> Debit Card &mdash; Square POS</label></div>@error('method')<p class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror</fieldset>
                    <div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950" data-square-pos-warning hidden><p class="font-bold">Square POS payment already completed</p><p class="mt-1">Record this only after the card payment has successfully completed on the Square POS terminal. Ops Portal does not charge the card or verify the Square transaction from this form.</p></div>
                    <div class="mt-5 grid gap-4 sm:grid-cols-2">
                        <div><label class="form-label" for="manual-payment-amount">Amount</label><input class="form-input" id="manual-payment-amount" name="amount" inputmode="decimal" value="{{ $manualErrors ? old('amount', number_format($balanceCents / 100, 2, '.', '')) : number_format($balanceCents / 100, 2, '.', '') }}" required @if($manualErrors && $errors->has('amount')) aria-invalid="true" aria-describedby="manual-payment-amount-error" @endif>@if($manualErrors)@error('amount')<p id="manual-payment-amount-error" class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror @endif</div>
                        <div><label class="form-label" for="manual-payment-received">Received date and time</label><input class="form-input" id="manual-payment-received" type="datetime-local" name="received_at" value="{{ $manualErrors ? old('received_at', now($activeOrganization->timezone)->format('Y-m-d\TH:i')) : now($activeOrganization->timezone)->format('Y-m-d\TH:i') }}" required @if($manualErrors && $errors->has('received_at')) aria-invalid="true" aria-describedby="manual-payment-received-error" @endif>@if($manualErrors)@error('received_at')<p id="manual-payment-received-error" class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror @endif</div>
                        <div class="sm:col-span-2"><label class="form-label" for="manual-payment-reference">Reference / check / Square transaction ID</label><input class="form-input" id="manual-payment-reference" name="reference" value="{{ $manualErrors ? old('reference') : '' }}" placeholder="Check number or optional Square reference" aria-describedby="manual-payment-reference-help{{ $manualErrors && $errors->has('reference') ? ' manual-payment-reference-error' : '' }}" @if($manualErrors && $errors->has('reference')) aria-invalid="true" @endif><p id="manual-payment-reference-help" class="mt-2 text-sm text-slate-600">Required for checks. For Square POS cards, the Square payment or receipt reference is optional but strongly encouraged for later reconciliation.</p>@if($manualErrors)@error('reference')<p id="manual-payment-reference-error" class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror @endif</div>
                        <div class="sm:col-span-2"><label class="form-label" for="manual-payment-note">Optional internal note</label><textarea class="form-textarea" id="manual-payment-note" name="note" maxlength="2000">{{ $manualErrors ? old('note') : '' }}</textarea>@if($manualErrors)@error('note')<p class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror @endif</div>
                    </div>
                </div>
                <footer class="payment-modal-footer"><button type="button" class="button-secondary" data-payment-overlay-close>Cancel</button><button class="button-primary">Record payment</button></footer>
            </form>
        </dialog>
    @endif

    @if($activeMembership->hasCapability('payments.collect') && $balanceCents > 0)
        <dialog id="secure-payment-dialog" class="payment-modal-dialog" data-payment-overlay data-auto-open="{{ $secureErrors || $reopenOverlay === 'secure' ? 'true' : 'false' }}" aria-labelledby="secure-payment-title">
            <div class="payment-modal-panel">
                <header class="payment-modal-header"><div><p class="text-sm font-bold text-brand-blue">{{ $invoice->invoice_number }}</p><h2 id="secure-payment-title" class="mt-1 text-xl font-bold">Pay securely</h2></div><button type="button" class="button-secondary min-w-11 px-3" data-payment-overlay-close aria-label="Close secure payment">Close</button></header>
                <div class="payment-modal-body">
                    @if($secureErrors)<div class="mb-5 rounded-lg border border-red-300 bg-red-50 p-4 text-red-900" role="alert"><p class="font-bold">Secure payment needs attention</p><p class="mt-1 text-sm">Review the marked fields and try again.</p></div>@endif
                    <div class="flex items-end justify-between gap-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Balance due</p><p class="mt-1 text-3xl font-bold">${{ number_format($balanceCents / 100, 2) }}</p></div>@if($selectedConfiguration)<span class="status-active">Connected</span>@endif</div>
                    @if($openAttempt)
                        <section class="mt-5 text-center" aria-labelledby="payment-link-ready-title"><h3 id="payment-link-ready-title" class="text-lg font-bold">Payment link ready</h3><p class="mt-1 text-sm text-slate-600">{{ ucfirst($openAttempt->provider) }} &middot; ${{ number_format($openAttempt->amount_cents / 100, 2) }}</p>@if($openAttempt->hosted_url)<img class="mx-auto mt-4 h-56 w-56" src="{{ route('office.invoices.payments.qr', [$invoice, $openAttempt]) }}" alt="QR code for secure {{ ucfirst($openAttempt->provider) }} checkout"><label class="sr-only" for="secure-checkout-url">Secure payment link</label><input class="sr-only" id="secure-checkout-url" value="{{ $openAttempt->hosted_url }}" readonly><div class="mt-4 grid gap-3 sm:grid-cols-2"><button type="button" class="button-secondary" data-copy-target="secure-checkout-url">Copy link</button><a class="button-primary" href="{{ $openAttempt->hosted_url }}" rel="noreferrer" target="_blank">Open checkout</a></div>@endif<p class="mt-4 font-semibold">Status: {{ $openAttempt->status === 'processing' ? 'Waiting for payment' : ucfirst($openAttempt->status) }}</p><div class="mt-4 grid gap-3 sm:grid-cols-2"><form method="POST" action="{{ route('office.invoices.payments.reconcile', [$invoice, $openAttempt]) }}">@csrf<button class="button-secondary w-full">Refresh status</button></form>@if($activeMembership->hasCapability('payments.manage_links'))<form method="POST" action="{{ route('office.invoices.payments.expire', [$invoice, $openAttempt]) }}">@csrf<button class="button-danger w-full">Expire link</button></form>@endif</div></section>
                    @elseif($selectedConfiguration?->isReady())
                        <section class="mt-5" aria-labelledby="processor-heading"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Processor</p><h3 id="processor-heading" class="mt-1 text-lg font-bold">{{ ucfirst($checkoutPaymentProvider) }}</h3><p class="mt-1 text-sm text-slate-600">Connected @if($defaultPaymentProvider === $checkoutPaymentProvider)&middot; Organization default @elseif($invoice->preferred_payment_provider === $checkoutPaymentProvider)&middot; Invoice override @endif</p></div><span class="status-active">Ready</span></div>
                            <form method="POST" action="{{ route('office.invoices.payments.checkout', $invoice) }}" class="mt-5">@csrf<input type="hidden" name="payment_form_context" value="secure"><input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><label class="form-label" for="secure-payment-amount">Amount</label><input class="form-input" id="secure-payment-amount" name="amount" inputmode="decimal" value="{{ $secureErrors ? old('amount', number_format($balanceCents / 100, 2, '.', '')) : number_format($balanceCents / 100, 2, '.', '') }}" required @if($secureErrors && $errors->has('amount')) aria-invalid="true" aria-describedby="secure-payment-amount-error" @endif>@if($secureErrors)@error('amount')<p id="secure-payment-amount-error" class="mt-2 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror @endif<button class="button-primary mt-4 w-full">Create secure payment link</button></form>
                            @if($canSwitchProvider && $alternativeProviders->isNotEmpty())<details class="mt-5 border-t border-slate-200 pt-3"><summary class="min-h-11 cursor-pointer py-3 font-bold text-brand-blue">Advanced</summary><div class="rounded-lg bg-slate-50 p-4"><p class="text-sm text-slate-600">Authorized override. The organization default remains unchanged.</p>@foreach($alternativeProviders as $provider => $configuration)<form method="POST" action="{{ route('office.invoices.payments.provider', $invoice) }}" class="mt-3">@csrf @method('PUT')<input type="hidden" name="payment_form_context" value="secure"><input type="hidden" name="preferred_payment_provider" value="{{ $provider }}"><button class="button-secondary w-full">Use {{ ucfirst($provider) }} instead</button></form>@endforeach</div></details>@endif
                        </section>
                    @else
                        <div class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="font-bold">Hosted checkout is not ready</p><p class="mt-1 text-sm text-slate-600">Connect and enable a provider, then choose an organization default in Billing Settings.</p>@if($activeMembership->hasCapability('payments.settings.manage'))<a class="button-secondary mt-4" href="{{ route('office.settings.billing.edit') }}">Open Billing Settings</a>@endif</div>
                    @endif
                </div>
                <footer class="payment-modal-footer"><button type="button" class="button-secondary" data-payment-overlay-close>Close</button></footer>
            </div>
        </dialog>
    @endif

    <dialog id="payment-history-dialog" class="payment-history-dialog" data-payment-overlay data-auto-open="{{ $reopenOverlay === 'history' ? 'true' : 'false' }}" aria-labelledby="payment-history-title">
        <div class="payment-history-panel">
            <header class="payment-modal-header"><div><p class="text-xs font-bold uppercase tracking-[0.08em] text-brand-blue">{{ $invoice->invoice_number }}</p><h2 id="payment-history-title" class="mt-1 text-xl font-bold">Payment history</h2></div><button type="button" class="button-secondary min-w-11 px-3" data-payment-overlay-close aria-label="Close payment history">Close</button></header>
            <div class="payment-modal-body">
                @if(session('receipt_url'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4"><label class="form-label" for="new-receipt-url">New receipt link</label><div class="mt-2 flex gap-2"><input id="new-receipt-url" class="form-input" value="{{ session('receipt_url') }}" readonly><button type="button" class="button-secondary" data-copy-target="new-receipt-url">Copy</button></div></div>@endif
                <div class="divide-y divide-slate-200">@forelse($invoice->paymentTransactions->sortByDesc('received_at') as $transaction)<article class="py-4"><div class="flex items-start justify-between gap-4"><div><p class="font-bold">{{ $transaction->displayMethodLabel() }}</p><p class="mt-1 text-sm text-slate-600"><x-local-time :value="$transaction->received_at" :timezone="$activeOrganization->timezone" format="M j, Y - g:i A T" /> &middot; {{ ucfirst($transaction->status) }}</p>@if($transaction->manual_reference)<p class="mt-1 text-sm text-slate-600">Reference: {{ $transaction->manual_reference }}</p>@endif @if($transaction->receipt)<p class="mt-1 text-sm font-semibold text-emerald-700">Receipt available</p>@endif</div><p @class(['text-lg font-bold', 'text-emerald-700' => $transaction->type === 'payment', 'text-red-700' => $transaction->type !== 'payment'])>{{ $transaction->type === 'payment' ? '+' : '-' }}${{ number_format($transaction->amount_cents / 100, 2) }}</p></div>@if($transaction->receipt && $activeMembership->hasCapability('payments.manage_links'))<form class="mt-3" method="POST" action="{{ route('office.invoices.receipts.link', [$invoice, $transaction->receipt]) }}">@csrf<button class="button-secondary w-full">Create / rotate receipt link</button></form>@endif @if($transaction->type === 'payment' && $transaction->status === 'succeeded' && $activeMembership->hasCapability('payments.refund'))<details class="mt-3"><summary class="min-h-11 cursor-pointer py-3 font-bold text-red-800">Refund or reverse</summary><form class="rounded-lg border border-red-200 bg-red-50 p-4" method="POST" action="{{ route('office.invoices.transactions.refund', [$invoice, $transaction]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}">@if($transaction->payment_source === 'square_pos')<div class="mb-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950" role="note">Recording a reversal here does not refund the card in Square. Complete the refund or reversal in Square separately, then record the corresponding reversal in Ops Portal.</div>@endif<label class="form-label" for="refund-amount-{{ $transaction->id }}">Amount</label><input id="refund-amount-{{ $transaction->id }}" class="form-input" name="amount" inputmode="decimal" required><label class="form-label mt-3" for="refund-reason-{{ $transaction->id }}">Required reason</label><textarea id="refund-reason-{{ $transaction->id }}" class="form-textarea" name="reason" required></textarea><button class="button-danger mt-3 w-full">{{ $transaction->usesManualReversal() ? 'Record reversal' : 'Request refund' }}</button></form></details>@endif</article>@empty<p class="py-8 text-center text-sm text-slate-600">No payment history yet.</p>@endforelse</div>
            </div>
            <footer class="payment-history-footer"><div class="mr-auto"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Current balance</p><p class="mt-1 text-2xl font-bold">${{ number_format($balanceCents / 100, 2) }}</p></div>@if(! $openAttempt && $balanceCents > 0 && $activeMembership->hasCapability('payments.record_manual'))<button type="button" class="button-secondary" data-payment-overlay-switch="record-payment-dialog">Record payment</button>@endif @if($balanceCents > 0 && $activeMembership->hasCapability('payments.collect'))<button type="button" class="button-primary" data-payment-overlay-switch="secure-payment-dialog">Pay securely</button>@endif</footer>
        </div>
    </dialog>
@endif
