@if($activeMembership->hasCapability('payments.view') && $invoice->status === 'issued')
    <div id="payments" class="scroll-mt-32" aria-hidden="true"></div>
    <section class="surface p-5">
        <div class="flex items-start justify-between gap-3"><div><h2 class="text-xl font-bold">Payments</h2><p class="mt-1 text-sm text-slate-600">{{ ucfirst(str_replace('_', ' ', $invoice->paymentState())) }}</p></div><p class="text-2xl font-bold">${{ number_format(max(0, $invoice->balanceCents()) / 100, 2) }}</p></div>
        @if(session('receipt_url'))<div class="mt-4 rounded-lg border border-emerald-300 bg-emerald-50 p-3"><label class="form-label" for="new-receipt-url">New receipt link</label><div class="flex gap-2"><input id="new-receipt-url" class="form-input" value="{{ session('receipt_url') }}" readonly><button type="button" class="button-secondary" data-copy-target="new-receipt-url">Copy</button></div></div>@endif
        @php($openAttempt = $invoice->paymentAttempts->first(fn ($attempt) => $attempt->isOpen()))
        @if($openAttempt)
            <div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p class="font-bold">{{ ucfirst($openAttempt->provider) }} checkout {{ $openAttempt->status }}</p><p class="mt-1 text-sm">${{ number_format($openAttempt->amount_cents / 100, 2) }} &middot; created <x-local-time :value="$openAttempt->created_at" :timezone="$activeOrganization->timezone" /></p>@if($openAttempt->hosted_url)<img class="mx-auto mt-3 h-44 w-44" src="{{ route('office.invoices.payments.qr', [$invoice, $openAttempt]) }}" alt="QR code for hosted checkout"><label class="form-label mt-3" for="checkout-url-{{ $openAttempt->id }}">Hosted checkout link</label><div class="flex gap-2"><input class="form-input" id="checkout-url-{{ $openAttempt->id }}" value="{{ $openAttempt->hosted_url }}" readonly><button type="button" class="button-secondary" data-copy-target="checkout-url-{{ $openAttempt->id }}">Copy</button></div>@endif<div class="mt-3 grid gap-2 sm:grid-cols-2"><form method="POST" action="{{ route('office.invoices.payments.reconcile', [$invoice, $openAttempt]) }}">@csrf<button class="button-secondary w-full">Refresh / reconcile</button></form>@if($activeMembership->hasCapability('payments.manage_links'))<form method="POST" action="{{ route('office.invoices.payments.expire', [$invoice, $openAttempt]) }}">@csrf<button class="button-danger w-full">Expire checkout</button></form>@endif</div></div>
        @elseif($invoice->balanceCents() > 0 && $activeMembership->hasCapability('payments.collect') && $checkoutPaymentProvider && ($paymentProviders[$checkoutPaymentProvider] ?? null)?->isReady())
            <form id="hosted-checkout" method="POST" action="{{ route('office.invoices.payments.checkout', $invoice) }}" class="mt-4 scroll-mt-32">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><label class="form-label" for="checkout-amount">Hosted checkout amount</label><input class="form-input" id="checkout-amount" name="amount" inputmode="decimal" value="{{ number_format($invoice->balanceCents() / 100, 2, '.', '') }}" required><button class="button-primary mt-3 w-full">Create secure checkout</button><p class="mt-2 text-xs text-slate-600">Processor: {{ ucfirst($checkoutPaymentProvider) }}{{ $invoice->electronic_payment_provider ? ' · locked by a successful payment' : ' · organization routing' }}</p></form>
        @elseif($invoice->balanceCents() > 0 && $activeMembership->hasCapability('payments.collect'))
            <p id="hosted-checkout" class="mt-4 scroll-mt-32 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">Connect one ready provider or choose an organization default in Billing Settings. Cash and check remain available below.</p>
        @endif
        @if(! $openAttempt && $invoice->balanceCents() > 0 && $activeMembership->hasCapability('payments.record_manual'))
            <form id="record-manual-payment" method="POST" action="{{ route('office.invoices.payments.manual', $invoice) }}" class="mt-5 scroll-mt-32 border-t border-slate-200 pt-4">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><h3 class="font-bold">Record cash or check</h3><div class="mt-3 grid gap-3"><select class="form-input" name="method" aria-label="Manual payment method"><option value="cash">Cash</option><option value="check">Check</option></select><input class="form-input" name="amount" value="{{ number_format($invoice->balanceCents() / 100, 2, '.', '') }}" inputmode="decimal" aria-label="Payment amount" required><input class="form-input" type="datetime-local" name="received_at" value="{{ now($activeOrganization->timezone)->format('Y-m-d\TH:i') }}" aria-label="Received date and time" required><input class="form-input" name="reference" placeholder="Check reference (required for checks)" aria-label="Check reference"><button class="button-secondary">Record payment</button></div></form>
        @endif
        <div class="mt-5 space-y-3">@forelse($invoice->paymentTransactions->sortByDesc('received_at') as $transaction)<article class="rounded-lg border border-slate-200 p-3"><div class="flex justify-between gap-3"><div><p class="font-bold">{{ ucfirst($transaction->type) }} &middot; {{ ucfirst($transaction->method) }}</p><p class="text-sm text-slate-600"><x-local-time :value="$transaction->received_at" :timezone="$activeOrganization->timezone" /> &middot; {{ ucfirst($transaction->status) }}</p></div><p class="font-bold">${{ number_format($transaction->amount_cents / 100, 2) }}</p></div>@if($transaction->receipt && $activeMembership->hasCapability('payments.manage_links'))<form class="mt-2" method="POST" action="{{ route('office.invoices.receipts.link', [$invoice, $transaction->receipt]) }}">@csrf<button class="button-secondary w-full">Create / rotate receipt link</button></form>@endif @if($transaction->type === 'payment' && $transaction->status === 'succeeded' && $activeMembership->hasCapability('payments.refund'))<form class="mt-3 border-t border-slate-200 pt-3" method="POST" action="{{ route('office.invoices.transactions.refund', [$invoice, $transaction]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><input class="form-input" name="amount" placeholder="Refund amount" inputmode="decimal" required><textarea class="form-input mt-2" name="reason" placeholder="Required reason" aria-label="Refund or reversal reason" required></textarea><button class="button-danger mt-2 w-full">{{ in_array($transaction->method, ['cash', 'check'], true) ? 'Record reversal' : 'Refund' }}</button></form>@endif</article>@empty<p class="text-sm text-slate-600">No payment history yet.</p>@endforelse</div>
    </section>
@endif
