<x-layouts.office :title="$invoice->invoice_number" width="workspace">
    <x-office.invoice-command-bar :invoice="$invoice" :can-delete-draft="$canDeleteDraft ?? false" />
    @if(session('status'))<div class="mt-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 text-red-900" role="alert"><p class="font-bold">Invoice needs attention</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if($invoice->status==='void')<div class="mt-5 rounded-lg border border-red-300 bg-red-50 p-4 font-semibold text-red-900">This invoice is void and immutable. Open the current invoice from Billing.</div>@endif
    @include('office.invoices._billing-summary')

    <div class="invoice-workspace" data-invoice-workspace>
        <div class="space-y-6">
            <div id="approved-work" class="scroll-mt-6" aria-hidden="true"></div>
            <section class="surface p-5"><h2 class="text-xl font-bold">Approved work included</h2><div class="mt-4 space-y-3">@foreach($invoice->closeoutLinks as $link)@php($partAdjustments=$link->review->adjustments->where('type','part')->keyBy('visit_part_proposal_id'))<article class="rounded-lg border border-slate-200 p-4"><p class="font-bold">{{ $link->visit->displayLabel() }} · Closeout v{{ $link->closeout->version }}</p><p class="mt-1 text-sm text-slate-600">{{ ucfirst(str_replace('_',' ',$link->closeout->outcome)) }} · Approved <x-local-time :value="$link->review->decided_at" :timezone="$activeOrganization->timezone" /></p><p class="mt-2 text-sm">Travel recorded: {{ $link->visit->timeEntries->where('category','travel')->sum(fn($entry)=>$entry->ended_at ? (int)ceil($entry->started_at->diffInSeconds($entry->ended_at)/60) : 0) }} minutes · not charged automatically.</p>@foreach($link->closeout->parts->whereNull('removed_at') as $part)@php($adjustment=$partAdjustments->get($part->id))@php($treatment=$adjustment?->approved_billing_treatment ?? $part->billing_treatment)<div class="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><p><strong>{{ $part->description }}</strong> · {{ $adjustment?->approved_quantity ?? $part->quantity }} {{ $adjustment?->approved_unit ?? $part->unit }} · {{ ucfirst(str_replace('_',' ',$treatment)) }}</p>@if($treatment!=='billable' && !$adjustment?->excluded && !$invoice->lines->contains('source_part_proposal_id',$part->id) && $invoice->isEditable())<form method="POST" action="{{ route('office.invoices.proposals.include',[$invoice,$part]) }}" class="mt-2 flex flex-wrap gap-2">@csrf<input class="form-input flex-1" name="override_reason" placeholder="Reason to change treatment to billable" aria-label="Billing treatment override reason" required><button class="button-secondary">Add as billable</button></form>@endif</div>@endforeach</article>@endforeach</div></section>

            <div id="invoice-lines" class="scroll-mt-6" aria-hidden="true"></div>
            <section class="surface p-5"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-bold">Invoice lines</h2><p class="mt-1 text-sm text-slate-600">Generated evidence and Catalog source snapshots remain unchanged. Price and inclusion edits are invoice-only.</p></div>@if($invoice->isEditable() && $canUseCatalog)<x-catalog-picker id="invoice-catalog-picker" :action="route('office.invoices.catalog-lines.store', $invoice)" :services="$catalogServices" :products="$catalogProducts" :packages="$catalogPackages" :show-prices="true" />@endif</div>
                <div class="mt-4 space-y-4">@foreach($invoice->lines as $line)<form method="POST" action="{{ route('office.invoices.lines.update',[$invoice,$line]) }}" class="rounded-lg border border-slate-200 p-4">@csrf @method('PUT')
                    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                        @if($line->catalog_item_type)<div class="md:col-span-2 xl:col-span-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm"><div class="flex flex-wrap items-center justify-between gap-2"><p><span class="status-active">Catalog {{ ucfirst($line->catalog_item_type) }}</span> <strong class="ml-2">{{ $line->catalog_name_snapshot }}</strong> · {{ $line->catalog_code_snapshot }}</p><p>Snapshotted default: {{ $line->catalog_original_unit_price_cents === null ? 'Price required' : '$'.number_format($line->catalog_original_unit_price_cents / 100, 2) }}</p></div>@if($line->catalog_package_recipe_snapshot)<details class="mt-2"><summary class="min-h-11 cursor-pointer py-2 font-bold text-brand-blue">Internal Package recipe and expected demand</summary><p class="text-xs text-slate-600">{{ count($line->catalog_package_recipe_snapshot['recipe'] ?? []) }} snapshotted components. This internal recipe is not rendered on customer invoice documents.</p></details>@endif</div>@endif
                        <div><label class="form-label" for="type-{{ $line->id }}">Type</label><select class="form-input" id="type-{{ $line->id }}" name="line_type">@foreach(['labor','travel','service_charge','part','equipment','other'] as $type)<option value="{{ $type }}" @selected($line->line_type===$type)>{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select></div>
                        <div class="md:col-span-1 xl:col-span-3"><label class="form-label" for="description-{{ $line->id }}">Description</label><input class="form-input" id="description-{{ $line->id }}" name="description" value="{{ $line->description }}" required></div>
                        <div><label class="form-label" for="quantity-{{ $line->id }}">Quantity</label><input class="form-input" id="quantity-{{ $line->id }}" name="quantity" value="{{ rtrim(rtrim(number_format($line->quantity_millis/1000,3,'.',''),'0'),'.') }}" required></div>
                        <div><label class="form-label" for="unit-{{ $line->id }}">Unit</label><input class="form-input" id="unit-{{ $line->id }}" name="unit" value="{{ $line->unit }}"></div>
                        <div><label class="form-label" for="price-{{ $line->id }}">Unit price</label><input class="form-input" id="price-{{ $line->id }}" name="unit_price" value="{{ $line->unit_price_cents===null ? '' : number_format($line->unit_price_cents/100,2,'.','') }}" inputmode="decimal" required></div>
                        <div><label class="form-label" for="treatment-{{ $line->id }}">Treatment</label><select class="form-input" id="treatment-{{ $line->id }}" name="billing_treatment"><option value="">Not applicable</option>@foreach(['billable','warranty','customer_owned','no_charge'] as $t)<option value="{{ $t }}" @selected($line->billing_treatment===$t)>{{ ucfirst(str_replace('_',' ',$t)) }}</option>@endforeach</select></div>
                        @if($line->line_type==='labor')<div><label class="form-label" for="rate-{{ $line->id }}">Named rate</label><select class="form-input" id="rate-{{ $line->id }}" name="labor_rate_id"><option value="">Manual</option>@foreach($rates as $rate)<option value="{{ $rate->id }}" @selected($line->labor_rate_id===$rate->id)>{{ $rate->name }} · ${{ number_format($rate->hourly_rate_cents/100,2) }}/hr</option>@endforeach</select></div>@else<input type="hidden" name="labor_rate_id" value="">@endif
                        <div class="flex min-h-11 items-center gap-5"><label class="flex items-center gap-2"><input type="checkbox" name="included" value="1" @checked($line->included)> Included</label><label class="flex items-center gap-2"><input type="checkbox" name="taxable" value="1" @checked($line->taxable)> Taxable</label></div>
                        <div class="md:col-span-2 xl:col-span-3"><label class="form-label" for="reason-{{ $line->id }}">Reason for invoice adjustment</label><input class="form-input" id="reason-{{ $line->id }}" name="override_reason" required></div>
                        <div class="flex items-end justify-between gap-3"><p class="pb-3 font-bold">Line total ${{ number_format($line->total_cents/100,2) }}</p><button class="button-secondary">Save line</button></div>
                    </div>
                </form>@endforeach</div>
                @if($invoice->isEditable())<form method="POST" action="{{ route('office.invoices.lines.store',$invoice) }}" class="mt-6 border-t border-slate-200 pt-5">@csrf<h3 class="font-bold">Add custom manual line</h3><p class="mt-1 text-sm text-slate-600">Manual lines remain available for one-off work that does not belong in the Catalog.</p><div class="mt-3 grid gap-3 md:grid-cols-3"><select class="form-input" name="line_type" aria-label="Line type">@foreach(['service_charge','travel','equipment','other'] as $type)<option value="{{ $type }}">{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select><input class="form-input md:col-span-2" name="description" placeholder="Customer-facing description" aria-label="Description" required><input class="form-input" name="quantity" value="1" aria-label="Quantity" required><input class="form-input" name="unit" placeholder="Unit" aria-label="Unit"><input class="form-input" name="unit_price" placeholder="0.00" aria-label="Unit price" required><input type="hidden" name="included" value="1"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="taxable" value="1"> Taxable</label><input class="form-input md:col-span-2" name="override_reason" placeholder="Reason for manual charge" aria-label="Reason" required><button class="button-primary">Add manual line</button></div></form>@endif
            </section>
        </div>

        <div class="space-y-6">
            <div id="totals" class="scroll-mt-6" aria-hidden="true"></div>
            <section class="surface p-5"><h2 class="text-xl font-bold">Totals</h2><dl class="mt-4 space-y-2"><div class="flex justify-between"><dt>Subtotal</dt><dd>${{ number_format($invoice->subtotal_cents/100,2) }}</dd></div><div class="flex justify-between"><dt>Discount</dt><dd>−${{ number_format($invoice->discount_total_cents/100,2) }}</dd></div><div class="flex justify-between"><dt>Tax</dt><dd>${{ number_format($invoice->tax_total_cents/100,2) }}</dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-xl font-bold"><dt>Total</dt><dd>${{ number_format($invoice->total_cents/100,2) }}</dd></div></dl>
                @if($invoice->status==='issued')<p class="mt-3 border-t border-slate-200 pt-3 text-sm">PDF: <strong>{{ ucfirst($invoice->pdf_status) }}</strong></p>@if($invoice->pdf_status==='failed' && $activeMembership->hasCapability('invoices.issue'))<form method="POST" action="{{ route('office.invoices.pdf.retry',$invoice) }}" class="mt-2">@csrf<button class="button-secondary w-full">Retry PDF</button></form>@endif @endif
            </section>
            @if($activeMembership->hasCapability('invoices.void') && $invoice->status!=='void')<form id="void-reissue" method="POST" action="{{ route('office.invoices.void',$invoice) }}" class="surface scroll-mt-32 border-red-200 p-5">@csrf<input type="hidden" name="void_token" value="{{ Str::uuid() }}"><h2 class="font-bold text-red-800">Void and reissue</h2><label class="form-label mt-3" for="void_reason">Reason</label><textarea class="form-textarea" id="void_reason" name="void_reason" required></textarea><label class="mt-3 flex min-h-11 items-center gap-2"><input type="checkbox" name="confirm_void" value="1" required> Create a newly numbered replacement</label><button class="button-danger mt-3 w-full">Void and reissue</button></form>@endif
            @if($canDeleteDraft ?? false)<form id="delete-unissued-invoice" method="POST" action="{{ route('office.invoices.destroy',$invoice) }}" class="surface scroll-mt-32 border-red-300 bg-red-50 p-5">@csrf @method('DELETE')<h2 class="font-bold text-red-900">Delete unissued invoice</h2><p class="mt-2 text-sm text-red-800">This removes the draft and returns the Billing Handoff to Ready. Issued invoices must use Void and reissue.</p><label class="form-label mt-3" for="deletion_reason">Deletion reason</label><textarea class="form-textarea" id="deletion_reason" name="deletion_reason" required maxlength="2000"></textarea><label class="form-label mt-3" for="confirm_invoice_number">Enter {{ $invoice->invoice_number }} to confirm</label><input class="form-input" id="confirm_invoice_number" name="confirm_invoice_number" required autocomplete="off"><label class="mt-3 flex min-h-11 items-center gap-2"><input type="checkbox" name="confirm_delete" value="1" required> I understand this invoice will be removed.</label><button class="button-danger mt-3 w-full">Delete unissued invoice</button></form>@endif
            @if($activeMembership->hasCapability('payments.view') && $invoice->status==='issued')
                <div id="payments" class="scroll-mt-6" aria-hidden="true"></div>
                <section class="surface p-5"><div class="flex items-start justify-between gap-3"><div><h2 class="text-xl font-bold">Payments</h2><p class="mt-1 text-sm text-slate-600">{{ ucfirst(str_replace('_',' ',$invoice->paymentState())) }}</p></div><p class="text-2xl font-bold">${{ number_format(max(0,$invoice->balanceCents())/100,2) }}</p></div>
                    @if(session('receipt_url'))<div class="mt-4 rounded-lg border border-emerald-300 bg-emerald-50 p-3"><label class="form-label" for="new-receipt-url">New receipt link</label><div class="flex gap-2"><input id="new-receipt-url" class="form-input" value="{{ session('receipt_url') }}" readonly><button type="button" class="button-secondary" data-copy-target="new-receipt-url">Copy</button></div></div>@endif
                    @php($openAttempt=$invoice->paymentAttempts->first(fn($attempt)=>$attempt->isOpen()))
                    @if($openAttempt)<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p class="font-bold">{{ ucfirst($openAttempt->provider) }} checkout {{ $openAttempt->status }}</p><p class="mt-1 text-sm">${{ number_format($openAttempt->amount_cents/100,2) }} · created <x-local-time :value="$openAttempt->created_at" :timezone="$activeOrganization->timezone" /></p>@if($openAttempt->hosted_url)<img class="mx-auto mt-3 h-44 w-44" src="{{ route('office.invoices.payments.qr',[$invoice,$openAttempt]) }}" alt="QR code for hosted checkout"><label class="form-label mt-3" for="checkout-url-{{ $openAttempt->id }}">Hosted checkout link</label><div class="flex gap-2"><input class="form-input" id="checkout-url-{{ $openAttempt->id }}" value="{{ $openAttempt->hosted_url }}" readonly><button type="button" class="button-secondary" data-copy-target="checkout-url-{{ $openAttempt->id }}">Copy</button></div>@endif<div class="mt-3 grid gap-2 sm:grid-cols-2"><form method="POST" action="{{ route('office.invoices.payments.reconcile',[$invoice,$openAttempt]) }}">@csrf<button class="button-secondary w-full">Refresh / reconcile</button></form>@if($activeMembership->hasCapability('payments.manage_links'))<form method="POST" action="{{ route('office.invoices.payments.expire',[$invoice,$openAttempt]) }}">@csrf<button class="button-danger w-full">Expire checkout</button></form>@endif</div></div>
                    @elseif($invoice->balanceCents()>0 && $activeMembership->hasCapability('payments.collect') && $checkoutPaymentProvider && ($paymentProviders[$checkoutPaymentProvider] ?? null)?->isReady())<form id="hosted-checkout" method="POST" action="{{ route('office.invoices.payments.checkout',$invoice) }}" class="mt-4 scroll-mt-32">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><label class="form-label" for="checkout-amount">Hosted checkout amount</label><input class="form-input" id="checkout-amount" name="amount" inputmode="decimal" value="{{ number_format($invoice->balanceCents()/100,2,'.','') }}" required><button class="button-primary mt-3 w-full">Create secure checkout</button><p class="mt-2 text-xs text-slate-600">Processor: {{ ucfirst($checkoutPaymentProvider) }}{{ $invoice->electronic_payment_provider ? ' · locked by a successful payment' : ' · organization routing' }}</p></form>@elseif($invoice->balanceCents()>0 && $activeMembership->hasCapability('payments.collect'))<p id="hosted-checkout" class="mt-4 scroll-mt-32 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">Connect one ready provider or choose an organization default in Billing Settings. Cash and check remain available below.</p>@endif
                    @if(!$openAttempt && $invoice->balanceCents()>0 && $activeMembership->hasCapability('payments.record_manual'))<form id="record-manual-payment" method="POST" action="{{ route('office.invoices.payments.manual',$invoice) }}" class="mt-5 scroll-mt-32 border-t border-slate-200 pt-4">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><h3 class="font-bold">Record cash or check</h3><div class="mt-3 grid gap-3"><select class="form-input" name="method" aria-label="Manual payment method"><option value="cash">Cash</option><option value="check">Check</option></select><input class="form-input" name="amount" value="{{ number_format($invoice->balanceCents()/100,2,'.','') }}" inputmode="decimal" aria-label="Payment amount" required><input class="form-input" type="datetime-local" name="received_at" value="{{ now($activeOrganization->timezone)->format('Y-m-d\TH:i') }}" aria-label="Received date and time" required><input class="form-input" name="reference" placeholder="Check reference (required for checks)" aria-label="Check reference"><button class="button-secondary">Record payment</button></div></form>@endif
                    <div class="mt-5 space-y-3">@forelse($invoice->paymentTransactions->sortByDesc('received_at') as $transaction)<article class="rounded-lg border border-slate-200 p-3"><div class="flex justify-between gap-3"><div><p class="font-bold">{{ ucfirst($transaction->type) }} · {{ ucfirst($transaction->method) }}</p><p class="text-sm text-slate-600"><x-local-time :value="$transaction->received_at" :timezone="$activeOrganization->timezone" /> · {{ ucfirst($transaction->status) }}</p></div><p class="font-bold">${{ number_format($transaction->amount_cents/100,2) }}</p></div>@if($transaction->receipt && $activeMembership->hasCapability('payments.manage_links'))<form class="mt-2" method="POST" action="{{ route('office.invoices.receipts.link',[$invoice,$transaction->receipt]) }}">@csrf<button class="button-secondary w-full">Create / rotate receipt link</button></form>@endif @if($transaction->type==='payment' && $transaction->status==='succeeded' && $activeMembership->hasCapability('payments.refund'))<form class="mt-3 border-t border-slate-200 pt-3" method="POST" action="{{ route('office.invoices.transactions.refund',[$invoice,$transaction]) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ Str::uuid() }}"><input class="form-input" name="amount" placeholder="Refund amount" inputmode="decimal" required><textarea class="form-input mt-2" name="reason" placeholder="Required reason" aria-label="Refund or reversal reason" required></textarea><button class="button-danger mt-2 w-full">{{ in_array($transaction->method,['cash','check'],true) ? 'Record reversal' : 'Refund' }}</button></form>@endif</article>@empty<p class="text-sm text-slate-600">No payment history yet.</p>@endforelse</div>
                </section>
            @endif
        </div>
    </div>
</x-layouts.office>
