<x-layouts.office title="Proposal library" width="workspace">
    <div class="space-y-6">
        <header><p class="text-sm font-bold uppercase tracking-[.12em] text-brand-blue">Commercial settings</p><h1 class="mt-1 text-3xl font-bold">Proposal library</h1><p class="mt-2 text-slate-600">Reusable scope, immutable terms versions, and the four V1 presentation templates.</p></header>
        <div class="grid gap-6 xl:grid-cols-3">
            <section class="surface overflow-hidden">
                <header class="border-b border-slate-200 p-5"><h2 class="text-xl font-bold">Scope blocks</h2></header>
                <div class="divide-y divide-slate-200">@foreach($blocks as $block)<article class="p-4"><p class="font-bold">{{ $block->name }}</p><p class="text-sm text-slate-600">{{ $block->heading }}</p></article>@endforeach</div>
                <form method="POST" action="{{ route('office.commercial-library.blocks.store') }}" class="space-y-3 border-t border-slate-200 bg-slate-50 p-5">@csrf<label class="form-label" for="block-name">Library name</label><input class="form-input" id="block-name" name="name" required><label class="form-label" for="block-heading">Customer heading</label><input class="form-input" id="block-heading" name="heading" required><label class="form-label" for="block-body">Content</label><textarea class="form-textarea" id="block-body" name="body"></textarea><button class="button-primary w-full">Create scope block</button></form>
            </section>
            <section class="surface overflow-hidden">
                <header class="border-b border-slate-200 p-5"><h2 class="text-xl font-bold">Approved terms</h2></header>
                <div class="divide-y divide-slate-200">@foreach($terms as $set)<article class="p-4"><p class="font-bold">{{ $set->name }} · v{{ $set->version }}</p><p class="text-sm text-slate-600">{{ $set->code }}</p></article>@endforeach</div>
                <form method="POST" action="{{ route('office.commercial-library.terms.store') }}" class="space-y-3 border-t border-slate-200 bg-slate-50 p-5">@csrf<label class="form-label" for="terms-code">Stable code</label><input class="form-input" id="terms-code" name="code" required><label class="form-label" for="terms-name">Name</label><input class="form-input" id="terms-name" name="name" required><label class="form-label" for="terms-library-body">Terms</label><textarea class="form-textarea min-h-40" id="terms-library-body" name="body" required></textarea><button class="button-primary w-full">Create approved version</button></form>
            </section>
            <section class="space-y-4">
                <h2 class="text-xl font-bold">Templates</h2>
                @foreach($templates as $template)
                    <article class="surface overflow-hidden">
                        <form method="POST" action="{{ route('office.commercial-library.templates.update',$template) }}" class="space-y-3 p-5">@csrf @method('PUT')<p class="text-xs font-bold uppercase text-brand-blue">{{ str($template->template_type)->headline() }}</p><label class="form-label" for="template-name-{{ $template->id }}">Name</label><input class="form-input" id="template-name-{{ $template->id }}" name="name" value="{{ $template->name }}" required><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="acceptance_enabled" value="1" @checked($template->acceptance_enabled)> Acceptance enabled</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" @checked($template->active)> Active</label><button class="button-secondary w-full">Save template</button></form>
                        <details class="border-t border-slate-200"><summary class="min-h-11 cursor-pointer px-5 py-3 font-bold">Sections · {{ $template->sections->count() }}</summary><div class="divide-y divide-slate-200 border-t border-slate-200">@foreach($template->sections as $section)<form method="POST" action="{{ route('office.commercial-library.templates.sections.update',[$template,$section]) }}" class="space-y-2 p-4">@csrf @method('PUT')<p class="text-xs font-bold uppercase text-slate-500">{{ str($section->section_type)->headline() }}</p><label class="form-label" for="section-heading-{{ $section->id }}">Heading</label><input class="form-input" id="section-heading-{{ $section->id }}" name="heading" value="{{ $section->heading }}" required><label class="form-label" for="section-order-{{ $section->id }}">Order</label><input class="form-input" id="section-order-{{ $section->id }}" type="number" name="sort_order" value="{{ $section->sort_order }}" required><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="customer_visible" value="1" @checked($section->customer_visible)> Customer visible</label><button class="button-secondary w-full">Save section</button></form>@endforeach</div><form method="POST" action="{{ route('office.commercial-library.templates.sections.store',$template) }}" class="space-y-2 border-t border-slate-200 bg-slate-50 p-4">@csrf<label class="form-label" for="new-section-type-{{ $template->id }}">Add section</label><select class="form-input" id="new-section-type-{{ $template->id }}" name="section_type">@foreach(['cover','scope','pricing','media','terms'] as $type)<option value="{{ $type }}">{{ str($type)->headline() }}</option>@endforeach</select><label class="form-label" for="new-section-heading-{{ $template->id }}">Heading</label><input class="form-input" id="new-section-heading-{{ $template->id }}" name="heading" required><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="customer_visible" value="1" checked> Customer visible</label><button class="button-secondary w-full">Add section</button></form></details>
                    </article>
                @endforeach
            </section>
        </div>
    </div>
</x-layouts.office>
