<div class="grid gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><label for="name" class="form-label">Project / Engagement name</label><input id="name" name="name" class="form-input" required value="{{ old('name', $project->name ?? '') }}" aria-invalid="{{ $errors->has('name') ? 'true' : 'false' }}">@error('name')<p class="mt-1 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="type" class="form-label">Type</label><select id="type" name="type" class="form-input" required>@foreach(['installation_project'=>'Installation / Project','ongoing_support'=>'Ongoing IT Support','consulting_engineering'=>'Consulting / Engineering','internal'=>'Internal Project'] as $value=>$label)<option value="{{ $value }}" @selected(old('type', $project->type ?? 'installation_project') === $value)>{{ $label }}</option>@endforeach</select>@error('type')<p class="mt-1 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="status" class="form-label">Status</label><select id="status" name="status" class="form-input" required>@foreach(['planning','active','on_hold','completed','canceled'] as $value)<option value="{{ $value }}" @selected(old('status', $project->status ?? 'planning') === $value)>{{ Str::headline($value) }}</option>@endforeach</select></div>
    <div><label for="customer_id" class="form-label">Customer</label><select id="customer_id" name="customer_id" class="form-input"><option value="">Internal Project — no customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id', $project->customer_id ?? $customerId ?? '') === (string)$customer->id)>{{ $customer->displayName }}</option>@endforeach</select>@error('customer_id')<p class="mt-1 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="owner_user_id" class="form-label">Owner</label><select id="owner_user_id" name="owner_user_id" class="form-input"><option value="">Current user</option>@foreach($members as $membership)<option value="{{ $membership->user_id }}" @selected((string)old('owner_user_id', $project->owner_user_id ?? '') === (string)$membership->user_id)>{{ $membership->user->name }}</option>@endforeach</select></div>
    <div><label for="service_location_id" class="form-label">Primary service location</label><select id="service_location_id" name="service_location_id" class="form-input"><option value="">Customer-wide / multi-site</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected((string)old('service_location_id', $project->service_location_id ?? '') === (string)$location->id)>{{ $location->name }}{{ $location->active ? '' : ' (inactive)' }}</option>@endforeach</select><p class="mt-1 text-sm text-slate-500">Choose a Customer and load its context before selecting a location.</p></div>
    <div><label for="primary_contact_id" class="form-label">Primary contact</label><select id="primary_contact_id" name="primary_contact_id" class="form-input"><option value="">No primary contact</option>@foreach($contacts as $contact)<option value="{{ $contact->id }}" @selected((string)old('primary_contact_id', $project->primary_contact_id ?? '') === (string)$contact->id)>{{ $contact->name }}{{ $contact->role ? ' · '.$contact->role : '' }}{{ $contact->active ? '' : ' (inactive)' }}</option>@endforeach</select></div>
    <div><label for="start_on" class="form-label">Start date</label><input id="start_on" name="start_on" type="date" class="form-input" value="{{ old('start_on', isset($project) ? optional($project->start_on)->format('Y-m-d') : '') }}"></div>
    <div><label for="target_end_on" class="form-label">Target end date</label><input id="target_end_on" name="target_end_on" type="date" class="form-input" value="{{ old('target_end_on', isset($project) ? optional($project->target_end_on)->format('Y-m-d') : '') }}"><p class="mt-1 text-sm text-slate-500">Optional for ongoing support.</p>@error('target_end_on')<p class="mt-1 text-sm font-semibold text-red-700">{{ $message }}</p>@enderror</div>
    <div class="md:col-span-2"><label for="summary" class="form-label">Summary</label><textarea id="summary" name="summary" class="{{ ($detailForm ?? false) ? 'form-textarea min-h-24' : 'form-input min-h-24' }}">{{ old('summary', $project->summary ?? '') }}</textarea></div>
    <div class="md:col-span-2"><label for="objective" class="form-label">Objective</label><textarea id="objective" name="objective" class="{{ ($detailForm ?? false) ? 'form-textarea min-h-24' : 'form-input min-h-24' }}">{{ old('objective', $project->objective ?? '') }}</textarea></div>
</div>
