<section id="field-v2-panel-closeout" role="tabpanel" aria-labelledby="field-v2-tab-closeout" tabindex="0" data-v2-panel="closeout" class="space-y-3">
    <div class="surface p-5">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-lg font-bold">Closeout</h2><p class="mt-1 text-sm text-slate-600">{{ $closeout?->status === 'submitted' ? 'Submitted record' : 'Use the guided finish flow when the Visit is ready.' }}</p></div>@if($closeout?->outcome)<span class="status-active">{{ $outcomeLabels[$closeout->outcome] }}</span>@endif</div>
        @if($closeout)
            <dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt class="font-bold">Version</dt><dd>{{ $closeout->version }} · {{ Str::headline($closeout->status) }}</dd></div><div><dt class="font-bold">Last saved</dt><dd>{{ $closeout->lastSavedBy?->name ?? 'Not saved' }}@if($closeout->updated_at) · <x-local-time :value="$closeout->updated_at" :timezone="$visit->timezone" />@endif</dd></div>@if($closeout->diagnosis)<div class="sm:col-span-2"><dt class="font-bold">Diagnosis</dt><dd class="mt-1 whitespace-pre-line">{{ $closeout->diagnosis }}</dd></div>@endif @if($closeout->work_performed)<div class="sm:col-span-2"><dt class="font-bold">Work performed</dt><dd class="mt-1 whitespace-pre-line">{{ $closeout->work_performed }}</dd></div>@endif</dl>
        @else<p class="mt-4 text-sm text-slate-500">The shared Closeout draft starts on the first saved field action.</p>@endif
        @if($closeoutMissing->isNotEmpty() && $workspaceWritable)<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p class="font-bold text-amber-950">{{ $closeoutMissing->count() }} item(s) need attention</p><ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-950" data-v2-readiness-summary>@foreach($closeoutMissing as $message)<li>{{ $message }}</li>@endforeach</ul></div>@endif
        @if(in_array($visit->status, ['on_site', 'returned_for_correction'], true) && $workspaceWritable)<button type="button" class="button-action mt-4 w-full" data-v2-finish-open>Finish Visit</button>@endif
    </div>

    @if(($versions ?? collect())->count() > 1)<div class="surface p-5"><h2 class="font-bold">Version history</h2><div class="mt-3 space-y-2">@foreach($versions as $version)<article class="rounded-lg border border-slate-200 p-3"><p class="font-semibold">Version {{ $version->version }} · {{ Str::headline($version->status) }}</p><p class="mt-1 text-xs text-slate-500">{{ $version->media->where('state', 'stored')->count() }} photos · {{ $version->parts->whereNull('removed_at')->count() }} proposals</p>@if($version->acknowledgmentSignature)<a class="mt-2 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('closeout-acknowledgment-signatures.show', $version->acknowledgmentSignature) }}">View this version's signature</a>@endif</article>@endforeach</div></div>@endif

    </section>

    @if(in_array($visit->status, ['on_site', 'returned_for_correction'], true) && $workspaceWritable)
        <dialog class="field-v2-finish-dialog" data-v2-finish-dialog aria-labelledby="v2-finish-title">
            <div class="field-v2-finish-panel">
                <header class="field-v2-finish-header"><div><p class="text-xs font-bold uppercase tracking-wide text-brand-blue">{{ $visit->displayLabel() }}</p><h2 id="v2-finish-title" class="text-xl font-bold">Finish Visit</h2></div><button type="button" class="button-secondary min-w-11" data-v2-finish-close>Close</button></header>
                <nav class="field-v2-step-nav" aria-label="Closeout steps">@foreach(['outcome' => '1 Outcome', 'summary' => '2 Work', 'check' => '3 Check', 'acknowledgment' => '4 Acknowledgment', 'review' => '5 Review'] as $step => $label)<button type="button" data-v2-step-button="{{ $step }}" aria-current="{{ $loop->first ? 'step' : 'false' }}">{{ $label }}</button>@endforeach</nav>
                <div class="field-v2-finish-body">
                    <p class="hidden rounded-lg border p-3 text-sm font-semibold" tabindex="-1" role="status" data-v2-draft-status></p>
                    <form method="POST" action="{{ route('field.visits.draft', $visit) }}" data-v2-closeout-form data-v2-submit-url="{{ route('field.visits.submit', $visit) }}" data-dirty-form>
                        @csrf<input type="hidden" name="content_version" value="{{ $closeout?->content_version ?? 1 }}">
                        <section data-v2-step="outcome"><h3 class="text-lg font-bold">Choose the Visit outcome</h3><p class="mt-1 text-sm text-slate-600">This only changes the shared draft after Save &amp; continue.</p><fieldset class="mt-4 grid gap-2 sm:grid-cols-2">@foreach($outcomeLabels as $value => $label)<label class="field-outcome-option"><input class="sr-only" type="radio" name="outcome" value="{{ $value }}" @checked($selectedOutcome === $value)><span class="font-bold">{{ $label }}</span><span class="mt-1 text-xs text-slate-600">{{ match($value) {'resolved' => 'Work is complete.', 'needs_return_trip' => 'More work must be scheduled.', 'customer_unavailable' => 'The customer could not participate.', default => 'Pause for office follow-up.'} }}</span></label>@endforeach</fieldset></section>

                        <section data-v2-step="summary"><h3 class="text-lg font-bold">Work summary</h3><p class="mt-1 text-sm text-slate-600">Only fields relevant to the selected outcome are shown.</p><div class="mt-4 space-y-4">@foreach(['diagnosis' => ['Diagnosis', 'resolved needs_return_trip on_hold'], 'work_performed' => ['Work performed', 'resolved needs_return_trip on_hold'], 'exceptions' => ['Exceptions', 'resolved'], 'return_reason' => ['Return reason', 'needs_return_trip'], 'unfinished_work' => ['Unfinished work', 'needs_return_trip on_hold'], 'needed_equipment' => ['Needed parts / equipment', 'needs_return_trip on_hold'], 'hold_reason' => ['Hold reason', 'on_hold'], 'recommendations' => ['Recommendations', 'resolved needs_return_trip on_hold']] as $field => [$label, $outcomes])<div data-v2-outcomes="{{ $outcomes }}"><div class="flex flex-wrap items-center justify-between gap-2"><label class="form-label" for="v2_{{ $field }}">{{ $label }}</label>@if($field === 'work_performed' && $completedHelper)<button type="button" class="text-sm font-bold text-brand-blue" data-v2-narrative-helper data-target="v2_{{ $field }}" data-value="{{ $completedHelper }}">Use completed Work Items</button>@elseif($field === 'recommendations' && $followUpHelper)<button type="button" class="text-sm font-bold text-brand-blue" data-v2-narrative-helper data-target="v2_{{ $field }}" data-value="{{ $followUpHelper }}">Use follow-up Work Items</button>@endif</div><textarea class="form-textarea mt-1" id="v2_{{ $field }}" name="{{ $field }}">{{ old($field, $closeout?->$field) }}</textarea></div>@endforeach<div data-v2-outcomes="customer_unavailable"><label class="form-label" for="v2_unavailable_category">Unavailable reason</label><select class="form-input mt-1" id="v2_unavailable_category" name="unavailable_category"><option value="">Choose a reason</option>@foreach(config('field_execution.unavailable_reasons') as $value => $label)<option value="{{ $value }}" @selected(old('unavailable_category', $closeout?->unavailable_category) === $value)>{{ $label }}</option>@endforeach</select><label class="form-label mt-3" for="v2_unavailable_detail">Unavailable details</label><textarea class="form-textarea mt-1" id="v2_unavailable_detail" name="unavailable_detail">{{ old('unavailable_detail', $closeout?->unavailable_detail) }}</textarea></div></div></section>

                        <section data-v2-step="check"><h3 class="text-lg font-bold">Evidence &amp; work check</h3><p class="mt-1 text-sm text-slate-600">This checklist reflects the server's current readiness result.</p><div class="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" class="button-secondary" data-v2-go-tab="work">Go to Work · {{ $handledItems->count() }} handled</button><button type="button" class="button-secondary" data-v2-go-tab="time">Go to Time · {{ $activeTimer ? 'running' : 'stopped' }}</button><button type="button" class="button-secondary" data-v2-go-tab="evidence">Add photos · {{ $activeMedia->count() }}</button><button type="button" class="button-secondary" data-v2-go-tab="evidence">Add parts · {{ $activeParts->count() }}</button></div><div class="mt-5 border-t border-slate-200 pt-5" data-v2-outcomes="resolved"><h4 class="font-bold">No-photo fallback</h4><p class="mt-1 text-sm text-slate-600">Use only when required evidence cannot be provided.</p><label class="form-label mt-3" for="v2_no_photo_category">Reason</label><select class="form-input mt-1" id="v2_no_photo_category" name="no_photo_category"><option value="">Choose a reason</option>@foreach(config('field_execution.no_photo_reasons') as $value => $label)<option value="{{ $value }}" @selected(old('no_photo_category', $closeout?->no_photo_category) === $value)>{{ $label }}</option>@endforeach</select><label class="form-label mt-3" for="v2_no_photo_detail">Details</label><textarea class="form-textarea mt-1" id="v2_no_photo_detail" name="no_photo_detail">{{ old('no_photo_detail', $closeout?->no_photo_detail) }}</textarea></div></section>

                        <section data-v2-step="acknowledgment"><h3 class="text-lg font-bold">Customer acknowledgment</h3><p class="mt-1 text-sm text-slate-600">Enter the on-site POC who will sign during Review, or record the existing PR D fallback.</p><div class="mt-4 space-y-4"><div><label class="form-label" for="v2_representative_name">POC or customer name</label><input class="form-input mt-1" id="v2_representative_name" name="representative_name" value="{{ old('representative_name', $closeout?->representative_name) }}"></div><div><label class="form-label" for="v2_representative_role">POC role or title</label><input class="form-input mt-1" id="v2_representative_role" name="representative_role" maxlength="120" value="{{ old('representative_role', $closeout?->representative_role) }}"></div><div class="border-t border-slate-200 pt-4"><p class="font-bold">Acknowledgment fallback</p><label class="form-label mt-3" for="v2_ack_category">Reason</label><select class="form-input mt-1" id="v2_ack_category" name="ack_unavailable_category"><option value="">Use on-site signature</option>@foreach(config('field_execution.ack_fallbacks') as $value => $label)<option value="{{ $value }}" @selected(old('ack_unavailable_category', $closeout?->ack_unavailable_category) === $value)>{{ $label }}</option>@endforeach</select><label class="form-label mt-3" for="v2_ack_detail">Fallback details</label><textarea class="form-textarea mt-1" id="v2_ack_detail" name="ack_unavailable_detail">{{ old('ack_unavailable_detail', $closeout?->ack_unavailable_detail) }}</textarea></div></div></section>

                        <footer class="mt-6 flex flex-wrap justify-between gap-3 border-t border-slate-200 pt-4" data-v2-draft-footer><button type="button" class="button-secondary" data-v2-step-previous>Previous</button><button class="button-primary" data-v2-save-continue>Save &amp; continue</button></footer>
                    </form>

                    <section data-v2-step="review"><h3 class="text-lg font-bold">Review &amp; Submit</h3><p class="mt-1 text-sm text-slate-600">Saving earlier steps updates this authoritative checklist.</p><ul class="mt-4 space-y-2" data-v2-readiness-list>@forelse($closeoutMissing as $field => $message)<li class="flex items-center justify-between gap-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm"><span>{{ $message }}</span><button type="button" class="font-bold text-brand-blue" data-v2-fix="{{ $field }}">Fix</button></li>@empty<li class="rounded-lg border border-emerald-300 bg-emerald-50 p-3 text-sm font-semibold text-emerald-950">Server readiness checks are complete.</li>@endforelse</ul>
                        @if($canSubmitCloseout)
                            <form method="POST" action="{{ route('field.visits.submit', $visit) }}" class="mt-5" data-v2-submit-form>@csrf<input type="hidden" name="submission_token" value="{{ Str::uuid() }}"><div data-signature-pad data-v2-signature-path><div class="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm"><p class="font-bold">On-site POC acknowledgment</p><p class="mt-2">{{ config('field_execution.ack_statement') }}</p></div><label class="form-label mt-4" for="v2_signature_canvas">POC signature</label><canvas id="v2_signature_canvas" class="mt-1 h-40 w-full touch-none rounded-lg border-2 border-slate-400 bg-white" width="600" height="240" tabindex="0" role="img" aria-label="Signature drawing area" data-signature-canvas></canvas><input type="hidden" name="signature_data" data-signature-data><div class="mt-2 flex items-center justify-between gap-3"><p class="text-sm text-slate-600" role="status" aria-live="polite" data-signature-status>Signature not yet captured.</p><button type="button" class="button-secondary" data-signature-clear>Clear</button></div><label class="mt-4 flex min-h-11 gap-3 rounded-lg border border-slate-300 p-4"><input type="checkbox" name="acknowledgment_confirmed" value="1" required><span class="text-sm font-semibold">I confirm the work and outcome were presented to this POC.</span></label></div><div class="hidden rounded-lg border border-emerald-300 bg-emerald-50 p-4 text-sm text-emerald-950" data-v2-fallback-path><p class="font-bold">Acknowledgment fallback selected</p><p class="mt-1">No signature is required after the fallback draft is saved.</p></div><button class="button-action mt-5 w-full" data-v2-final-submit>Submit closeout</button></form>
                        @else<p class="mt-5 rounded-lg border border-slate-300 bg-slate-50 p-4 text-sm font-semibold">Only the assigned lead or an authorized supervisor can submit.</p>@endif
                    </section>
                </div>
            </div>
        </dialog>
    @endif
