<x-layouts.field :title="$visit->serviceTicket->ticket_number">
    @if(session('status'))<div class="mb-4 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <a href="{{ route('field.home') }}" class="inline-flex min-h-11 items-center text-sm font-bold text-brand-blue">← Today</a>
    <p class="mt-2 text-sm font-bold text-brand-blue">{{ $visit->serviceTicket->ticket_number }}</p><h1 class="mt-1 text-2xl font-bold">{{ $visit->serviceTicket->title }}</h1><p class="mt-2 text-sm font-semibold text-slate-600">{{ ucfirst(str_replace('_',' ',$visit->status)) }} · {{ $visit->scheduledStartLocal()?->format('M j, g:i A T') ?? 'Unscheduled' }}</p>
    @can('execute', $visit)
        @if($visit->status==='assigned')<form method="POST" action="{{ route('field.visits.transition', $visit) }}" class="mt-5" onsubmit="return confirm('Start travel for this visit?')">@csrf<input type="hidden" name="status" value="en_route"><button class="button-action w-full">Start En Route</button></form>@endif
        @if($visit->status==='en_route')<form method="POST" action="{{ route('field.visits.transition', $visit) }}" class="mt-5" onsubmit="return confirm('Mark this visit on site?')">@csrf<input type="hidden" name="status" value="on_site"><button class="button-action w-full">Mark On Site</button></form>@endif
    @endcan
    <section class="surface mt-5 p-5"><h2 class="font-bold">Customer & location</h2><p class="mt-3 font-bold">{{ $visit->serviceTicket->customer->display_name }}</p><p class="mt-1 text-slate-700">{{ $visit->serviceLocation->name }}<br>{{ $visit->serviceLocation->formattedAddress() }}</p><p class="mt-2 text-sm font-semibold text-slate-500">{{ $visit->timezone }}</p>@if($visit->serviceLocation->access_instructions)<h3 class="mt-4 text-sm font-bold uppercase tracking-[.1em] text-brand-orange">Access instructions</h3><p class="mt-2 whitespace-pre-line text-slate-700">{{ $visit->serviceLocation->access_instructions }}</p>@endif</section>
    @php($contact = $visit->serviceTicket->contact ?? $visit->serviceLocation->primaryContact)
    @if($contact)<section class="surface mt-4 p-5"><h2 class="font-bold">Contact</h2><p class="mt-2">{{ $contact->name }}</p><div class="mt-3 flex flex-wrap gap-2">@if($contact->phone)<a class="button-secondary" href="tel:{{ $contact->phone }}">Call {{ $contact->phone }}</a>@endif @if($contact->email)<a class="button-secondary" href="mailto:{{ $contact->email }}">Email</a>@endif</div></section>@endif
    <section class="surface mt-4 p-5"><h2 class="font-bold">Work scope</h2><p class="mt-3 whitespace-pre-line text-slate-700">{{ $visit->serviceTicket->description ?: 'No work scope recorded.' }}</p>@if($visit->serviceTicket->customer_visible_summary)<h3 class="mt-4 text-sm font-bold uppercase tracking-[.1em] text-slate-500">Customer summary</h3><p class="mt-2 whitespace-pre-line">{{ $visit->serviceTicket->customer_visible_summary }}</p>@endif</section>
    <section class="surface mt-4 p-5"><h2 class="font-bold">Crew</h2><ul class="mt-3 space-y-2">@foreach($visit->assignments as $assignment)<li class="text-sm">{{ $assignment->membership->user->name }} @if($assignment->is_lead)<strong class="text-brand-orange">· Lead</strong>@endif</li>@endforeach</ul></section>
    <section class="surface mt-4 p-5"><h2 class="font-bold">Ticket visit history</h2><ul class="mt-3 space-y-2">@foreach($visit->serviceTicket->visits as $history)<li class="text-sm text-slate-700">Visit #{{ $history->id }} · {{ ucfirst(str_replace('_',' ',$history->status)) }} @if($history->scheduled_start_at)· {{ $history->scheduledStartLocal()->format('M j, Y') }}@endif</li>@endforeach</ul></section>
</x-layouts.field>
