<section class="surface overflow-hidden" id="proposal-content">
    <header class="border-b border-slate-200 p-5"><h2 class="text-lg font-bold">Proposal content</h2><p class="mt-1 text-sm text-slate-600">Scope, terms, and media become immutable when published.</p></header>
    @if($revision->isEditable() && $activeMembership->hasCapability('quotes.manage'))
        <div class="space-y-5 p-5">
            <form method="POST" action="{{ route('office.quotes.content-blocks.store',[$quote,$revision]) }}" data-offline-write>@csrf<input type="hidden" name="content_version" value="{{ $revision->content_version }}"><label class="form-label" for="content-block">Reusable scope block</label><div class="mt-2 flex flex-col gap-2 sm:flex-row"><select class="form-input" id="content-block" name="content_block_id" required><option value="">Choose a block</option>@foreach($contentBlocks as $block)<option value="{{ $block->id }}">{{ $block->name }}</option>@endforeach</select><button class="button-secondary shrink-0">Copy into Quote</button></div></form>
            <form method="POST" action="{{ route('office.quotes.terms.update',[$quote,$revision]) }}" data-offline-write>@csrf @method('PUT')<input type="hidden" name="content_version" value="{{ $revision->content_version }}"><label class="form-label" for="terms-set">Approved terms</label><select class="form-input" id="terms-set" name="terms_set_id"><option value="">Custom terms</option>@foreach($termsSets as $terms)<option value="{{ $terms->id }}" @selected($revision->commercial_terms_set_id===$terms->id)>{{ $terms->name }} · v{{ $terms->version }}</option>@endforeach</select><label class="form-label mt-3" for="terms-body">Terms override</label><textarea class="form-textarea min-h-36" id="terms-body" name="terms_body" placeholder="Leave blank to use the selected approved version.">{{ old('terms_body',$revision->terms_overridden?$revision->terms_body_snapshot:'') }}</textarea><p class="mt-1 text-xs text-slate-500">Editing approved terms creates a reviewed override and triggers approval.</p><button class="button-secondary mt-3 w-full">Save terms snapshot</button></form>
            <form method="POST" action="{{ route('office.quotes.media.upload',[$quote,$revision]) }}" enctype="multipart/form-data" data-offline-write>@csrf<label class="form-label" for="proposal-media">Private image or document</label><input class="form-input" id="proposal-media" type="file" name="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf,.docx,.xlsx,.txt,.csv" required><label class="form-label mt-2" for="proposal-caption">Caption</label><input class="form-input" id="proposal-caption" name="caption"><button class="button-secondary mt-3 w-full">Upload private media</button></form>
            <form method="POST" action="{{ route('office.quotes.media.embed',[$quote,$revision]) }}" data-offline-write>@csrf<label class="form-label" for="proposal-video">HTTPS video URL</label><input class="form-input" id="proposal-video" type="url" name="embed_url" placeholder="https://…" required><label class="form-label mt-2" for="proposal-video-caption">Caption</label><input class="form-input" id="proposal-video-caption" name="caption"><button class="button-secondary mt-3 w-full">Add video reference</button></form>
        </div>
    @endif
    <div class="divide-y divide-slate-200 border-t border-slate-200">
        @forelse($revision->media as $media)
            <div class="p-4">
                <p class="font-semibold">{{ $media->caption ?: $media->original_name ?: 'Embedded video' }}</p>
                <p class="text-xs text-slate-500">{{ ucfirst($media->media_type) }} @if($media->byte_size) · {{ number_format($media->byte_size/1024) }} KB @endif</p>
                <div class="mt-2 flex flex-wrap gap-2">
                    @if($media->storage_key)<a class="button-secondary" href="{{ route('office.quotes.media.show',[$quote,$revision,$media]) }}">Preview</a>@else<a class="button-secondary" href="{{ $media->embed_url }}" target="_blank" rel="noopener noreferrer">Open video</a>@endif
                    @if($revision->isEditable() && $activeMembership->hasCapability('quotes.manage'))<form method="POST" action="{{ route('office.quotes.media.destroy',[$quote,$revision,$media]) }}">@csrf @method('DELETE')<button class="button-danger">Remove</button></form>@endif
                </div>
            </div>
        @empty
            <p class="p-5 text-sm text-slate-600">No Proposal media.</p>
        @endforelse
    </div>
</section>

<section class="surface p-5" id="approval-publication">
    <h2 class="text-lg font-bold">Approval and publication</h2>
    @if($revision->approvals->isNotEmpty())<div class="mt-4 space-y-3">@foreach($revision->approvals as $approval)<div class="rounded-lg border border-slate-200 p-3"><div class="flex flex-wrap justify-between gap-2"><strong>{{ str($approval->status)->headline() }}</strong><span class="text-xs text-slate-500">{{ $approval->requested_at?->setTimezone($activeOrganization->timezone)->format('M j, Y g:i A T') }}</span></div><p class="mt-1 text-sm text-slate-600">{{ collect($approval->trigger_snapshot)->pluck('kind')->map(fn($kind)=>str($kind)->headline())->join(', ') ?: 'Policy pass — no exception approval required.' }}</p>@if($approval->status==='pending' && $activeMembership->hasCapability('quotes.approve'))<form method="POST" action="{{ route('office.quote-approvals.decide',$approval) }}" class="mt-3 space-y-2">@csrf<label class="form-label" for="approval-reason-{{ $approval->id }}">Decision reason</label><textarea class="form-textarea" id="approval-reason-{{ $approval->id }}" name="reason" required></textarea><div class="flex gap-2"><button class="button-primary" name="decision" value="approved">Approve</button><button class="button-danger" name="decision" value="rejected">Reject</button></div></form>@endif</div>@endforeach</div>@endif
    @if($revision->isEditable() && $activeMembership->hasCapability('quotes.manage'))<form method="POST" action="{{ route('office.quotes.approval.submit',[$quote,$revision]) }}" class="mt-4" data-offline-write>@csrf<button class="button-primary w-full">Evaluate and submit for approval</button></form>@endif
    @if($revision->status==='approved' && !$revision->publication && $activeMembership->hasCapability('quotes.publish'))
        <form method="POST" action="{{ route('office.quotes.publications.store',[$quote,$revision]) }}" class="mt-5 space-y-3 border-t border-slate-200 pt-5" data-offline-write>@csrf<label class="form-label" for="proposal-template">Proposal template</label><select class="form-input" id="proposal-template" name="proposal_template_id" required>@foreach($proposalTemplates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select><label class="form-label" for="proposal-expiry">Expires on</label><input class="form-input" id="proposal-expiry" type="date" name="expires_on" value="{{ now($activeOrganization->timezone)->addDays($commercialSettings->default_proposal_expiration_days)->toDateString() }}" required><label class="form-label" for="labor-grouping">Labor subtotal grouping</label><select class="form-input" id="labor-grouping" name="labor_grouping"><option value="location">Location</option><option value="system">System</option></select><div class="grid gap-2"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="acceptance_enabled" value="1" checked> Acceptance enabled in Phase 5</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="show_line_details" value="1" @checked($commercialSettings->customer_show_line_details)> Show individual line prices</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="show_location_totals" value="1" checked> Show Location totals</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="show_manufacturer_model" value="1"> Show manufacturer/model</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="show_product_images" value="1"> Show Product images</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="show_package_components" value="1"> Show Package components</label></div><button class="button-primary w-full">Freeze and publish</button></form>
    @elseif($revision->publication)<a class="button-primary mt-4 w-full" href="{{ route('office.proposal-publications.show',$revision->publication) }}">Open immutable publication</a>@endif
</section>
