@php($editing=isset($product))
<div class="grid gap-5 sm:grid-cols-2">
    <div><label class="form-label" for="product_code">Product code</label><input class="form-input" id="product_code" name="product_code" value="{{ old('product_code',$product->product_code ?? '') }}" @if($editing) required @else data-product-code-autofill @endif><p class="mt-1 text-xs text-slate-500">{{ $editing ? 'Canonical internal identifier.' : 'Defaults from SKU, or manufacturer and model. You can override it.' }}</p></div>
    <div><label class="form-label" for="sku">SKU</label><input class="form-input" id="sku" name="sku" value="{{ old('sku',$product->sku ?? '') }}"></div>
    <div class="sm:col-span-2"><label class="form-label" for="name">Product name</label><input class="form-input" id="name" name="name" value="{{ old('name',$product->name ?? '') }}" required></div>
    <div><label class="form-label" for="manufacturer">Manufacturer</label><input class="form-input" id="manufacturer" name="manufacturer" value="{{ old('manufacturer',$product->manufacturer ?? '') }}"></div>
    <div><label class="form-label" for="model">Model</label><input class="form-input" id="model" name="model" value="{{ old('model',$product->model ?? '') }}"></div>
    <div class="sm:col-span-2"><label class="form-label" for="category_id">Category</label><select class="form-input" id="category_id" name="category_id"><option value="">Uncategorized</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id',$product->category_id ?? '')===(string)$category->id)>{{ $category->name }}{{ $category->active ? '' : ' — inactive' }}</option>@endforeach</select></div>
</div>
<div class="mt-5"><label class="form-label" for="customer_description">Customer description</label><textarea class="form-textarea" id="customer_description" name="customer_description" rows="3">{{ old('customer_description',$product->customer_description ?? '') }}</textarea><p class="mt-1 text-xs text-slate-500">Safe for future customer-facing documents.</p></div>
<div class="mt-5"><label class="form-label" for="internal_description">Internal description</label><textarea class="form-textarea" id="internal_description" name="internal_description" rows="3">{{ old('internal_description',$product->internal_description ?? '') }}</textarea></div>
<fieldset class="mt-7 border-t border-slate-200 pt-6"><legend class="text-lg font-bold text-slate-950">Units and future tracking</legend><div class="mt-4 grid gap-5 sm:grid-cols-2">
    <div><label class="form-label" for="base_uom_id">Base consumption unit</label><select class="form-input" id="base_uom_id" name="base_uom_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)old('base_uom_id',$product->base_uom_id ?? '')===(string)$unit->id)>{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}{{ $unit->active ? '' : ' — inactive' }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Smallest practical unit consumed, such as foot or each.</p></div>
    <div><label class="form-label" for="default_sales_uom_id">Default sales unit</label><select class="form-input" id="default_sales_uom_id" name="default_sales_uom_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string)old('default_sales_uom_id',$product->default_sales_uom_id ?? '')===(string)$unit->id)>{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}{{ $unit->active ? '' : ' — inactive' }}</option>@endforeach</select></div>
    <div><label class="form-label" for="sales_quantity">Base units per sales unit</label><input class="form-input" id="sales_quantity" name="sales_quantity" inputmode="decimal" value="{{ old('sales_quantity',isset($product) ? rtrim(rtrim(number_format($product->sales_quantity_millis/1000,3,'.',''),'0'),'.') : '1') }}" required><p class="mt-1 text-xs text-slate-500">For selling wire by foot, use 1. Purchase boxes are configured on the Product page.</p></div>
    <div><label class="form-label" for="tracking_type">Future inventory classification</label><select class="form-input" id="tracking_type" name="tracking_type" required>@foreach(App\Models\CatalogProduct::TRACKING_TYPES as $type)<option value="{{ $type }}" @selected(old('tracking_type',$product->tracking_type ?? 'standard')===$type)>{{ Str::headline($type) }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Classification only; no inventory quantity is tracked.</p></div>
</div></fieldset>
@if($canManagePricing)
<fieldset class="mt-7 border-t border-slate-200 pt-6"><legend class="text-lg font-bold text-slate-950">Cost, price, and tax</legend><div class="mt-4 grid gap-5 sm:grid-cols-2">
    <div><label class="form-label" for="default_cost">Default cost</label><input class="form-input" id="default_cost" name="default_cost" inputmode="decimal" value="{{ old('default_cost',isset($product) && $product->default_cost_cents !== null ? number_format($product->default_cost_cents/100,2,'.','') : '') }}"></div>
    <div><label class="form-label" for="default_cost_quantity">Cost covers base-unit quantity</label><input class="form-input" id="default_cost_quantity" name="default_cost_quantity" inputmode="decimal" value="{{ old('default_cost_quantity',isset($product) ? rtrim(rtrim(number_format($product->default_cost_quantity_millis/1000,3,'.',''),'0'),'.') : '1') }}" required><p class="mt-1 text-xs text-slate-500">Avoids fractional-cent unit cost; purchase packs may carry their own pack cost.</p></div>
    <div><label class="form-label" for="default_sell_price">Default sell price</label><input class="form-input" id="default_sell_price" name="default_sell_price" inputmode="decimal" value="{{ old('default_sell_price',isset($product) && $product->default_sell_price_cents !== null ? number_format($product->default_sell_price_cents/100,2,'.','') : '') }}"><p class="mt-1 text-xs text-slate-500">Price for one default sales unit.</p></div>
</div><label class="mt-4 flex min-h-11 items-center gap-3"><input type="checkbox" name="taxable" value="1" @checked(old('taxable',$product->taxable ?? true))><span><strong>Taxable by default</strong><span class="block text-xs text-slate-500">Future invoice selection will snapshot this setting.</span></span></label></fieldset>
@else
<div class="mt-7 rounded-lg border border-slate-300 bg-slate-50 p-4 text-sm text-slate-700"><strong>Pricing is protected.</strong> Only a pricing manager can change cost, sell price, or tax defaults.</div>
@endif
<label class="mt-6 flex min-h-11 items-center gap-3"><input type="checkbox" name="active" value="1" @checked(old('active',$product->active ?? true))><span>Active and available for future selection</span></label>
