<x-layouts.office title="Catalog products" width="workspace">
    @if(session('status'))<x-office.alert type="success">{{ session('status') }}</x-office.alert>@endif
    @php($productFilters = collect(['q','category','status'])->filter(fn ($key) => filled(request($key))))
    <form method="GET" aria-label="Product filters">
    <x-office.primary-toolbar title="Products & Services" description="Maintain physical products, units, and purchasing conversions." eyebrow="Catalog">
        <x-slot:search><label class="sr-only" for="q">Search products</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" type="search" placeholder="Search name, code, SKU, or model"></x-slot:search>
        <x-slot:filters><x-office.filter-panel :active-count="$productFilters->count()"><div class="grid gap-3 sm:grid-cols-2"><div><label class="form-label" for="category">Category</label><select class="form-input" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div></div><div class="mt-4 flex justify-end gap-2"><a class="button-secondary" href="{{ route('office.catalog.products.index') }}">Clear all</a><button class="button-primary">Apply filters</button></div></x-office.filter-panel></x-slot:filters>
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:primaryAction><a class="button-primary" href="{{ route('office.catalog.products.create') }}">Add product</a></x-slot:primaryAction>
        @endif
        @if($productFilters->isNotEmpty())
            <x-slot:chips>@foreach($productFilters as $key)<x-office.filter-chip :label="Str::headline($key).': '.Str::headline(request($key))" :remove-url="route('office.catalog.products.index', request()->except([$key, 'page']))" />@endforeach<a class="inline-flex min-h-9 items-center px-2 text-xs font-bold text-brand-blue underline" href="{{ route('office.catalog.products.index') }}">Clear all</a></x-slot:chips>
        @endif
    </x-office.primary-toolbar>
    </form>
    <x-office.catalog-tabs />
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Catalog products</caption><thead><tr><th scope="col">Product</th><th scope="col">Manufacturer / model</th><th scope="col">Category</th><th scope="col">Base unit</th><th scope="col">Cost</th><th scope="col">Sell price</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>
        @forelse($products as $product)<tr><td><a class="font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">{{ $product->product_code }}</a><p class="mt-0.5 font-semibold text-slate-950">{{ $product->name }}</p>@if($product->sku)<p class="text-xs text-slate-500">SKU {{ $product->sku }}</p>@endif</td><td>{{ collect([$product->manufacturer,$product->model])->filter()->join(' / ') ?: 'Not set' }}</td><td>{{ $product->category?->name ?? 'Uncategorized' }}</td><td>{{ $product->baseUom->name }}@if($product->purchase_units_count)<p class="text-xs text-slate-500">{{ $product->purchase_units_count }} purchase {{ Str::plural('option',$product->purchase_units_count) }}</p>@endif</td><td>{{ $product->default_cost_cents === null ? 'Not set' : '$'.number_format($product->default_cost_cents/100,2) }}</td><td>{{ $product->default_sell_price_cents === null ? 'Not set' : '$'.number_format($product->default_sell_price_cents/100,2) }}</td><td><span class="{{ $product->active ? 'status-success' : 'status-muted' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">Open</a></td></tr>
        @empty<tr><td colspan="8" class="p-3"><x-office.state-panel title="No products found" message="Create a product or adjust the filters." /></td></tr>@endforelse
    </tbody></table></div>
    <div class="office-mobile-list">@forelse($products as $product)<article class="office-mobile-card"><div class="flex items-start justify-between gap-3"><div><a class="font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">{{ $product->product_code }}</a><h2 class="mt-1 font-bold text-slate-950">{{ $product->name }}</h2></div><span class="{{ $product->active ? 'status-success' : 'status-muted' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="font-semibold text-slate-500">Base unit</dt><dd>{{ $product->baseUom->name }}</dd></div><div><dt class="font-semibold text-slate-500">Sell price</dt><dd>{{ $product->default_sell_price_cents === null ? 'Not set' : '$'.number_format($product->default_sell_price_cents/100,2) }}</dd></div></dl><a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.products.show',$product) }}">Open product</a></article>@empty<x-office.state-panel title="No products found" message="Create a product or adjust the filters." />@endforelse</div>
    <div class="mt-5">{{ $products->links() }}</div>
</x-layouts.office>
