<x-layouts.office title="Catalog products" width="workspace">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-office.page-header title="Products & Services" description="Maintain physical products, base consumption units, and purchasing conversions without tracking inventory balances." eyebrow="Catalog">
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:actions><a class="button-primary" href="{{ route('office.catalog.products.create') }}">Add product</a></x-slot:actions>
        @endif
    </x-office.page-header>
    <x-office.catalog-tabs />
    <form method="GET" class="office-filter-toolbar xl:grid-cols-[minmax(260px,1fr)_240px_170px_auto]" aria-label="Product filters">
        <div><label class="form-label" for="q">Name, code, SKU, or model</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" type="search"></div>
        <div><label class="form-label" for="category">Category</label><select class="form-input" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
        <div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div>
        <div class="flex flex-wrap gap-2"><button class="button-secondary">Filter</button>@if(request()->query())<a class="inline-flex min-h-11 items-center px-2 text-sm font-bold text-brand-blue underline" href="{{ route('office.catalog.products.index') }}">Clear</a>@endif</div>
    </form>
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Catalog products</caption><thead><tr><th scope="col">Product</th><th scope="col">Manufacturer / model</th><th scope="col">Category</th><th scope="col">Base unit</th><th scope="col">Cost</th><th scope="col">Sell price</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>
        @forelse($products as $product)<tr><td><a class="font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">{{ $product->product_code }}</a><p class="mt-0.5 font-semibold text-slate-950">{{ $product->name }}</p>@if($product->sku)<p class="text-xs text-slate-500">SKU {{ $product->sku }}</p>@endif</td><td>{{ collect([$product->manufacturer,$product->model])->filter()->join(' / ') ?: 'Not set' }}</td><td>{{ $product->category?->name ?? 'Uncategorized' }}</td><td>{{ $product->baseUom->name }}@if($product->purchase_units_count)<p class="text-xs text-slate-500">{{ $product->purchase_units_count }} purchase {{ Str::plural('option',$product->purchase_units_count) }}</p>@endif</td><td>{{ $product->default_cost_cents === null ? 'Not set' : '$'.number_format($product->default_cost_cents/100,2) }}</td><td>{{ $product->default_sell_price_cents === null ? 'Not set' : '$'.number_format($product->default_sell_price_cents/100,2) }}</td><td><span class="{{ $product->active ? 'status-success' : 'status-muted' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">Open</a></td></tr>
        @empty<tr><td colspan="8" class="py-10 text-center"><p class="font-bold text-slate-900">No products found</p><p class="mt-1 text-sm text-slate-500">Create a product or adjust the filters.</p></td></tr>@endforelse
    </tbody></table></div>
    <div class="office-mobile-list">@forelse($products as $product)<article class="office-mobile-card"><div class="flex items-start justify-between gap-3"><div><a class="font-bold text-brand-blue" href="{{ route('office.catalog.products.show',$product) }}">{{ $product->product_code }}</a><h2 class="mt-1 font-bold text-slate-950">{{ $product->name }}</h2></div><span class="{{ $product->active ? 'status-success' : 'status-muted' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="font-semibold text-slate-500">Base unit</dt><dd>{{ $product->baseUom->name }}</dd></div><div><dt class="font-semibold text-slate-500">Sell price</dt><dd>{{ $product->default_sell_price_cents === null ? 'Not set' : '$'.number_format($product->default_sell_price_cents/100,2) }}</dd></div></dl><a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.products.show',$product) }}">Open product</a></article>@empty<div class="surface p-8 text-center"><p class="font-bold">No products found</p></div>@endforelse</div>
    <div class="mt-5">{{ $products->links() }}</div>
</x-layouts.office>
