@php($formatQuantity = fn (int $millis) => rtrim(rtrim(number_format($millis / 1000, 3, '.', ''), '0'), '.'))
<x-layouts.office :title="$product->name" width="detail">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-form-errors />
    <x-office.record-header :title="$product->name" :back-href="route('office.catalog.products.index')" back-label="Products" :description="$product->customer_description ?: 'No customer description.'">
        <x-slot:badges><span class="{{ $product->active ? 'status-success' : 'status-muted' }}">{{ $product->active ? 'Active' : 'Inactive' }}</span><span class="status-active">{{ Str::headline($product->tracking_type) }}</span></x-slot:badges>
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:actions><a class="button-primary" href="{{ route('office.catalog.products.edit',$product) }}">Edit product</a></x-slot:actions>
        @endif
    </x-office.record-header>
    <x-office.catalog-tabs />
    <x-office.detail-nav :items="['overview'=>'Overview','purchasing'=>'Purchase units']" />
    <div class="office-detail-grid">
        <div class="office-detail-main">
            <section id="overview" class="surface scroll-mt-6 p-5"><h2 class="text-xl font-bold">Product definition</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm font-semibold text-slate-500">Product code</dt><dd class="mt-1 font-bold">{{ $product->product_code }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">SKU</dt><dd class="mt-1">{{ $product->sku ?: 'Not set' }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Manufacturer</dt><dd class="mt-1">{{ $product->manufacturer ?: 'Not set' }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Model</dt><dd class="mt-1">{{ $product->model ?: 'Not set' }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Category</dt><dd class="mt-1">{{ $product->category?->name ?? 'Uncategorized' }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Future tracking</dt><dd class="mt-1">{{ Str::headline($product->tracking_type) }} <span class="block text-xs text-slate-500">Classification only; no balance exists.</span></dd></div></dl>@if($product->internal_description)<div class="mt-5 border-t border-slate-200 pt-4"><h3 class="font-bold">Internal description</h3><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $product->internal_description }}</p></div>@endif</section>
            <section id="purchasing" class="surface scroll-mt-6 p-5"><div><h2 class="text-xl font-bold">Purchase units</h2><p class="mt-1 text-sm text-slate-600">Product-specific conversions show how purchased packs translate into the base unit. They do not create stock.</p></div>
                <div class="mt-5 space-y-4">@forelse($product->purchaseUnits as $purchaseUnit)<article class="rounded-lg border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold">{{ $purchaseUnit->label }}</h3><p class="text-sm text-slate-600">1 {{ $purchaseUnit->purchaseUom->name }} = {{ $formatQuantity($purchaseUnit->base_quantity_millis) }} {{ Str::plural($product->baseUom->name, (int)ceil($purchaseUnit->base_quantity_millis / 1000)) }}</p>@if($purchaseUnit->vendor_sku)<p class="mt-1 text-xs text-slate-500">Vendor SKU {{ $purchaseUnit->vendor_sku }}</p>@endif</div><div class="flex flex-wrap gap-2">@if($purchaseUnit->is_default)<span class="status-active">Default</span>@endif<span class="{{ $purchaseUnit->active ? 'status-success' : 'status-muted' }}">{{ $purchaseUnit->active ? 'Active' : 'Inactive' }}</span></div></div>@if($purchaseUnit->default_purchase_cost_cents !== null)<p class="mt-2 text-sm font-semibold">Pack cost ${{ number_format($purchaseUnit->default_purchase_cost_cents/100,2) }}</p>@endif
                    @if($activeMembership->hasCapability('catalog.manage'))<details class="mt-3"><summary class="min-h-11 cursor-pointer py-3 font-bold text-brand-blue">Edit purchase unit</summary><form method="POST" action="{{ route('office.catalog.products.purchase-units.update',[$product,$purchaseUnit]) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<div><label class="form-label" for="purchase_uom_{{ $purchaseUnit->id }}">Purchase unit</label><select class="form-input" id="purchase_uom_{{ $purchaseUnit->id }}" name="purchase_uom_id">@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($purchaseUnit->purchase_uom_id===$unit->id)>{{ $unit->name }}</option>@endforeach</select></div><div><label class="form-label" for="label_{{ $purchaseUnit->id }}">Label</label><input class="form-input" id="label_{{ $purchaseUnit->id }}" name="label" value="{{ $purchaseUnit->label }}" required></div><div><label class="form-label" for="base_quantity_{{ $purchaseUnit->id }}">Base-unit quantity</label><input class="form-input" id="base_quantity_{{ $purchaseUnit->id }}" name="base_quantity" inputmode="decimal" value="{{ $formatQuantity($purchaseUnit->base_quantity_millis) }}" required></div><div><label class="form-label" for="vendor_sku_{{ $purchaseUnit->id }}">Vendor SKU</label><input class="form-input" id="vendor_sku_{{ $purchaseUnit->id }}" name="vendor_sku" value="{{ $purchaseUnit->vendor_sku }}"></div>@if($canManagePricing)<div><label class="form-label" for="purchase_cost_{{ $purchaseUnit->id }}">Default pack cost</label><input class="form-input" id="purchase_cost_{{ $purchaseUnit->id }}" name="default_purchase_cost" inputmode="decimal" value="{{ $purchaseUnit->default_purchase_cost_cents === null ? '' : number_format($purchaseUnit->default_purchase_cost_cents/100,2,'.','') }}"></div>@endif<div class="grid gap-2"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="is_default" value="1" @checked($purchaseUnit->is_default)> Default purchase unit</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" @checked($purchaseUnit->active)> Active</label></div><button class="button-secondary sm:col-span-2">Save purchase unit</button></form></details>@endif
                </article>@empty<p class="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">No purchase-unit conversions configured. Products bought and used in the same unit do not need one.</p>@endforelse</div>
                @if($activeMembership->hasCapability('catalog.manage'))<form method="POST" action="{{ route('office.catalog.products.purchase-units.store',$product) }}" class="mt-6 border-t border-slate-200 pt-5">@csrf<h3 class="font-bold">Add purchase unit</h3><p class="mt-1 text-sm text-slate-600">Example: a 250 ft box uses purchase unit Box and base-unit quantity 250.</p><div class="mt-3 grid gap-3 sm:grid-cols-2"><div><label class="form-label" for="purchase_uom_id">Purchase unit</label><select class="form-input" id="purchase_uom_id" name="purchase_uom_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select></div><div><label class="form-label" for="label">Label</label><input class="form-input" id="label" name="label" value="{{ old('label') }}" placeholder="250 ft box" required></div><div><label class="form-label" for="base_quantity">Base-unit quantity</label><input class="form-input" id="base_quantity" name="base_quantity" inputmode="decimal" value="{{ old('base_quantity') }}" placeholder="250" required></div><div><label class="form-label" for="vendor_sku">Vendor SKU</label><input class="form-input" id="vendor_sku" name="vendor_sku" value="{{ old('vendor_sku') }}"></div>@if($canManagePricing)<div><label class="form-label" for="default_purchase_cost">Default pack cost</label><input class="form-input" id="default_purchase_cost" name="default_purchase_cost" inputmode="decimal" value="{{ old('default_purchase_cost') }}"></div>@endif<div class="grid gap-2"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="is_default" value="1" @checked(old('is_default'))> Default purchase unit</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" checked> Active</label></div><button class="button-primary sm:col-span-2">Add purchase unit</button></div></form>@endif
            </section>
        </div>
        <aside class="office-detail-rail"><section class="surface p-5"><h2 class="font-bold">Units and pricing</h2><dl class="mt-4 space-y-4 text-sm"><div><dt class="font-semibold text-slate-500">Base unit</dt><dd class="mt-1 font-bold">{{ $product->baseUom->name }}</dd></div><div><dt class="font-semibold text-slate-500">Sales unit</dt><dd class="mt-1">{{ $formatQuantity($product->sales_quantity_millis) }} {{ Str::plural($product->baseUom->name, (int)ceil($product->sales_quantity_millis/1000)) }} per {{ $product->defaultSalesUom->name }}</dd></div><div class="border-t border-slate-200 pt-4"><dt class="font-semibold text-slate-500">Default cost</dt><dd class="mt-1">{{ $product->default_cost_cents === null ? 'Not set' : '$'.number_format($product->default_cost_cents/100,2).' per '.$formatQuantity($product->default_cost_quantity_millis).' '.strtolower($product->baseUom->name) }}</dd></div><div><dt class="font-semibold text-slate-500">Default sell price</dt><dd class="mt-1 text-xl font-bold">{{ $product->default_sell_price_cents === null ? 'Not set' : '$'.number_format($product->default_sell_price_cents/100,2) }}</dd><dd class="mt-1 text-xs text-slate-500">Per {{ strtolower($product->defaultSalesUom->name) }}</dd></div><div><dt class="font-semibold text-slate-500">Tax default</dt><dd class="mt-1">{{ $product->taxable ? 'Taxable' : 'Non-taxable' }}</dd></div></dl></section></aside>
    </div>
</x-layouts.office>
