<x-layouts.office title="Convert accepted scope" width="detail">
    <div class="space-y-6">
        <nav class="text-sm" aria-label="Breadcrumb"><a class="font-bold text-brand-blue" href="{{ route('office.proposal-publications.show', $publication) }}">← Accepted Proposal</a></nav>
        <header class="border-b border-slate-200 pb-5"><p class="text-sm font-bold uppercase tracking-[.12em] text-brand-blue">Project conversion review</p><h1 class="mt-1 text-3xl font-bold">Convert accepted scope</h1><p class="mt-2 text-slate-600">{{ $publication->snapshot['document']['number'] }} · {{ $publication->snapshot['customer']['display_name'] }} · ${{ number_format($acceptance->total_cents / 100, 2) }}</p></header>
        <x-form-errors />
        <form method="POST" action="{{ route('office.proposal-publications.convert.store', $publication) }}" class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">@csrf
            <main class="space-y-6">
                <section class="surface overflow-hidden"><header class="border-b border-slate-200 p-5"><h2 class="text-xl font-bold">Accepted scope review</h2><p class="mt-1 text-sm text-slate-600">Only selected, accepted lines become planning rows. Allowances remain unresolved and are excluded.</p></header><div class="divide-y divide-slate-200">
                    @foreach($acceptance->selections->where('included', true) as $selection)
                        @php($line = $selection->line_snapshot)
                        <article class="p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><strong>{{ $line['description'] }}</strong><p class="mt-1 text-sm text-slate-600">{{ Str::headline($line['type']) }} · {{ rtrim(rtrim(number_format($line['quantity_millis']/1000,3,'.',''),'0'),'.') }} {{ $line['unit_name'] }}@if($line['location'] ?? null) · {{ $line['location'] }}@endif @if($line['system'] ?? null) · {{ $line['system'] }}@endif @if($line['phase'] ?? null) · {{ $line['phase'] }}@endif</p></div><strong>${{ number_format($line['total_cents']/100,2) }}</strong></div>
                            @if(($line['type'] ?? null) === 'package' && !empty($line['conversion_components']))<details class="mt-3"><summary class="min-h-11 cursor-pointer py-2 font-bold text-brand-blue">Internal Package recipe</summary><ul class="space-y-1 text-sm text-slate-600">@foreach($line['conversion_components'] as $component)<li>{{ $component['name'] }} · {{ rtrim(rtrim(number_format(($line['quantity_millis']*$component['quantity_millis']/1000000),3,'.',''),'0'),'.') }} {{ $component['unit_name'] }}</li>@endforeach</ul></details>@endif
                            @if(($line['type'] ?? null) !== 'allowance' && $activeMembership->hasCapability('projects.admin') && $activeMembership->hasCapability('dispatch.manage'))<label class="mt-3 flex min-h-11 items-center gap-3 rounded-lg border border-slate-200 px-3"><input type="checkbox" name="ticket_line_ids[]" value="{{ $selection->publication_line_id }}" @checked(in_array($selection->publication_line_id, old('ticket_line_ids', [])))><span>Create a draft operational Service Ticket for this line</span></label>@endif
                        </article>
                    @endforeach
                </div></section>
                <section class="surface overflow-hidden"><header class="border-b border-slate-200 p-5"><h2 class="text-xl font-bold">Accepted billing milestones</h2><p class="mt-1 text-sm text-slate-600">The accepted deposit remains an ordinary Billing draft. Later Project milestone completion creates later drafts only.</p></header><div class="divide-y divide-slate-200">@forelse($acceptance->milestones as $milestone)<div class="flex justify-between gap-4 p-4"><span>{{ $milestone->name }}</span><span class="text-right font-bold">${{ number_format($milestone->allocated_cents/100,2) }}<span class="block text-xs font-normal text-slate-500">{{ $milestone->invoice ? 'Draft '.$milestone->invoice->invoice_number : 'Not invoiced' }}</span></span></div>@empty<p class="p-5 text-sm text-slate-500">No accepted payment milestones.</p>@endforelse</div></section>
            </main>
            <aside class="space-y-5">
                <section class="surface p-5"><h2 class="font-bold">Project destination</h2><fieldset class="mt-4 space-y-3"><legend class="sr-only">Choose Project destination</legend><label class="flex min-h-11 items-center gap-3"><input type="radio" name="project_mode" value="new" @checked(old('project_mode','new')==='new')><span>Create a new Project</span></label><label class="flex min-h-11 items-center gap-3"><input type="radio" name="project_mode" value="existing" @checked(old('project_mode')==='existing')><span>Use an existing compatible Project</span></label></fieldset><label class="form-label mt-4" for="project_name">New Project name</label><input class="form-input" id="project_name" name="project_name" value="{{ old('project_name', $publication->snapshot['document']['title']) }}"><label class="form-label mt-4" for="project_type">Project type</label><select class="form-input" id="project_type" name="project_type"><option value="installation_project">Installation Project</option><option value="ongoing_support">Ongoing Support</option><option value="consulting_engineering">Consulting / Engineering</option></select><label class="form-label mt-4" for="project_id">Existing Project</label><select class="form-input" id="project_id" name="project_id"><option value="">Choose Project</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int)old('project_id')===$project->id)>{{ $project->project_number }} — {{ $project->name }}</option>@endforeach</select><label class="mt-4 flex min-h-11 items-start gap-3"><input class="mt-1" type="checkbox" name="confirm_location_mismatch" value="1" @checked(old('confirm_location_mismatch'))><span class="text-sm">Confirm a different same-customer Project location when applicable.</span></label></section>
                <section class="surface p-5"><label class="form-label" for="project_conversion_template_id">Project template</label><select class="form-input" id="project_conversion_template_id" name="project_conversion_template_id"><option value="">Accepted scope only</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((int)old('project_conversion_template_id')===$template->id)>{{ $template->name }} · {{ $template->workstreams->count() }} Workstreams · {{ $template->milestones->count() }} Milestones</option>@endforeach</select></section>
                <section class="surface p-5"><h2 class="font-bold">Commit conversion</h2><p class="mt-2 text-sm text-slate-600">This creates append-only planning provenance. It does not issue invoices, collect payments, reserve inventory, or change the accepted Proposal.</p><label class="mt-4 flex min-h-11 items-start gap-3 rounded-lg border border-amber-300 bg-amber-50 p-3"><input class="mt-1" type="checkbox" name="confirm_conversion" value="1" required><span>I reviewed the Project destination, planning rows, milestone mapping, and selected Tickets.</span></label><button class="button-primary mt-4 w-full">Convert accepted scope</button></section>
            </aside>
        </form>
    </div>
</x-layouts.office>
