<x-layouts.office title="Proposal publication" width="detail">
    @php($snapshot = $publication->snapshot)
    <div class="space-y-6">
        <nav class="text-sm" aria-label="Breadcrumb"><a class="font-bold text-brand-blue" href="{{ route('office.quotes.show', [$publication->revision->document, $publication->revision]) }}">← {{ $snapshot['document']['number'] }}</a></nav>
        <header class="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-end lg:justify-between">
            <div><p class="text-sm font-bold uppercase tracking-[.12em] text-brand-blue">Immutable publication</p><h1 class="mt-1 text-3xl font-bold">{{ $snapshot['document']['title'] }}</h1><p class="mt-2 text-slate-600">{{ $snapshot['customer']['display_name'] }} · {{ str($publication->status)->headline() }}</p></div>
            <div class="flex flex-wrap gap-2">@if($publication->pdf_status === 'ready')<a class="button-primary" href="{{ route('office.proposal-publications.pdf', $publication) }}">Download PDF</a>@elseif($publication->pdf_status === 'failed' && $canPublish)<form method="POST" action="{{ route('office.proposal-publications.pdf.retry', $publication) }}">@csrf<button class="button-secondary">Retry PDF</button></form>@else<span class="status-badge">PDF {{ $publication->pdf_status }}</span>@endif</div>
        </header>
        @if(session('proposal_token_once'))
            <div class="rounded-lg border border-amber-300 bg-amber-50 p-4" role="status"><p class="font-bold">{{ session('proposal_token_record') }} — secure link shown once</p><code class="mt-2 block break-all text-sm">{{ session('proposal_token_once') }}</code><p class="mt-2 text-sm">Copy this link now. Only its hash is retained after this response.</p></div>
        @endif
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
            <main class="space-y-5">
                <section class="surface p-6">
                    <div class="flex justify-between gap-4"><h2 class="text-xl font-bold">Customer preview</h2><span class="status-badge">{{ $publication->template->name }}</span></div>
                    @foreach($snapshot['template']['sections'] as $templateSection)
                        @continue(! $templateSection['customer_visible'])
                        @switch($templateSection['section_type'])
                            @case('cover')
                                <section class="mt-6 border-b border-slate-200 pb-5"><h2 class="text-2xl font-bold">{{ $snapshot['document']['title'] }}</h2><p class="mt-2 text-sm text-slate-600">Prepared for {{ $snapshot['customer']['display_name'] }}@if($snapshot['customer']['site_name']) · {{ $snapshot['customer']['site_name'] }}@endif</p></section>
                                @break
                            @case('scope')
                                <section class="mt-6"><h2 class="text-xl font-bold">{{ $templateSection['heading'] }}</h2>@forelse($snapshot['sections'] as $section)<article class="mt-4"><h3 class="font-bold">{{ $section['heading'] }}</h3><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $section['body'] }}</p></article>@empty<p class="mt-2 text-sm text-slate-500">No customer-visible scope sections.</p>@endforelse</section>
                                @break
                            @case('pricing')
                                <section class="mt-6"><h2 class="text-xl font-bold">{{ $templateSection['heading'] }}</h2><div class="mt-3 overflow-hidden rounded-lg border border-slate-200"><div class="divide-y divide-slate-200">@foreach($snapshot['lines'] as $line)@if(! $line['optional'] || $line['included'])<article class="flex justify-between gap-4 p-4"><div><p class="font-bold">{{ $line['description'] }}</p><p class="text-sm text-slate-600">{{ rtrim(rtrim(number_format($line['quantity_millis'] / 1000, 3, '.', ''), '0'), '.') }} {{ $line['unit_name'] }}</p></div>@if($snapshot['publication']['show_line_details'])<strong>${{ number_format($line['total_cents'] / 100, 2) }}</strong>@endif</article>@endif @endforeach</div></div><dl class="ml-auto mt-6 max-w-sm space-y-2"><div class="flex justify-between"><dt>Subtotal</dt><dd>${{ number_format($snapshot['totals']['subtotal_cents'] / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Discount</dt><dd>−${{ number_format(($snapshot['totals']['line_discount_cents'] + $snapshot['totals']['quote_discount_cents']) / 100, 2) }}</dd></div><div class="flex justify-between"><dt>Tax</dt><dd>${{ number_format($snapshot['totals']['tax_cents'] / 100, 2) }}</dd></div><div class="flex justify-between border-t border-slate-200 pt-3 text-xl font-bold"><dt>Total</dt><dd>${{ number_format($snapshot['totals']['total_cents'] / 100, 2) }}</dd></div></dl></section>
                                @break
                            @case('media')
                                @if($snapshot['media'] !== [])<section class="mt-6"><h2 class="text-xl font-bold">{{ $templateSection['heading'] }}</h2><ul class="mt-3 divide-y divide-slate-200 rounded-lg border border-slate-200">@foreach($snapshot['media'] as $media)<li class="p-4"><p class="font-semibold">{{ $media['caption'] ?: ($media['original_name'] ?: 'Embedded video') }}</p><p class="mt-1 text-xs text-slate-500">{{ str($media['media_type'])->headline() }}@if($media['byte_size']) · {{ number_format($media['byte_size'] / 1024, 1) }} KB @endif</p>@if($media['media_type'] === 'video')<a class="mt-2 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ $media['embed_url'] }}" target="_blank" rel="noreferrer">Open video</a>@endif</li>@endforeach</ul></section>@endif
                                @break
                            @case('terms')
                                <section class="mt-6 border-t border-slate-200 pt-5"><h2 class="text-xl font-bold">{{ $templateSection['heading'] ?: ($snapshot['terms']['name'] ?: 'Terms') }}</h2><p class="mt-3 whitespace-pre-line text-sm text-slate-700">{{ $snapshot['terms']['body'] }}</p></section>
                                @break
                        @endswitch
                    @endforeach
                </section>
                <section class="surface overflow-hidden"><header class="border-b border-slate-200 p-5"><h2 class="text-xl font-bold">Audit history</h2><p class="mt-1 text-sm text-slate-600">Bounded approval and publication activity. Sensitive content is excluded.</p></header><ol class="divide-y divide-slate-200">@forelse($audits as $audit)<li class="p-4"><p class="font-semibold">{{ str($audit->event_type)->replace('.', ' ')->headline() }}</p><p class="mt-1 text-xs text-slate-500">{{ $audit->actor?->name ?? 'System' }} · {{ $audit->occurred_at->timezone($activeOrganization->timezone)->format('M j, Y g:i A T') }}</p></li>@empty<li class="p-4 text-sm text-slate-500">No approval or publication activity recorded.</li>@endforelse</ol></section>
            </main>
            <aside class="space-y-5">
                <section class="surface p-5"><h2 class="font-bold">Publication record</h2><dl class="mt-3 space-y-2 text-sm"><div><dt class="text-slate-500">Published</dt><dd><x-local-time :value="$publication->published_at" :timezone="$activeOrganization->timezone" /></dd></div><div><dt class="text-slate-500">Expires</dt><dd><x-local-time :value="$publication->expires_at" :timezone="$activeOrganization->timezone" /></dd></div><div><dt class="text-slate-500">Snapshot hash</dt><dd class="break-all font-mono text-xs">{{ $publication->publication_hash }}</dd></div></dl></section>
                @if($canPublish)<section class="surface p-5"><h2 class="font-bold">Secure customer access</h2><p class="mt-1 text-sm text-slate-600">Recipient links bind acceptance to that email. Generic links require email verification.</p><form method="POST" action="{{ route('office.proposal-publications.recipients.store', $publication) }}" class="mt-4 space-y-2">@csrf<label class="form-label" for="recipient-name">Name</label><input class="form-input" id="recipient-name" name="name"><label class="form-label" for="recipient-email">Email</label><input class="form-input" id="recipient-email" type="email" name="email" required><button class="button-secondary w-full">Create recipient link</button></form><form method="POST" action="{{ route('office.proposal-publications.share-links.store', $publication) }}" class="mt-4 border-t border-slate-200 pt-4">@csrf<label class="form-label" for="share-label">Generic-link label</label><input class="form-input" id="share-label" name="label"><button class="button-secondary mt-2 w-full">Create generic link</button></form></section>@endif
                @if($canEngagement)<section class="surface overflow-hidden"><header class="p-5"><h2 class="font-bold">Delivery records</h2></header><div class="divide-y divide-slate-200">@foreach($publication->recipients as $recipient)<div class="p-4"><p class="font-semibold">{{ $recipient->name ?: $recipient->email }}</p><p class="text-xs text-slate-500">{{ $recipient->email }} · {{ $recipient->revoked_at ? 'Revoked' : 'Active' }}</p>@if($canPublish && ! $recipient->revoked_at)<div class="mt-2 flex gap-2"><form method="POST" action="{{ route('office.proposal-publications.deliver', [$publication, $recipient]) }}">@csrf<button class="button-secondary">Queue local email</button></form><form method="POST" action="{{ route('office.proposal-publications.recipients.revoke', [$publication, $recipient]) }}">@csrf<button class="button-danger">Revoke</button></form></div>@endif</div>@endforeach @foreach($publication->deliveries as $delivery)<div class="p-4 text-sm"><strong>{{ str($delivery->delivery_type)->headline() }}</strong> · {{ str($delivery->status)->headline() }}@if($delivery->safe_failure_code)<p class="text-red-700">{{ $delivery->safe_failure_code }}</p>@endif</div>@endforeach</div></section>@endif
                @if($canEngagement)
                    <section class="surface overflow-hidden">
                        <header class="border-b border-slate-200 p-5"><h2 class="font-bold">Customer engagement</h2><p class="mt-1 text-sm text-slate-600">Every secure view and response is retained. Network addresses are encrypted at rest.</p></header>
                        <ol class="max-h-96 divide-y divide-slate-200 overflow-y-auto">
                            @forelse($publication->engagementEvents->sortByDesc('occurred_at') as $engagement)
                                <li class="p-4"><p class="font-semibold">{{ str($engagement->event_type)->replace('_', ' ')->headline() }}</p><p class="mt-1 text-xs text-slate-500">{{ $engagement->recipient?->email ?? ($engagement->shareLink?->label ?: 'Generic link') }} · <x-local-time :value="$engagement->occurred_at" :timezone="$activeOrganization->timezone" /></p></li>
                            @empty<li class="p-4 text-sm text-slate-500">No customer engagement yet.</li>@endforelse
                        </ol>
                    </section>
                    <section class="surface p-5"><h2 class="font-bold">Proposal discussion</h2><div class="mt-3 space-y-3">@forelse($publication->comments as $comment)<article class="rounded-lg border border-slate-200 p-3"><p class="text-xs font-bold uppercase text-slate-500">{{ $comment->author_type === 'staff' ? ($comment->staffUser?->name ?? 'Staff') : ($comment->author_name ?: 'Customer') }} · {{ str($comment->target_type)->headline() }}</p><p class="mt-1 whitespace-pre-line text-sm">{{ $comment->body }}</p></article>@empty<p class="text-sm text-slate-500">No comments yet.</p>@endforelse</div><form method="POST" action="{{ route('office.proposal-publications.comments.store', $publication) }}" class="mt-4 space-y-2">@csrf<input type="hidden" name="target_type" value="proposal"><label class="form-label" for="staff-comment">Reply</label><textarea class="form-textarea" id="staff-comment" name="body" required></textarea><button class="button-secondary w-full">Add staff reply</button></form></section>
                    @if($publication->acceptance)
                        <section class="surface p-5"><p class="text-xs font-bold uppercase tracking-[.12em] text-emerald-700">Accepted</p><h2 class="mt-1 font-bold">{{ $publication->acceptance->signer_name }}</h2><p class="text-sm text-slate-600">{{ $publication->acceptance->signer_title }} · {{ $publication->acceptance->signer_email }}</p><dl class="mt-3 space-y-2 text-sm"><div><dt class="text-slate-500">Accepted total</dt><dd class="font-bold">${{ number_format($publication->acceptance->total_cents / 100, 2) }}</dd></div><div><dt class="text-slate-500">Signed</dt><dd><x-local-time :value="$publication->acceptance->signed_at" :timezone="$activeOrganization->timezone" /></dd></div></dl><a class="button-secondary mt-4 w-full" href="{{ route('office.proposal-publications.acceptances.signature', [$publication, $publication->acceptance]) }}">View signature</a>@if($publication->acceptance->milestones->isNotEmpty())<div class="mt-3 rounded-lg border border-slate-200 p-3 text-sm"><p class="font-bold">Accepted payment schedule</p>@foreach($publication->acceptance->milestones as $milestone)<p class="mt-1">{{ $milestone->name }} · ${{ number_format($milestone->allocated_cents / 100, 2) }} · {{ $milestone->invoice ? 'Draft invoice '.$milestone->invoice->invoice_number : 'Later milestone' }}</p>@endforeach</div>@endif<p class="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm">The first scheduled milestone is an ordinary Billing draft for review. No payment is created automatically.</p></section>
                    @endif
                @endif
                @if($canExtend && in_array($publication->status, ['active', 'expired'], true) && ! $publication->acceptance)
                    <form method="POST" action="{{ route('office.proposal-publications.extend', $publication) }}" class="surface p-5">@csrf<h2 class="font-bold">Extend expiration</h2><p class="mt-1 text-sm text-slate-600">Admin Catalog price review is required. Changed prices require a new revision.</p><label class="form-label mt-4" for="expires-on">New expiration date</label><input class="form-input" id="expires-on" name="expires_on" type="date" required><label class="mt-3 flex min-h-11 items-start gap-3"><input class="mt-1" type="checkbox" name="confirm_price_review" value="1" required><span>I reviewed current Catalog pricing.</span></label><button class="button-secondary mt-3 w-full">Extend publication</button></form>
                @endif
                @if($canPublish && $publication->status === 'active')<form method="POST" action="{{ route('office.proposal-publications.withdraw', $publication) }}" class="surface p-5">@csrf<label class="flex min-h-11 items-start gap-3"><input class="mt-1" type="checkbox" name="confirm" value="1" required><span><strong>Withdraw publication</strong><span class="block text-sm text-slate-600">The immutable record remains available internally.</span></span></label><button class="button-danger mt-3 w-full">Withdraw</button></form>@endif
            </aside>
        </div>
    </div>
</x-layouts.office>
