<x-form-errors />
<div class="grid gap-4 md:grid-cols-2">
    <div><label class="form-label" for="scheduled_start">Local start ({{ $visit->timezone ?? $ticket->serviceLocation->timezone }})</label><input type="datetime-local" class="form-input" id="scheduled_start" name="scheduled_start" value="{{ old('scheduled_start', isset($visit) ? $visit->scheduledStartLocal()?->format('Y-m-d\\TH:i') : '') }}"></div>
    <div><label class="form-label" for="scheduled_end">Local end</label><input type="datetime-local" class="form-input" id="scheduled_end" name="scheduled_end" value="{{ old('scheduled_end', isset($visit) ? $visit->scheduledEndLocal()?->format('Y-m-d\\TH:i') : '') }}"></div>
</div>
<p class="mt-2 text-sm text-slate-500">Leave both times blank to keep this visit planned. Times are saved in UTC and displayed in the service location timezone.</p>
<fieldset class="mt-6"><legend class="font-bold text-slate-950">Crew</legend><div class="mt-3 grid gap-3 sm:grid-cols-2">@foreach($memberships as $membership)<label class="flex min-h-11 items-center gap-3 rounded-lg border border-slate-200 px-3"><input type="checkbox" name="assignees[]" value="{{ $membership->id }}" @checked(in_array($membership->id, old('assignees', isset($visit) ? $visit->assignments->pluck('organization_membership_id')->all() : [])))><span>{{ $membership->user->name }}</span></label>@endforeach</div></fieldset>
<div class="mt-4"><label class="form-label" for="lead_membership_id">Lead assignee</label><select class="form-input" id="lead_membership_id" name="lead_membership_id" aria-describedby="lead-membership-help"><option value="">Choose lead</option>@foreach($memberships as $membership)<option value="{{ $membership->id }}" @selected((string)old('lead_membership_id', isset($visit) ? $visit->assignments->firstWhere('is_lead', true)?->organization_membership_id : '')===(string)$membership->id)>{{ $membership->user->name }}</option>@endforeach</select><p id="lead-membership-help" class="mt-2 text-sm text-slate-500">A single crew member becomes lead automatically. Choose the lead when assigning two or more people.</p></div>
@error('schedule_conflict')<div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-900">{{ $message }}<label class="mt-3 flex min-h-11 items-center gap-2"><input type="checkbox" name="confirm_conflicts" value="1"> Confirm overlapping schedule</label></div>@enderror
