<x-layouts.office title="Catalog services" width="workspace">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-office.page-header title="Products & Services" description="Maintain standardized customer-facing services and protected pricing defaults." eyebrow="Catalog">
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:actions><a class="button-primary" href="{{ route('office.catalog.services.create') }}">Add service</a></x-slot:actions>
        @endif
    </x-office.page-header>
    <x-office.catalog-tabs />
    <form method="GET" class="office-filter-toolbar xl:grid-cols-[minmax(220px,1fr)_220px_200px_170px_auto]" aria-label="Service filters">
        <div><label class="form-label" for="q">Name or code</label><input class="form-input" id="q" name="q" value="{{ request('q') }}" type="search"></div>
        <div><label class="form-label" for="category">Category</label><select class="form-input" id="category" name="category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div>
        <div><label class="form-label" for="pricing_model">Pricing</label><select class="form-input" id="pricing_model" name="pricing_model"><option value="">All models</option>@foreach(App\Models\CatalogService::PRICING_MODELS as $model)<option value="{{ $model }}" @selected(request('pricing_model')===$model)>{{ Str::headline($model) }}</option>@endforeach</select></div>
        <div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div>
        <div class="flex flex-wrap gap-2"><button class="button-secondary">Filter</button>@if(request()->query())<a class="inline-flex min-h-11 items-center px-2 text-sm font-bold text-brand-blue underline" href="{{ route('office.catalog.services.index') }}">Clear</a>@endif</div>
    </form>
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Catalog services</caption><thead><tr><th scope="col">Service</th><th scope="col">Category</th><th scope="col">Pricing model</th><th scope="col">Default price</th><th scope="col">Sales unit</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>
        @forelse($services as $service)<tr><td><a class="font-bold text-brand-blue" href="{{ route('office.catalog.services.show',$service) }}">{{ $service->service_code }}</a><p class="mt-0.5 font-semibold text-slate-950">{{ $service->name }}</p></td><td>{{ $service->category?->name ?? 'Uncategorized' }}</td><td>{{ Str::headline($service->pricing_model) }}@if($service->variants_count)<p class="text-xs text-slate-500">{{ $service->variants_count }} variants</p>@endif</td><td>{{ $service->default_price_cents === null ? 'Price required' : '$'.number_format($service->default_price_cents/100,2) }}</td><td>{{ $service->salesUom->name }}</td><td><span class="{{ $service->active ? 'status-success' : 'status-muted' }}">{{ $service->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right"><a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.services.show',$service) }}">Open</a></td></tr>
        @empty<tr><td colspan="7" class="py-10 text-center"><p class="font-bold text-slate-900">No services found</p><p class="mt-1 text-sm text-slate-500">Create a service or adjust the filters.</p></td></tr>@endforelse
    </tbody></table></div>
    <div class="office-mobile-list">@forelse($services as $service)<article class="office-mobile-card"><div class="flex items-start justify-between gap-3"><div><a class="font-bold text-brand-blue" href="{{ route('office.catalog.services.show',$service) }}">{{ $service->service_code }}</a><h2 class="mt-1 font-bold text-slate-950">{{ $service->name }}</h2></div><span class="{{ $service->active ? 'status-success' : 'status-muted' }}">{{ $service->active ? 'Active' : 'Inactive' }}</span></div><dl class="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt class="font-semibold text-slate-500">Pricing</dt><dd>{{ Str::headline($service->pricing_model) }}</dd></div><div><dt class="font-semibold text-slate-500">Price</dt><dd>{{ $service->default_price_cents === null ? 'Required' : '$'.number_format($service->default_price_cents/100,2) }}</dd></div></dl><a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.services.show',$service) }}">Open service</a></article>@empty<div class="surface p-8 text-center"><p class="font-bold">No services found</p></div>@endforelse</div>
    <div class="mt-5">{{ $services->links() }}</div>
</x-layouts.office>
