<x-layouts.office :title="$service->name" width="detail">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-form-errors />
    <x-office.record-header :title="$service->name" :back-href="route('office.catalog.services.index')" back-label="Services" :description="$service->customer_description ?: 'No customer description.'">
        <x-slot:badges><span class="{{ $service->active ? 'status-success' : 'status-muted' }}">{{ $service->active ? 'Active' : 'Inactive' }}</span><span class="status-active">{{ Str::headline($service->pricing_model) }}</span></x-slot:badges>
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:actions><a class="button-primary" href="{{ route('office.catalog.services.edit',$service) }}">Edit service</a></x-slot:actions>
        @endif
    </x-office.record-header>
    <x-office.catalog-tabs />
    <x-office.detail-nav :items="['overview'=>'Overview','variants'=>'Variants','addons'=>'Add-ons']" />
    <div class="office-detail-grid">
        <div class="office-detail-main">
            <section id="overview" class="surface scroll-mt-6 p-5"><h2 class="text-xl font-bold">Service definition</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm font-semibold text-slate-500">Code</dt><dd class="mt-1 font-bold">{{ $service->service_code }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Category</dt><dd class="mt-1">{{ $service->category?->name ?? 'Uncategorized' }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Sales unit</dt><dd class="mt-1">{{ $service->salesUom->name }}</dd></div><div><dt class="text-sm font-semibold text-slate-500">Estimated duration</dt><dd class="mt-1">{{ $service->estimated_duration_minutes ? $service->estimated_duration_minutes.' minutes' : 'Not set' }}</dd></div></dl>@if($service->internal_description)<div class="mt-5 border-t border-slate-200 pt-4"><h3 class="font-bold">Internal description</h3><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $service->internal_description }}</p></div>@endif<div class="mt-5 grid gap-4 border-t border-slate-200 pt-4 sm:grid-cols-2"><div><h3 class="font-bold">Internal scope</h3><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $service->internal_scope ?: 'Not documented.' }}</p></div><div><h3 class="font-bold">Internal exclusions</h3><p class="mt-2 whitespace-pre-line text-sm text-slate-700">{{ $service->internal_exclusions ?: 'Not documented.' }}</p></div></div></section>
            <section id="variants" class="surface scroll-mt-6 p-5"><div><h2 class="text-xl font-bold">Variants</h2><p class="mt-1 text-sm text-slate-600">Explicit selectable options for variant-priced services.</p></div>
                @if($service->pricing_model !== 'variant')<p class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">Change the pricing model to Variant before adding options.</p>
                @else<div class="mt-5 space-y-4">@forelse($service->variants as $variant)<article class="rounded-lg border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold">{{ $variant->label }}</h3><p class="text-sm text-slate-500">{{ $variant->code }} · {{ $variant->customer_label ?: 'Uses internal label' }}</p></div><span class="{{ $variant->active ? 'status-success' : 'status-muted' }}">{{ $variant->active ? 'Active' : 'Inactive' }}</span></div><p class="mt-2 text-sm font-semibold">{{ $variant->price_override_cents === null ? 'Uses service default price' : '$'.number_format($variant->price_override_cents/100,2) }}</p>
                    @if($activeMembership->hasCapability('catalog.manage'))<details class="mt-3"><summary class="min-h-11 cursor-pointer py-3 font-bold text-brand-blue">Edit variant</summary><form method="POST" action="{{ route('office.catalog.services.variants.update',[$service,$variant]) }}" class="grid gap-3 sm:grid-cols-2">@csrf @method('PUT')<input class="form-input" name="code" value="{{ $variant->code }}" aria-label="Variant code" required><input class="form-input" name="label" value="{{ $variant->label }}" aria-label="Variant label" required><input class="form-input" name="customer_label" value="{{ $variant->customer_label }}" aria-label="Customer label" placeholder="Customer label"><input class="form-input" name="estimated_duration_minutes" type="number" min="1" value="{{ $variant->estimated_duration_minutes }}" aria-label="Estimated duration minutes" placeholder="Duration minutes">@if($activeMembership->hasCapability('catalog.pricing.manage'))<input class="form-input" name="price_override" inputmode="decimal" value="{{ $variant->price_override_cents === null ? '' : number_format($variant->price_override_cents/100,2,'.','') }}" aria-label="Price override" placeholder="Price override">@endif<input class="form-input" name="sort_order" type="number" min="0" value="{{ $variant->sort_order }}" aria-label="Sort order"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" @checked($variant->active)> Active</label><button class="button-secondary">Save variant</button></form></details>@endif
                </article>@empty<p class="text-sm text-slate-600">No variants configured.</p>@endforelse</div>
                @if($activeMembership->hasCapability('catalog.manage'))<form method="POST" action="{{ route('office.catalog.services.variants.store',$service) }}" class="mt-6 border-t border-slate-200 pt-5"><h3 class="font-bold">Add variant</h3><div class="mt-3 grid gap-3 sm:grid-cols-2"><input class="form-input" name="code" value="{{ old('code') }}" aria-label="New variant code" placeholder="Code" required><input class="form-input" name="label" value="{{ old('label') }}" aria-label="New variant label" placeholder="Internal label" required><input class="form-input" name="customer_label" value="{{ old('customer_label') }}" aria-label="New variant customer label" placeholder="Customer label"><input class="form-input" name="estimated_duration_minutes" type="number" min="1" value="{{ old('estimated_duration_minutes') }}" aria-label="New variant duration" placeholder="Duration minutes">@if($activeMembership->hasCapability('catalog.pricing.manage'))<input class="form-input" name="price_override" inputmode="decimal" value="{{ old('price_override') }}" aria-label="New variant price override" placeholder="Price override">@endif<input class="form-input" name="sort_order" type="number" min="0" value="{{ old('sort_order',0) }}" aria-label="New variant sort order"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" checked> Active</label><button class="button-primary">Add variant</button></div></form>@endif @endif
            </section>
            <section id="addons" class="surface scroll-mt-6 p-5"><h2 class="text-xl font-bold">Optional add-ons</h2><p class="mt-1 text-sm text-slate-600">Related services are suggestions only. They do not add themselves or change pricing.</p>@if($activeMembership->hasCapability('catalog.manage'))<form method="POST" action="{{ route('office.catalog.services.addons.update',$service) }}" class="mt-4">@csrf @method('PUT')<div class="grid gap-2 sm:grid-cols-2">@forelse($addonCandidates as $candidate)<label class="flex min-h-11 items-center gap-3 rounded-lg border border-slate-200 px-3"><input type="checkbox" name="addon_service_ids[]" value="{{ $candidate->id }}" @checked($service->addons->contains($candidate->id))><span><strong>{{ $candidate->name }}</strong><span class="block text-xs text-slate-500">{{ $candidate->service_code }}</span></span></label>@empty<p class="text-sm text-slate-600">Create another active service to use it as an add-on.</p>@endforelse</div>@if($addonCandidates->isNotEmpty())<button class="button-secondary mt-4">Save add-ons</button>@endif</form>@else<div class="mt-4 space-y-2">@forelse($service->addons as $addon)<a class="block min-h-11 rounded-lg border border-slate-200 p-3 font-bold text-brand-blue" href="{{ route('office.catalog.services.show',$addon) }}">{{ $addon->name }}</a>@empty<p class="text-sm text-slate-600">No add-ons configured.</p>@endforelse</div>@endif</section>
        </div>
        <aside class="office-detail-rail"><section class="surface p-5"><h2 class="font-bold">Pricing</h2><p class="mt-3 text-2xl font-bold">{{ $service->default_price_cents === null ? 'Price required' : '$'.number_format($service->default_price_cents/100,2) }}</p><p class="mt-1 text-sm text-slate-600">{{ Str::headline($service->pricing_model) }} per {{ strtolower($service->salesUom->name) }}</p>@if($service->pricing_model==='recurring')<p class="mt-2 text-sm font-semibold">Every {{ $service->billing_interval }} {{ Str::plural($service->billing_cadence,$service->billing_interval) }}</p>@endif<dl class="mt-5 space-y-3 border-t border-slate-200 pt-4 text-sm"><div><dt class="font-semibold text-slate-500">Tax default</dt><dd>{{ $service->taxable ? 'Taxable' : 'Non-taxable' }}</dd></div><div><dt class="font-semibold text-slate-500">Customer visibility</dt><dd>{{ $service->customer_visible ? 'Visible' : 'Internal only' }}</dd></div><div><dt class="font-semibold text-slate-500">Office approval</dt><dd>{{ $service->requires_office_approval ? 'Required' : 'Not required' }}</dd></div></dl></section></aside>
    </div>
</x-layouts.office>
