<x-layouts.office title="Catalog units" width="workspace">
    @if(session('status'))<x-office.alert type="success">{{ session('status') }}</x-office.alert>@endif
    <x-office.primary-toolbar title="Products & Services" description="Define reusable sales, purchase, and base units without tracking inventory quantities." eyebrow="Catalog">
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:primaryAction><a class="button-primary" href="{{ route('office.catalog.units.create') }}">Add unit</a></x-slot:primaryAction>
        @endif
    </x-office.primary-toolbar>
    <x-office.catalog-tabs />
    <form method="GET" class="office-filter-toolbar sm:grid-cols-[minmax(220px,1fr)_180px_180px_auto]" aria-label="Unit filters"><div><label class="form-label" for="q">Name or code</label><input class="form-input" id="q" name="q" type="search" value="{{ request('q') }}"></div><div><label class="form-label" for="dimension">Dimension</label><select class="form-input" id="dimension" name="dimension"><option value="">All</option>@foreach(['count','length','time','service','period','package'] as $dimension)<option value="{{ $dimension }}" @selected(request('dimension')===$dimension)>{{ ucfirst($dimension) }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="flex gap-2"><button class="button-secondary">Filter</button>@if(request()->query())<a class="inline-flex min-h-11 items-center px-2 font-bold text-brand-blue underline" href="{{ route('office.catalog.units.index') }}">Clear</a>@endif</div></form>
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Units of measure</caption><thead><tr><th scope="col">Unit</th><th scope="col">Dimension</th><th scope="col">Precision</th><th scope="col">Services</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>@forelse($units as $unit)<tr><td><p class="font-bold">{{ $unit->name }}{{ $unit->symbol ? ' ('.$unit->symbol.')' : '' }}</p><p class="text-xs text-slate-500">{{ $unit->code }}</p></td><td>{{ ucfirst($unit->dimension) }}</td><td>{{ $unit->decimal_places }} decimal places</td><td>{{ $unit->services_count }}</td><td><span class="{{ $unit->active ? 'status-success' : 'status-muted' }}">{{ $unit->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right">@if($activeMembership->hasCapability('catalog.manage'))<a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.units.edit',$unit) }}">Edit</a>@else<span class="text-sm text-slate-500">Read only</span>@endif</td></tr>@empty<tr><td colspan="6" class="py-10 text-center"><p class="font-bold">No units found</p></td></tr>@endforelse</tbody></table></div>
    <div class="office-mobile-list">@forelse($units as $unit)<article class="office-mobile-card"><div class="flex justify-between gap-3"><div><h2 class="font-bold">{{ $unit->name }}</h2><p class="text-xs text-slate-500">{{ $unit->code }} · {{ ucfirst($unit->dimension) }}</p></div><span class="{{ $unit->active ? 'status-success' : 'status-muted' }}">{{ $unit->active ? 'Active' : 'Inactive' }}</span></div><p class="mt-3 text-sm">Precision: {{ $unit->decimal_places }} decimal places</p>@if($activeMembership->hasCapability('catalog.manage'))<a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.units.edit',$unit) }}">Edit unit</a>@endif</article>@empty<div class="surface p-8 text-center"><p class="font-bold">No units found</p></div>@endforelse</div><div class="mt-5">{{ $units->links() }}</div>
</x-layouts.office>
