@php($visits = collect($serviceContext['visits'] ?? []))
@php($workItems = collect($serviceContext['work_items'] ?? []))
<section class="service-details">
    <h2>Service Details</h2>
    <p><strong>{{ $serviceContext['ticket']['number'] }} · {{ $serviceContext['ticket']['title'] }}</strong><br><span class="muted">{{ $serviceContext['site']['name'] }} · {{ $serviceContext['site']['address'] }}</span>@if($serviceContext['contact']['name'] ?? null)<br><span class="muted">Point of contact: {{ $serviceContext['contact']['name'] }}@if($serviceContext['contact']['role'] ?? null) · {{ $serviceContext['contact']['role'] }}@endif</span>@endif</p>
    <div class="service-block"><h3>Requested service</h3><p>{{ $serviceContext['requested_service']['scope'] ?: ($serviceContext['requested_service']['summary'] ?: 'No customer-facing scope was recorded.') }}</p>@if(($serviceContext['requested_service']['summary'] ?? null) && $serviceContext['requested_service']['summary'] !== ($serviceContext['requested_service']['scope'] ?? null))<p class="muted">{{ $serviceContext['requested_service']['summary'] }}</p>@endif</div>
    @if($workItems->isNotEmpty())<div class="service-block"><h3>Additional Work Items</h3>@foreach($workItems as $item)<div class="service-item"><strong>{{ $item['title'] }}</strong><br><span class="muted">{{ $item['status'] }}</span>@if($item['discovered_visit'] ?? null)<br>Discovered during {{ $item['discovered_visit'] }}@endif @if(!empty($item['handled_visits']))<br>Handled: {{ implode(', ', $item['handled_visits']) }}@endif @if($item['follow_up_ticket'] ?? null)<br>Follow-up: {{ $item['follow_up_ticket'] }}@endif</div>@endforeach</div>@endif
    @if($visits->isNotEmpty())<div class="service-block"><h3>Visit history</h3>@foreach($visits as $visit)<div class="service-item"><strong>{{ $visit['label'] }}</strong> · {{ $visit['status'] }}@if($visit['date'] ?? null)<br>{{ \Illuminate\Support\Carbon::parse($visit['date'])->format('M j, Y') }}@endif @if(!empty($visit['technicians']))<br>Technicians: {{ implode(', ', $visit['technicians']) }}@endif @if($visit['site_window']['start_at'] ?? null)<br>On site: {{ \Illuminate\Support\Carbon::parse($visit['site_window']['start_at'])->timezone($visit['timezone'])->format('g:i A') }}–{{ \Illuminate\Support\Carbon::parse($visit['site_window']['end_at'])->timezone($visit['timezone'])->format('g:i A T') }}@endif @if($visit['work_performed'] ?? null)<p><strong>Work performed</strong><br>{{ $visit['work_performed'] }}</p>@endif @if($visit['recommendations'] ?? null)<p><strong>Recommendations</strong><br>{{ $visit['recommendations'] }}</p>@endif @if($visit['outcome'] ?? null)<p><strong>Outcome:</strong> {{ $visit['outcome'] }}</p>@endif @if(!empty($visit['parts']))<p><strong>Parts and equipment</strong></p><ul class="service-list">@foreach($visit['parts'] as $part)<li>{{ $part['description'] }} · {{ rtrim(rtrim($part['quantity'], '0'), '.') }} {{ $part['unit'] }}</li>@endforeach</ul>@endif @php($ack=$visit['acknowledgment'] ?? ['type'=>'none']) @if($ack['type'] !== 'none')<p><strong>Customer acknowledgment</strong><br>@if($ack['type'] === 'signed'){{ $ack['name'] }}@if($ack['role'] ?? null) · {{ $ack['role'] }}@endif · Signed @else{{ $ack['category'] }}@if($ack['detail'] ?? null) · {{ $ack['detail'] }}@endif @endif @if($ack['occurred_at'] ?? null)<br>{{ \Illuminate\Support\Carbon::parse($ack['occurred_at'])->timezone($visit['timezone'])->format('M j, Y \a\t g:i A T') }}@endif</p>@endif</div>@endforeach</div>@endif
</section>
