<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#1D80F7"><title>{{ $invoice->invoice_number }} | NewDay Tech</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="bg-canvas text-slate-900"><div data-connectivity-banner hidden class="bg-amber-100 px-4 py-2 text-center text-sm font-bold text-amber-900" role="status">You’re offline. Acknowledgment cannot be saved until connectivity returns.</div>
<main class="mx-auto min-h-screen max-w-3xl bg-white p-5 sm:p-8">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <header class="flex flex-wrap items-start justify-between gap-5 border-b-2 border-brand-blue pb-6"><img src="{{ asset('images/newday-logo.png') }}" alt="NewDay Tech LLC" class="w-48"><div class="text-right"><p class="text-sm font-bold text-brand-blue">INVOICE</p><h1 class="mt-1 text-2xl font-bold">{{ $invoice->invoice_number }}</h1><p class="mt-1 text-sm">Issued <x-local-time :value="$invoice->issued_at" :timezone="$activeOrganization->timezone" format="M j, Y" /></p></div></header>
    <div class="grid gap-6 border-b border-slate-200 py-6 sm:grid-cols-2"><section><h2 class="text-xs font-bold uppercase tracking-wider text-slate-500">From</h2><p class="mt-2 font-bold">{{ $invoice->seller_legal_name ?: $invoice->seller_name }}</p><p>{{ $invoice->seller_address_line_1 }}</p>@if($invoice->seller_address_line_2)<p>{{ $invoice->seller_address_line_2 }}</p>@endif<p>{{ $invoice->seller_city }}, {{ $invoice->seller_state }} {{ $invoice->seller_postal_code }}</p><p class="mt-2">{{ $invoice->seller_phone }} · {{ $invoice->seller_email }}</p></section><section><h2 class="text-xs font-bold uppercase tracking-wider text-slate-500">Bill to</h2><p class="mt-2 font-bold">{{ $invoice->billing_legal_name ?: $invoice->billing_name }}</p>@if($invoice->billing_contact_name)<p>{{ $invoice->billing_contact_name }}</p>@endif<p>{{ $invoice->billing_address_line_1 }}</p>@if($invoice->billing_address_line_2)<p>{{ $invoice->billing_address_line_2 }}</p>@endif<p>{{ $invoice->billing_city }}, {{ $invoice->billing_state }} {{ $invoice->billing_postal_code }}</p></section></div>
    <section class="py-6"><h2 class="font-bold">Service</h2><p class="mt-1">{{ $invoice->serviceTicket->ticket_number }} · {{ $invoice->serviceTicket->title }}</p><p class="mt-1 text-sm text-slate-600">{{ $invoice->serviceLocation->name }}</p></section>
    <div class="overflow-x-auto" role="region" aria-label="Invoice line items" tabindex="0"><table class="w-full border-collapse text-left"><thead><tr class="border-b-2 border-slate-300 text-sm"><th class="py-3 pr-3">Description</th><th class="px-3 py-3 text-right">Qty</th><th class="px-3 py-3 text-right">Rate</th><th class="py-3 pl-3 text-right">Amount</th></tr></thead><tbody>@foreach($invoice->lines->where('included',true) as $line)<tr class="border-b border-slate-200"><td class="py-4 pr-3">{{ $line->description }}</td><td class="px-3 py-4 text-right">{{ rtrim(rtrim(number_format($line->quantity_millis/1000,3,'.',''),'0'),'.') }} {{ $line->unit }}</td><td class="px-3 py-4 text-right">${{ number_format($line->unit_price_cents/100,2) }}</td><td class="py-4 pl-3 text-right font-semibold">${{ number_format($line->total_cents/100,2) }}</td></tr>@endforeach</tbody></table></div>
    <div class="ml-auto mt-6 max-w-sm"><dl class="space-y-2"><div class="flex justify-between"><dt>Subtotal</dt><dd>${{ number_format($invoice->subtotal_cents/100,2) }}</dd></div>@if($invoice->discount_total_cents)<div class="flex justify-between"><dt>Discount</dt><dd>−${{ number_format($invoice->discount_total_cents/100,2) }}</dd></div>@endif<div class="flex justify-between"><dt>Tax</dt><dd>${{ number_format($invoice->tax_total_cents/100,2) }}</dd></div><div class="flex justify-between border-t-2 border-slate-300 pt-3 text-2xl font-bold"><dt>Total</dt><dd>${{ number_format($invoice->total_cents/100,2) }}</dd></div></dl><p class="mt-3 text-right font-semibold">{{ $invoice->payment_terms==='due_on_receipt' ? 'Due on receipt' : 'Due '.$invoice->due_on?->format('M j, Y') }}</p></div>
    @if($invoice->customer_note)<section class="mt-8 rounded-lg border border-slate-200 p-4"><h2 class="font-bold">Note</h2><p class="mt-2 whitespace-pre-line">{{ $invoice->customer_note }}</p></section>@endif
    <section class="mt-8 border-t border-slate-200 pt-6"><h2 class="text-xl font-bold">Invoice acknowledgment</h2><p class="mt-2 text-sm text-slate-600">Confirm that the invoice was presented for review. This does not record payment.</p>@if($invoice->acknowledgments->isNotEmpty())<p class="mt-4 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900">Acknowledged by {{ $invoice->acknowledgments->first()->contact_name }} on <x-local-time :value="$invoice->acknowledgments->first()->acknowledged_at" :timezone="$activeOrganization->timezone" />.</p>@else<form method="POST" action="{{ route('invoices.acknowledge',$invoice) }}" class="mt-4" data-offline-write>@csrf<input type="hidden" name="acknowledgment_token" value="{{ Str::uuid() }}"><label class="form-label" for="contact_name">Point-of-contact name</label><input class="form-input" id="contact_name" name="contact_name" required><label class="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" name="confirmed" value="1" required> I confirm this invoice was presented for review.</label><button class="button-primary mt-3 w-full sm:w-auto">Record acknowledgment</button></form>@endif</section>
    <footer class="mt-8 flex flex-wrap gap-3 border-t border-slate-200 pt-5">
        <button type="button" class="button-secondary" onclick="window.print()">Print</button>
        @if ($invoice->pdf_status === 'ready')
            <a class="button-secondary" href="{{ route('invoices.pdf', $invoice) }}">Download PDF</a>
        @endif
        @if ($activeMembership->hasCapability('experience.office.access'))
            <a class="button-secondary" href="{{ route('office.invoices.show', $invoice) }}">Return to billing</a>
        @else
            <a class="button-secondary" href="{{ route('field.home') }}">Return to field</a>
        @endif
    </footer>
</main></body></html>
