<x-layouts.office title="Catalog categories" width="workspace">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-office.page-header title="Products & Services" description="Organize catalog records with one optional parent category level." eyebrow="Catalog">
        @if($activeMembership->hasCapability('catalog.manage'))
            <x-slot:actions><a class="button-primary" href="{{ route('office.catalog.categories.create') }}">Add category</a></x-slot:actions>
        @endif
    </x-office.page-header>
    <x-office.catalog-tabs />
    <form method="GET" class="office-filter-toolbar sm:grid-cols-[minmax(220px,1fr)_180px_auto]" aria-label="Category filters"><div><label class="form-label" for="q">Name or code</label><input class="form-input" id="q" name="q" type="search" value="{{ request('q') }}"></div><div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="flex gap-2"><button class="button-secondary">Filter</button>@if(request()->query())<a class="inline-flex min-h-11 items-center px-2 font-bold text-brand-blue underline" href="{{ route('office.catalog.categories.index') }}">Clear</a>@endif</div></form>
    <div class="office-table-wrap"><table class="office-data-table"><caption class="sr-only">Catalog categories</caption><thead><tr><th scope="col">Category</th><th scope="col">Parent</th><th scope="col">Services</th><th scope="col">Children</th><th scope="col">Status</th><th scope="col" class="text-right">Action</th></tr></thead><tbody>@forelse($categories as $category)<tr><td><p class="font-bold">{{ $category->name }}</p><p class="text-xs text-slate-500">{{ $category->code }}</p></td><td>{{ $category->parent?->name ?? 'Top level' }}</td><td>{{ $category->services_count }}</td><td>{{ $category->children_count }}</td><td><span class="{{ $category->active ? 'status-success' : 'status-muted' }}">{{ $category->active ? 'Active' : 'Inactive' }}</span></td><td class="text-right">@if($activeMembership->hasCapability('catalog.manage'))<a class="inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.catalog.categories.edit',$category) }}">Edit</a>@else<span class="text-sm text-slate-500">Read only</span>@endif</td></tr>@empty<tr><td colspan="6" class="py-10 text-center"><p class="font-bold">No categories found</p></td></tr>@endforelse</tbody></table></div>
    <div class="office-mobile-list">@forelse($categories as $category)<article class="office-mobile-card"><div class="flex justify-between gap-3"><div><h2 class="font-bold">{{ $category->name }}</h2><p class="text-xs text-slate-500">{{ $category->code }}</p></div><span class="{{ $category->active ? 'status-success' : 'status-muted' }}">{{ $category->active ? 'Active' : 'Inactive' }}</span></div><p class="mt-3 text-sm">{{ $category->services_count }} services · {{ $category->children_count }} children</p>@if($activeMembership->hasCapability('catalog.manage'))<a class="button-secondary mt-4 w-full" href="{{ route('office.catalog.categories.edit',$category) }}">Edit category</a>@endif</article>@empty<div class="surface p-8 text-center"><p class="font-bold">No categories found</p></div>@endforelse</div><div class="mt-5">{{ $categories->links() }}</div>
</x-layouts.office>
