<x-layouts.office :title="'Review '.$visit->serviceTicket->ticket_number">
    @php
        $activeMedia = $versions->flatMap->media->where('state','stored');
        $activeParts = $closeout->parts->whereNull('removed_at');
    @endphp
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-form-errors />
    <a href="{{ route('office.closeout-reviews.index') }}" class="inline-flex min-h-11 items-center text-sm font-bold text-brand-blue">← Review queue</a>
    <div class="mt-2 flex flex-wrap justify-between gap-4"><div><p class="font-bold text-brand-blue">{{ $visit->serviceTicket->ticket_number }} · Visit #{{ $visit->id }}</p><h1 class="mt-1 text-3xl font-bold">{{ $visit->serviceTicket->title }}</h1><p class="mt-2 text-slate-600">{{ $visit->serviceTicket->customer->display_name }} · {{ $visit->serviceLocation->name }}</p></div><div class="rounded-lg border border-orange-300 bg-orange-50 px-4 py-3"><p class="text-xs font-bold uppercase tracking-wide text-orange-800">Submitted outcome</p><p class="mt-1 font-bold text-orange-950">{{ ucfirst(str_replace('_',' ',$closeout->outcome)) }} · v{{ $closeout->version }}</p></div></div>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
        <div class="space-y-6">
            <section class="surface p-5"><h2 class="text-lg font-bold">Closeout narrative</h2><dl class="mt-4 grid gap-4 md:grid-cols-2">@foreach(['diagnosis'=>'Diagnosis','work_performed'=>'Work performed','exceptions'=>'Exceptions','recommendations'=>'Recommendations','return_reason'=>'Return reason','unfinished_work'=>'Unfinished work','needed_equipment'=>'Needed equipment','hold_reason'=>'Hold reason','unavailable_detail'=>'Unavailable detail'] as $field=>$label)@if(filled($closeout->$field))<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-sm text-slate-800">{{ $closeout->$field }}</dd></div>@endif @endforeach</dl></section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Acknowledgment and evidence</h2><p class="mt-3 text-sm"><strong>Acknowledgment:</strong> {{ $closeout->representative_name ?: ucfirst(str_replace('_',' ',$closeout->ack_unavailable_category ?? 'Not recorded')) }}</p><p class="mt-2 text-sm"><strong>Photos:</strong> {{ $activeMedia->count() }} active across {{ $versions->count() }} version(s)</p><div class="mt-3 flex flex-wrap gap-2">@foreach($activeMedia as $media)<a class="button-secondary" href="{{ route('field.media.show',$media) }}">{{ ucfirst(str_replace('_',' ',$media->category)) }} · v{{ $media->closeout->version ?? '?' }}</a>@endforeach</div></section>
                <section class="surface p-5"><h2 class="text-lg font-bold">Version comparison</h2><div class="mt-4 grid gap-4 {{ $versions->count()>1 ? 'lg:grid-cols-2' : '' }}">@foreach($versions as $version)<article class="rounded-lg border {{ $version->id===$closeout->id ? 'border-brand-blue' : 'border-slate-200' }} p-4"><div class="flex justify-between gap-3"><p class="font-bold">Version {{ $version->version }} · {{ ucfirst($version->status) }}</p><p class="text-xs text-slate-500">@if($version->submitted_at)<x-local-time :value="$version->submitted_at" :timezone="$visit->timezone" />@else Draft @endif</p></div><dl class="mt-3 space-y-2 text-sm"><div><dt class="font-bold text-slate-500">Diagnosis</dt><dd class="whitespace-pre-line">{{ $version->diagnosis ?: '—' }}</dd></div><div><dt class="font-bold text-slate-500">Work performed</dt><dd class="whitespace-pre-line">{{ $version->work_performed ?: '—' }}</dd></div><div><dt class="font-bold text-slate-500">Recommendations</dt><dd class="whitespace-pre-line">{{ $version->recommendations ?: '—' }}</dd></div></dl>@foreach($version->reviews as $review)<p class="mt-3 text-sm font-semibold {{ $review->decision==='returned' ? 'text-orange-800' : 'text-emerald-800' }}">{{ ucfirst($review->decision) }} by {{ $review->reviewer?->name ?? 'Former user' }}@if($review->self_review_override) · Super Admin self-review override@endif</p>@if($review->reason)<p class="mt-1 text-sm text-slate-700">{{ $review->reason }}</p>@endif @endforeach</article>@endforeach</div></section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Operational history</h2><div class="mt-4 space-y-3">@forelse($events as $event)<div><p class="text-sm font-semibold">{{ ucfirst(str_replace(['.','_'],' ',$event->event_type)) }}</p><p class="text-xs text-slate-500">{{ $event->actor?->name ?? 'System' }} · <x-local-time :value="$event->occurred_at" :timezone="$visit->timezone" format="M j, g:i A T" /></p></div>@empty<p class="text-sm text-slate-500">No history recorded.</p>@endforelse</div></section>
        </div>
        <aside class="space-y-6">
            <section class="surface p-5"><h2 class="font-bold">Crew time</h2><div class="mt-4 space-y-3">@forelse($visit->timeEntries as $entry)<div class="rounded-lg border border-slate-200 p-3"><p class="font-semibold">{{ $entry->user->name }} · {{ ucfirst(str_replace('_',' ',$entry->category)) }}</p><p class="mt-1 text-sm text-slate-600">{{ $entry->ended_at ? number_format($entry->started_at->diffInSeconds($entry->ended_at)/60,0).' minutes' : 'Stopped on submission' }}</p></div>@empty<p class="text-sm text-slate-500">No time recorded.</p>@endforelse</div></section>
            <section class="surface p-5"><h2 class="font-bold">Parts and equipment</h2><div class="mt-4 space-y-3">@forelse($activeParts as $part)<div class="rounded-lg border border-slate-200 p-3"><p class="font-semibold">{{ $part->description }}</p><p class="text-sm text-slate-600">{{ $part->quantity }} {{ $part->unit }} · {{ ucfirst(str_replace('_',' ',$part->billing_treatment)) }}</p></div>@empty<p class="text-sm text-slate-500">No proposals.</p>@endforelse</div></section>
            @if($activeMembership->hasCapability('closeouts.review') && !$closeout->reviews->count())
                <section class="surface p-5"><h2 class="font-bold">Approve closeout</h2><form method="POST" action="{{ route('office.closeout-reviews.approve',$closeout) }}" class="mt-4 space-y-4">@csrf<input type="hidden" name="decision_token" value="{{ Str::uuid() }}">
                    @if($closeout->outcome==='customer_unavailable')<div><label class="form-label" for="disposition">Required disposition</label><select class="form-input" id="disposition" name="disposition" required><option value="">Choose</option><option value="follow_up">Create planned follow-up</option><option value="hold">Place ticket on hold</option><option value="cancel">Cancel ticket</option></select></div><div><label class="form-label" for="disposition_reason">Disposition reason</label><textarea class="form-textarea" id="disposition_reason" name="disposition_reason" required></textarea></div>@endif
                    @if($visit->timeEntries->isNotEmpty())<details><summary class="min-h-11 cursor-pointer py-3 font-semibold text-brand-blue">Adjust crew time</summary><div class="space-y-4">@foreach($visit->timeEntries as $entry)<fieldset class="rounded-lg border border-slate-200 p-3"><legend class="px-1 text-sm font-bold">{{ $entry->user->name }} · {{ ucfirst($entry->category) }}</legend><label class="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" name="time_adjustments[{{ $entry->id }}][enabled]" value="1"><span>Apply adjustment</span></label><label class="form-label" for="time_minutes_{{ $entry->id }}">Approved minutes</label><input class="form-input" id="time_minutes_{{ $entry->id }}" type="number" min="0" name="time_adjustments[{{ $entry->id }}][approved_minutes]" value="{{ $entry->ended_at ? ceil($entry->started_at->diffInSeconds($entry->ended_at)/60) : 0 }}"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="time_adjustments[{{ $entry->id }}][excluded]" value="1"><span>Exclude entry</span></label><label class="form-label" for="time_reason_{{ $entry->id }}">Reason</label><textarea class="form-textarea" id="time_reason_{{ $entry->id }}" name="time_adjustments[{{ $entry->id }}][reason]"></textarea></fieldset>@endforeach</div></details>@endif
                    @if($activeParts->isNotEmpty())<details><summary class="min-h-11 cursor-pointer py-3 font-semibold text-brand-blue">Adjust proposals</summary><div class="space-y-4">@foreach($activeParts as $part)<fieldset class="rounded-lg border border-slate-200 p-3"><legend class="px-1 text-sm font-bold">{{ $part->description }}</legend><label class="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" name="part_adjustments[{{ $part->id }}][enabled]" value="1"><span>Apply adjustment</span></label><label class="form-label" for="part_qty_{{ $part->id }}">Approved quantity</label><input class="form-input" id="part_qty_{{ $part->id }}" type="number" step="0.01" min="0" name="part_adjustments[{{ $part->id }}][approved_quantity]" value="{{ $part->quantity }}"><label class="form-label" for="part_unit_{{ $part->id }}">Unit</label><input class="form-input" id="part_unit_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][approved_unit]" value="{{ $part->unit }}"><label class="form-label" for="part_treatment_{{ $part->id }}">Billing treatment</label><select class="form-input" id="part_treatment_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][approved_billing_treatment]">@foreach(config('field_execution.billing_treatments') as $key=>$label)<option value="{{ $key }}" @selected($part->billing_treatment===$key)>{{ $label }}</option>@endforeach</select><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="part_adjustments[{{ $part->id }}][excluded]" value="1"><span>Exclude proposal</span></label><label class="form-label" for="part_reason_{{ $part->id }}">Reason</label><textarea class="form-textarea" id="part_reason_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][reason]"></textarea></fieldset>@endforeach</div></details>@endif
                    <button class="button-primary w-full">Approve and apply disposition</button></form></section>
                <section class="surface border-orange-300 p-5"><h2 class="font-bold">Return for correction</h2><form method="POST" action="{{ route('office.closeout-reviews.return',$closeout) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="decision_token" value="{{ Str::uuid() }}"><label class="form-label" for="return_reason">Correction instructions</label><textarea class="form-textarea" id="return_reason" name="reason" required maxlength="5000"></textarea><button class="button-secondary w-full">Return to field</button></form></section>
            @endif
        </aside>
    </div>
</x-layouts.office>
