<x-layouts.office :title="'Review '.$visit->serviceTicket->ticket_number" width="detail">
    @php
        $activeParts = $closeout->parts->whereNull('removed_at');
    @endphp
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    <x-form-errors />
    <x-office.record-header :title="$visit->serviceTicket->title" :back-href="route('office.closeout-reviews.index')" back-label="Review queue" :description="$visit->serviceTicket->ticket_number.' · '.$visit->displayLabel().' · '.$visit->serviceTicket->customer->display_name.' · '.$visit->serviceLocation->name">
        <x-slot:badges><span class="status-priority">{{ ucfirst(str_replace('_',' ',$closeout->outcome)) }}</span><span class="status-muted">Version {{ $closeout->version }}</span></x-slot:badges>
    </x-office.record-header>

    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
        <div class="space-y-6">
            @if($administrativeReview = $closeout->reviews->firstWhere('administrative_completion', true))<section class="surface border-orange-300 bg-orange-50 p-5"><h2 class="font-bold text-orange-950">Administratively completed</h2><p class="mt-2 text-sm text-orange-900">Completed and self-reviewed by {{ $administrativeReview->reviewer?->name ?? 'Super Admin' }} at <x-local-time :value="$administrativeReview->administratively_completed_at" :timezone="$visit->timezone" />.</p><p class="mt-2 whitespace-pre-line text-sm text-orange-950">{{ $administrativeReview->administrative_completion_reason }}</p></section>@endif
            <section class="surface p-5"><h2 class="text-lg font-bold">Closeout narrative</h2><dl class="mt-4 grid gap-4 md:grid-cols-2">@foreach(['diagnosis'=>'Diagnosis','work_performed'=>'Work performed','result_summary'=>'Result / Findings','exceptions'=>'Exceptions','recommendations'=>'Recommendations','return_reason'=>'Return reason','unfinished_work'=>'Unfinished work','needed_equipment'=>'Needed equipment','hold_reason'=>'Hold reason','unavailable_detail'=>'Unavailable detail'] as $field=>$label)@if(filled($closeout->$field))<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line text-sm text-slate-800">{{ $closeout->$field }}</dd></div>@endif @endforeach</dl></section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Work Items handled this Visit</h2><div class="mt-4 space-y-3">@forelse($visit->workItems as $workItem)<article class="rounded-lg border border-slate-200 p-4"><div class="flex flex-wrap justify-between gap-2"><h3 class="break-words font-bold">{{ $workItem->title }}</h3><span class="status-active">{{ Str::headline($workItem->status) }}</span></div><p class="mt-1 text-xs font-semibold text-slate-500">{{ $workItem->origin === 'field_discovered' ? 'Field discovered' : 'Office added' }}</p>@if($workItem->detail)<p class="mt-3 whitespace-pre-line break-words text-sm">{{ $workItem->detail }}</p>@endif @if($workItem->work_note)<p class="mt-3 whitespace-pre-line break-words rounded-lg bg-slate-50 p-3 text-sm"><strong>Work note:</strong> {{ $workItem->work_note }}</p>@endif @if($workItem->followUpServiceTicket)<a class="mt-3 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.service-tickets.show', $workItem->followUpServiceTicket) }}">Transferred to {{ $workItem->followUpServiceTicket->ticket_number }}</a>@endif</article>@empty<p class="text-sm text-slate-500">No additional Work Items were handled during this Visit.</p>@endforelse</div></section>
            <section class="surface p-5">
                <h2 class="text-lg font-bold">Acknowledgment and evidence</h2>
                @if($signature = $closeout->acknowledgmentSignature)
                    <div class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="font-bold text-slate-950">Signed on-site</p><p class="mt-1 text-sm">{{ $signature->signer_name }}@if($signature->signer_role) · {{ $signature->signer_role }}@endif · <x-local-time :value="$signature->signed_at" :timezone="$visit->timezone" /></p><p class="mt-3 text-xs text-slate-600">Acknowledgment statement {{ $signature->statement_version }}</p><a class="mt-3 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('closeout-acknowledgment-signatures.show', $signature) }}" target="_blank" rel="noopener">View signature evidence</a></div>
                @elseif($closeout->ack_unavailable_category)
                    <div class="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p class="font-bold text-amber-950">Acknowledgment fallback</p><p class="mt-1 text-sm text-amber-950">{{ config('field_execution.ack_fallbacks.'.$closeout->ack_unavailable_category, ucfirst(str_replace('_', ' ', $closeout->ack_unavailable_category))) }}</p><p class="mt-2 whitespace-pre-line text-sm text-amber-950">{{ $closeout->ack_unavailable_detail }}</p></div>
                @else
                    <p class="mt-3 text-sm"><strong>Acknowledgment:</strong> {{ $closeout->representative_name ?: 'Not recorded' }}</p>
                @endif
                @include('office.closeout-reviews._photo-gallery')
            </section>
                <section class="surface p-5"><h2 class="text-lg font-bold">Version comparison</h2><div class="mt-4 grid gap-4 {{ $versions->count()>1 ? 'lg:grid-cols-2' : '' }}">@foreach($versions as $version)<article class="rounded-lg border {{ $version->id===$closeout->id ? 'border-brand-blue' : 'border-slate-200' }} p-4"><div class="flex justify-between gap-3"><p class="font-bold">Version {{ $version->version }} · {{ ucfirst($version->status) }}</p><p class="text-xs text-slate-500">@if($version->submitted_at) <x-local-time :value="$version->submitted_at" :timezone="$visit->timezone" /> @else Draft @endif</p></div><dl class="mt-3 space-y-2 text-sm"><div><dt class="font-bold text-slate-500">Diagnosis</dt><dd class="whitespace-pre-line">{{ $version->diagnosis ?: '—' }}</dd></div><div><dt class="font-bold text-slate-500">Work performed</dt><dd class="whitespace-pre-line">{{ $version->work_performed ?: '—' }}</dd></div><div><dt class="font-bold text-slate-500">Recommendations</dt><dd class="whitespace-pre-line">{{ $version->recommendations ?: '—' }}</dd></div></dl>@foreach($version->reviews as $review)<p class="mt-3 text-sm font-semibold {{ $review->decision==='returned' ? 'text-orange-800' : 'text-emerald-800' }}">{{ ucfirst($review->decision) }} by {{ $review->reviewer?->name ?? 'Former user' }}@if($review->self_review_override) · Super Admin self-review override @endif</p>@if($review->reason)<p class="mt-1 text-sm text-slate-700">{{ $review->reason }}</p>@endif @endforeach</article>@endforeach</div></section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Operational history</h2><div class="mt-4 space-y-3">@forelse($events as $event)<div><p class="text-sm font-semibold">{{ ucfirst(str_replace(['.','_'],' ',$event->event_type)) }}</p><p class="text-xs text-slate-500">{{ $event->actor?->name ?? 'System' }} · <x-local-time :value="$event->occurred_at" :timezone="$visit->timezone" format="M j, g:i A T" /></p></div>@empty<p class="text-sm text-slate-500">No history recorded.</p>@endforelse</div></section>
        </div>
        <aside class="space-y-6">
            <section class="surface p-5"><h2 class="font-bold">Crew time</h2><p class="mt-2 text-sm text-slate-600">Allocation explains what recorded time was spent on. Approved-minute adjustment separately controls review and billing treatment.</p><div class="mt-4 space-y-3">@forelse($visit->timeEntries->sortBy('effective_started_at') as $entry)<div class="rounded-lg border border-slate-200 p-3"><p class="font-semibold">{{ $entry->user->name }} · {{ ucfirst(str_replace('_',' ',$entry->category)) }} @if($entry->hasSubmittedCorrection())<span class="status-active ml-2">Corrected</span>@endif</p><p class="mt-1 text-sm text-slate-600">@if($entry->effective_ended_at)<x-local-time :value="$entry->effective_started_at" :timezone="$visit->timezone" format="M j, g:i A T" />–<x-local-time :value="$entry->effective_ended_at" :timezone="$visit->timezone" format="M j, g:i A T" /> · {{ number_format($entry->effectiveDurationSeconds()/60,0) }} minutes @else Stopped on submission @endif</p>@include('office.service-tickets._submitted-time-correction', ['context' => 'review', 'reviewCloseoutId' => $closeout->id])@include('office.service-tickets._work-time-allocation', ['context' => 'review', 'reviewCloseoutId' => $closeout->id])</div>@empty<p class="text-sm text-slate-500">No time recorded.</p>@endforelse</div></section>
            <section class="surface p-5"><h2 class="font-bold">Catalog items, parts, and equipment</h2><div class="mt-4 space-y-3">@forelse($activeParts as $part)<div class="rounded-lg border border-slate-200 p-3"><p class="font-semibold">{{ $part->catalog_name_snapshot ?: $part->description }} @if($part->catalog_item_type)<span class="ml-2 status-active">Catalog {{ ucfirst($part->catalog_item_type) }}</span>@endif</p><p class="text-sm text-slate-600">{{ $part->catalog_quantity_millis ? rtrim(rtrim(number_format($part->catalog_quantity_millis/1000,3,'.',''),'0'),'.') : $part->quantity }} {{ $part->unit }} · {{ ucfirst(str_replace('_',' ',$part->billing_treatment)) }}</p></div>@empty<p class="text-sm text-slate-500">No proposals.</p>@endforelse</div></section>
            @if($activeMembership->hasCapability('closeouts.review') && !$closeout->reviews->count())
                <section class="surface p-5">
                    <h2 class="font-bold">Ticket completion</h2>
                    @if($closeout->outcome === 'resolved' && $completionBlockingVisits->isEmpty() && $outstandingWorkItems->isEmpty())
                        <div class="mt-3 rounded-lg border border-emerald-300 bg-emerald-50 p-4 text-emerald-950">
                            <p class="font-bold">This is the final resolved visit.</p>
                            <p class="mt-1 text-sm">Approving this closeout will complete {{ $visit->serviceTicket->ticket_number }} and create its ready billing handoff.</p>
                        </div>
                    @elseif($closeout->outcome === 'resolved')
                        <div class="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-4 text-amber-950">
                            <p class="font-bold">Approval will not close the Service Ticket yet.</p>
                            @if($completionBlockingVisits->isNotEmpty())<p class="mt-1 text-sm">The following visit(s) still need to be completed, approved, or canceled:</p>
                            <ul class="mt-3 space-y-2 text-sm">
                                @foreach($completionBlockingVisits as $blockingVisit)
                                    <li class="flex min-h-11 items-center justify-between gap-3 rounded-lg border border-amber-200 bg-white px-3">
                                        <span class="font-semibold">{{ $blockingVisit->displayLabel() }}</span>
                                        <span>{{ ucfirst(str_replace('_', ' ', $blockingVisit->status)) }}</span>
                                    </li>
                                @endforeach
                            </ul>@endif
                            @if($outstandingWorkItems->isNotEmpty())<p class="mt-4 text-sm font-bold">Outstanding Work Items:</p><ul class="mt-2 space-y-2 text-sm">@foreach($outstandingWorkItems as $workItem)<li class="rounded-lg border border-amber-200 bg-white px-3 py-3"><span class="font-semibold">{{ $workItem->title }}</span> — {{ Str::headline($workItem->status) }}</li>@endforeach</ul>@endif
                            <a class="mt-3 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.service-tickets.show', $visit->serviceTicket) }}">Open the complete visit history</a>
                        </div>
                    @elseif($closeout->outcome === 'needs_return_trip')
                        <div class="mt-3 rounded-lg border border-blue-200 bg-blue-50 p-4 text-blue-950">
                            <p class="font-bold">This Service Ticket will remain open.</p>
                            <p class="mt-1 text-sm">Approving this visit retains {{ $closeout->returnVisit?->displayLabel() ?? 'the planned return visit' }}.</p>
                        </div>
                    @else
                        <p class="mt-3 text-sm text-slate-600">Approving this outcome applies its disposition but does not complete the Service Ticket.</p>
                    @endif
                </section>
                <section class="surface p-5"><h2 class="font-bold">Approve closeout</h2><form method="POST" action="{{ route('office.closeout-reviews.approve',$closeout) }}" class="mt-4 space-y-4">@csrf<input type="hidden" name="decision_token" value="{{ Str::uuid() }}">
                    @if($closeout->outcome==='customer_unavailable')<div><label class="form-label" for="disposition">Required disposition</label><select class="form-input" id="disposition" name="disposition" required><option value="">Choose</option><option value="follow_up">Create planned follow-up</option><option value="hold">Place ticket on hold</option><option value="cancel">Cancel ticket</option></select></div><div><label class="form-label" for="disposition_reason">Disposition reason</label><textarea class="form-textarea" id="disposition_reason" name="disposition_reason" required></textarea></div>@endif
                    <section class="rounded-lg border border-slate-200 bg-slate-50 p-4" aria-labelledby="travel-charge-heading">
                        <h3 id="travel-charge-heading" class="text-xs font-bold uppercase tracking-wide text-slate-600">Travel</h3>
                        <p class="mt-2 text-sm text-slate-700">Recorded en-route travel: <strong>{{ $tripChargeRecommendation->travelSeconds < 3600 ? intdiv($tripChargeRecommendation->travelSeconds, 60).' minutes' : intdiv($tripChargeRecommendation->travelSeconds, 3600).' hr '.intdiv($tripChargeRecommendation->travelSeconds % 3600, 60).' min' }}</strong></p>
                        @if($tripChargeRecommendation->isRecommended())
                            <input type="hidden" name="trip_charge_selected" value="0">
                            <label class="mt-3 flex min-h-11 cursor-pointer items-center gap-3 rounded-lg border border-blue-200 bg-white px-3 py-2 focus-within:ring-2 focus-within:ring-brand-blue focus-within:ring-offset-2" for="trip_charge_selected">
                                <input id="trip_charge_selected" type="checkbox" name="trip_charge_selected" value="1" @checked((bool) old('trip_charge_selected', $tripChargeRecommendation->selectedByDefault))>
                                <span class="min-w-0 flex-1">
                                    <span class="block font-bold text-slate-950">Add {{ $tripChargeRecommendation->service->name }} — {{ $tripChargeRecommendation->variant->customer_label ?: $tripChargeRecommendation->variant->label }}</span>
                                    <span class="block text-sm text-slate-600">Recommended from this Visit's recorded en-route travel. Review before approval.</span>
                                </span>
                                <span class="font-bold text-slate-950">${{ number_format($tripChargeRecommendation->priceCents / 100, 2) }}</span>
                            </label>
                        @else
                            <p class="mt-2 text-sm font-semibold text-slate-600">No standard trip charge recommended.</p>
                        @endif
                    </section>
                    @if($visit->timeEntries->isNotEmpty())<details><summary class="min-h-11 cursor-pointer py-3 font-semibold text-brand-blue">Adjust crew time</summary><div class="space-y-4">@foreach($visit->timeEntries as $entry)<fieldset class="rounded-lg border border-slate-200 p-3"><legend class="px-1 text-sm font-bold">{{ $entry->user->name }} · {{ ucfirst($entry->category) }}</legend><label class="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" name="time_adjustments[{{ $entry->id }}][enabled]" value="1"><span>Apply adjustment</span></label><label class="form-label" for="time_minutes_{{ $entry->id }}">Approved minutes</label><input class="form-input" id="time_minutes_{{ $entry->id }}" type="number" min="0" name="time_adjustments[{{ $entry->id }}][approved_minutes]" value="{{ $entry->effective_ended_at ? ceil($entry->effectiveDurationSeconds()/60) : 0 }}"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="time_adjustments[{{ $entry->id }}][excluded]" value="1"><span>Exclude entry</span></label><label class="form-label" for="time_reason_{{ $entry->id }}">Reason</label><textarea class="form-textarea" id="time_reason_{{ $entry->id }}" name="time_adjustments[{{ $entry->id }}][reason]"></textarea></fieldset>@endforeach</div></details>@endif
                    @if($activeParts->isNotEmpty())<details><summary class="min-h-11 cursor-pointer py-3 font-semibold text-brand-blue">Adjust proposals</summary><div class="space-y-4">@foreach($activeParts as $part)<fieldset class="rounded-lg border border-slate-200 p-3"><legend class="px-1 text-sm font-bold">{{ $part->description }}</legend><label class="mt-2 flex min-h-11 items-center gap-2"><input type="checkbox" name="part_adjustments[{{ $part->id }}][enabled]" value="1"><span>Apply adjustment</span></label><label class="form-label" for="part_qty_{{ $part->id }}">Approved quantity</label><input class="form-input" id="part_qty_{{ $part->id }}" type="number" step="0.01" min="0" name="part_adjustments[{{ $part->id }}][approved_quantity]" value="{{ $part->quantity }}"><label class="form-label" for="part_unit_{{ $part->id }}">Unit</label><input class="form-input" id="part_unit_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][approved_unit]" value="{{ $part->unit }}"><label class="form-label" for="part_treatment_{{ $part->id }}">Billing treatment</label><select class="form-input" id="part_treatment_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][approved_billing_treatment]">@foreach(config('field_execution.billing_treatments') as $key=>$label)<option value="{{ $key }}" @selected($part->billing_treatment===$key)>{{ $label }}</option>@endforeach</select><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="part_adjustments[{{ $part->id }}][excluded]" value="1"><span>Exclude proposal</span></label><label class="form-label" for="part_reason_{{ $part->id }}">Reason</label><textarea class="form-textarea" id="part_reason_{{ $part->id }}" name="part_adjustments[{{ $part->id }}][reason]"></textarea></fieldset>@endforeach</div></details>@endif
                    <button class="button-primary w-full">{{ $closeout->outcome === 'resolved' && $completionBlockingVisits->isEmpty() && $outstandingWorkItems->isEmpty() ? 'Approve closeout & complete Service Ticket' : 'Approve closeout' }}</button></form></section>
                <section class="surface border-orange-300 p-5"><h2 class="font-bold">Return for correction</h2><form method="POST" action="{{ route('office.closeout-reviews.return',$closeout) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="decision_token" value="{{ Str::uuid() }}"><label class="form-label" for="return_reason">Correction instructions</label><textarea class="form-textarea" id="return_reason" name="reason" required maxlength="5000"></textarea><button class="button-secondary w-full">Return to field</button></form></section>
            @endif
        </aside>
    </div>
</x-layouts.office>
