@php
    $manualTimeSeconds = $visit->timeEntries->sum(fn ($entry) => $entry->ended_at ? $entry->started_at->diffInSeconds($entry->ended_at) : 0);
    $manualMedia = $closeout->media->where('state', 'stored');
    $manualParts = $closeout->parts->whereNull('removed_at');
    $manualRequested = request()->integer('manual_closeout_visit') === $visit->id;
@endphp
<dialog id="manual-closeout-visit-{{ $visit->id }}" data-manual-closeout-dialog data-visit-id="{{ $visit->id }}" aria-labelledby="manual-closeout-title-{{ $visit->id }}" class="m-0 h-dvh w-dvw max-h-none max-w-none bg-canvas p-0 text-ink sm:m-auto sm:h-[92dvh] sm:w-[96vw] sm:rounded-xl sm:border sm:border-slate-300">
    <div class="flex h-full min-h-0 flex-col">
        <header class="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-slate-200 bg-white p-4 sm:p-5">
            <div><p class="text-sm font-bold text-brand-blue">{{ $ticket->ticket_number }} · Visit #{{ $visit->id }}</p><h2 id="manual-closeout-title-{{ $visit->id }}" class="mt-1 text-xl font-bold text-slate-950">Administrative closeout</h2><p class="mt-1 text-sm text-slate-600">Resolved outcome · {{ ucfirst(str_replace('_', ' ', $visit->status)) }}</p></div>
            <button type="button" class="button-secondary min-w-11 px-3" data-manual-closeout-close aria-label="Close administrative closeout">Close</button>
        </header>
        <div class="min-h-0 flex-1 overflow-y-auto p-4 pb-[calc(2rem+env(safe-area-inset-bottom))] sm:p-6">
            <div data-manual-closeout-status tabindex="-1" aria-live="polite">@if($manualRequested)@if(session('status'))<div class="mb-4 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif<x-form-errors />@endif</div>
            <div class="mb-5 rounded-lg border border-orange-300 bg-orange-50 p-4 text-sm text-orange-950"><p class="font-bold">Super Admin override</p><p class="mt-1">Completing this form submits and self-approves the selected Visit, completes the Service Ticket, and creates its ready billing handoff. The action is immutable and audited.</p></div>
            <div class="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]">
                <form method="POST" action="{{ route('office.visits.manual-closeout.complete', $visit) }}" class="space-y-6" data-dirty-form data-manual-closeout-form>
                    @csrf
                    <input type="hidden" name="content_version" value="{{ $closeout->content_version }}">
                    <input type="hidden" name="completion_token" value="{{ old('completion_token', (string) Str::uuid()) }}">
                    <section class="surface p-5"><h3 class="font-bold">Work summary</h3><p class="mt-1 text-sm text-slate-600">Record what was found and completed. Manual completion is locked to Resolved.</p><div class="mt-4 space-y-4">
                        <div><label class="form-label" for="manual_diagnosis_{{ $visit->id }}">Diagnosis</label><textarea class="form-textarea @error('diagnosis') border-red-500 @enderror" id="manual_diagnosis_{{ $visit->id }}" name="diagnosis" required @error('diagnosis') aria-invalid="true" aria-describedby="diagnosis-error" @enderror>{{ old('diagnosis', $closeout->diagnosis) }}</textarea><x-field-error field="diagnosis" /></div>
                        <div><label class="form-label" for="manual_work_{{ $visit->id }}">Work performed</label><textarea class="form-textarea @error('work_performed') border-red-500 @enderror" id="manual_work_{{ $visit->id }}" name="work_performed" required @error('work_performed') aria-invalid="true" aria-describedby="work_performed-error" @enderror>{{ old('work_performed', $closeout->work_performed) }}</textarea><x-field-error field="work_performed" /></div>
                        <div><label class="form-label" for="manual_exceptions_{{ $visit->id }}">Exceptions</label><textarea class="form-textarea" id="manual_exceptions_{{ $visit->id }}" name="exceptions">{{ old('exceptions', $closeout->exceptions) }}</textarea></div>
                        <div><label class="form-label" for="manual_recommendations_{{ $visit->id }}">Recommendations</label><textarea class="form-textarea" id="manual_recommendations_{{ $visit->id }}" name="recommendations">{{ old('recommendations', $closeout->recommendations) }}</textarea></div>
                    </div></section>
                    <section class="surface p-5"><h3 class="font-bold">Customer acknowledgment</h3><p class="mt-1 text-sm text-slate-600">Enter the customer or point-of-contact name, or complete both fallback fields.</p><div class="mt-4 space-y-4">
                        <div><label class="form-label" for="manual_contact_{{ $visit->id }}">Customer or point-of-contact name</label><input class="form-input" id="manual_contact_{{ $visit->id }}" name="representative_name" value="{{ old('representative_name', $closeout->representative_name) }}"></div>
                        <div class="border-t border-slate-200 pt-4"><label class="form-label" for="manual_ack_category_{{ $visit->id }}">Acknowledgment fallback category</label><select class="form-input @error('ack_unavailable_category') border-red-500 @enderror" id="manual_ack_category_{{ $visit->id }}" name="ack_unavailable_category" @error('ack_unavailable_category') aria-invalid="true" aria-describedby="ack_unavailable_category-error" @enderror><option value="">Select only when acknowledgment is unavailable</option>@foreach(config('field_execution.ack_fallbacks') as $value => $label)<option value="{{ $value }}" @selected(old('ack_unavailable_category', $closeout->ack_unavailable_category) === $value)>{{ $label }}</option>@endforeach</select><x-field-error field="ack_unavailable_category" /></div>
                        <div><label class="form-label" for="manual_ack_detail_{{ $visit->id }}">Acknowledgment fallback details</label><textarea class="form-textarea @error('ack_unavailable_detail') border-red-500 @enderror" id="manual_ack_detail_{{ $visit->id }}" name="ack_unavailable_detail" @error('ack_unavailable_detail') aria-invalid="true" aria-describedby="ack_unavailable_detail-error" @enderror>{{ old('ack_unavailable_detail', $closeout->ack_unavailable_detail) }}</textarea><x-field-error field="ack_unavailable_detail" /></div>
                        <label class="flex min-h-11 gap-3 rounded-lg border border-slate-300 p-3 @error('acknowledgment_confirmed') border-red-500 bg-red-50 @enderror"><input type="checkbox" name="acknowledgment_confirmed" value="1" @checked(old('acknowledgment_confirmed'))><span class="text-sm font-semibold">I confirm the work and outcome were reviewed with the customer or point of contact named above.</span></label><x-field-error field="acknowledgment_confirmed" />
                    </div></section>
                    <section class="surface p-5"><h3 class="font-bold">Photo evidence fallback</h3><p class="mt-1 text-sm text-slate-600">Upload at least one active categorized photo, or complete both no-photo fields.</p><div class="mt-4 space-y-4"><div><label class="form-label" for="manual_no_photo_{{ $visit->id }}">No-photo category</label><select class="form-input @error('no_photo_category') border-red-500 @enderror" id="manual_no_photo_{{ $visit->id }}" name="no_photo_category" @error('no_photo_category') aria-invalid="true" aria-describedby="no_photo_category-error" @enderror><option value="">Select only when no photo is available</option>@foreach(config('field_execution.no_photo_reasons') as $value => $label)<option value="{{ $value }}" @selected(old('no_photo_category', $closeout->no_photo_category) === $value)>{{ $label }}</option>@endforeach</select><x-field-error field="no_photo_category" /></div><div><label class="form-label" for="manual_no_photo_detail_{{ $visit->id }}">No-photo details</label><textarea class="form-textarea @error('no_photo_detail') border-red-500 @enderror" id="manual_no_photo_detail_{{ $visit->id }}" name="no_photo_detail" @error('no_photo_detail') aria-invalid="true" aria-describedby="no_photo_detail-error" @enderror>{{ old('no_photo_detail', $closeout->no_photo_detail) }}</textarea><x-field-error field="no_photo_detail" /></div></div></section>
                    <section class="surface p-5"><h3 class="font-bold">Administrative completion</h3><div class="mt-4 space-y-4"><div><label class="form-label" for="manual_reason_{{ $visit->id }}">Administrative completion reason</label><textarea class="form-textarea @error('administrative_completion_reason') border-red-500 @enderror" id="manual_reason_{{ $visit->id }}" name="administrative_completion_reason" required>{{ old('administrative_completion_reason') }}</textarea><x-field-error field="administrative_completion_reason" /></div><label class="flex min-h-11 gap-3 rounded-lg border border-orange-300 bg-orange-50 p-3"><input type="checkbox" name="confirm_administrative_completion" value="1" required @checked(old('confirm_administrative_completion'))><span class="text-sm font-semibold">I understand this action submits and approves the Visit, completes the Service Ticket, and creates its billing handoff.</span></label><div class="grid gap-3 sm:grid-cols-2"><button class="button-secondary w-full" formaction="{{ route('office.visits.manual-closeout.save', $visit) }}" formnovalidate>Save draft</button><button class="button-primary w-full">Submit, approve, and complete ticket</button></div></div></section>
                </form>
                <aside class="space-y-5">
                    <section class="surface p-5"><h3 class="font-bold">Visit and time</h3><p class="mt-3 font-semibold">{{ $ticket->customer->display_name }} · {{ $ticket->serviceLocation->name }}</p><p class="mt-2 text-sm text-slate-600">{{ $visit->timezone }} · {{ number_format($manualTimeSeconds / 3600, 2) }} crew hours</p><div class="mt-3 space-y-2">@forelse($visit->timeEntries->sortBy('started_at') as $entry)<p class="text-sm"><strong>{{ $entry->user->name }}</strong> · {{ ucfirst(str_replace('_', ' ', $entry->category)) }} · @if($entry->ended_at){{ number_format($entry->started_at->diffInSeconds($entry->ended_at) / 3600, 2) }}h @else<span class="text-red-700">Running</span>@endif</p>@empty<p class="text-sm text-slate-500">No completed time entries.</p>@endforelse</div></section>
                    <section class="surface p-5"><h3 class="font-bold">Private photos</h3><div class="mt-3 space-y-3">@foreach($manualMedia as $media)<div class="flex items-center justify-between gap-3"><a class="font-bold text-brand-blue" href="{{ route('office.manual-closeout.media.show', $media) }}">{{ ucfirst(str_replace('_', ' ', $media->category)) }}</a><form method="POST" action="{{ route('office.visits.manual-closeout.media.remove', [$visit, $media]) }}">@csrf @method('DELETE')<button class="button-secondary">Remove</button></form></div>@endforeach</div><form method="POST" action="{{ route('office.visits.manual-closeout.media.store', $visit) }}" enctype="multipart/form-data" class="mt-4 space-y-3" data-upload-form>@csrf<label class="form-label" for="manual_photo_{{ $visit->id }}">Photo</label><input class="form-input" id="manual_photo_{{ $visit->id }}" type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required><label class="form-label" for="manual_photo_category_{{ $visit->id }}">Category</label><select class="form-input" id="manual_photo_category_{{ $visit->id }}" name="category">@foreach(config('field_execution.photo_categories') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><label class="form-label" for="manual_photo_caption_{{ $visit->id }}">Caption</label><input class="form-input" id="manual_photo_caption_{{ $visit->id }}" name="caption"><button class="button-secondary w-full">Upload photo</button><progress class="w-full" max="100" hidden></progress><p class="text-sm text-slate-600" data-upload-status aria-live="polite"></p></form></section>
                    <section class="surface p-5"><h3 class="font-bold">Parts and equipment</h3>@foreach($manualParts as $part)<div class="mt-3 border-t border-slate-200 pt-3"><p class="font-semibold">{{ $part->description }} · {{ $part->quantity }} {{ $part->unit }}</p><p class="text-sm text-slate-600">{{ ucfirst(str_replace('_', ' ', $part->billing_treatment)) }}</p><form method="POST" action="{{ route('office.visits.manual-closeout.parts.remove', [$visit, $part]) }}" class="mt-2">@csrf @method('DELETE')<button class="button-secondary">Remove</button></form></div>@endforeach<form method="POST" action="{{ route('office.visits.manual-closeout.parts.store', $visit) }}" class="mt-4 space-y-3">@csrf<label class="form-label" for="manual_part_{{ $visit->id }}">Description</label><input class="form-input" id="manual_part_{{ $visit->id }}" name="description" required><label class="form-label" for="manual_quantity_{{ $visit->id }}">Quantity</label><input class="form-input" id="manual_quantity_{{ $visit->id }}" type="number" step=".01" name="quantity" required><label class="form-label" for="manual_unit_{{ $visit->id }}">Unit</label><input class="form-input" id="manual_unit_{{ $visit->id }}" name="unit"><label class="form-label" for="manual_serial_{{ $visit->id }}">Serial / MAC</label><input class="form-input" id="manual_serial_{{ $visit->id }}" name="serial_mac"><label class="form-label" for="manual_billing_{{ $visit->id }}">Billing treatment</label><select class="form-input" id="manual_billing_{{ $visit->id }}" name="billing_treatment">@foreach(config('field_execution.billing_treatments') as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><label class="form-label" for="manual_part_note_{{ $visit->id }}">Technician note</label><textarea class="form-textarea" id="manual_part_note_{{ $visit->id }}" name="technician_note"></textarea><button class="button-secondary w-full">Add proposal</button></form></section>
                </aside>
            </div>
        </div>
    </div>
</dialog>
