<x-layouts.office :title="$ticket->ticket_number">
    @if(session('status'))<div class="mb-5 rounded-lg border border-emerald-300 bg-emerald-50 p-4 font-semibold text-emerald-900" role="status">{{ session('status') }}</div>@endif
    @if($errors->any() && !request()->filled('execution_visit'))<x-form-errors />@endif
    <a href="{{ route('office.service-tickets.index') }}" class="inline-flex min-h-11 items-center text-sm font-bold text-brand-blue">← Service Tickets</a>
    <div class="mt-2 flex flex-wrap items-start justify-between gap-4">
        <div><p class="font-bold text-brand-blue">{{ $ticket->ticket_number }}</p><h1 class="mt-1 text-3xl font-bold text-slate-950">{{ $ticket->title }}</h1><p class="mt-2 text-sm text-slate-500">{{ ucfirst($ticket->priority) }} priority · {{ ucfirst(str_replace('_',' ',$ticket->status)) }}</p></div>
        @if($activeMembership->hasCapability('dispatch.manage'))<div class="flex flex-wrap gap-2"><a href="{{ route('office.service-tickets.edit', $ticket) }}" class="button-secondary">Edit ticket</a>@if($ticket->status !== 'canceled')<a href="{{ route('office.service-tickets.visits.create', $ticket) }}" class="button-primary">Add visit</a>@endif</div>@endif
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]">
        <div class="space-y-6">
            <section class="surface p-5"><h2 class="text-lg font-bold">Customer & location</h2><p class="mt-3 font-bold">{{ $ticket->customer->display_name }}</p><a class="mt-1 inline-flex min-h-11 items-center text-sm font-bold text-brand-blue" href="{{ route('office.locations.show', $ticket->serviceLocation) }}">{{ $ticket->serviceLocation->name }} · {{ $ticket->serviceLocation->formattedAddress() }}</a>@if($ticket->contact)<p class="mt-2 text-sm text-slate-600">Contact: {{ $ticket->contact->name }} @if($ticket->contact->phone)· {{ $ticket->contact->phone }}@endif</p>@endif</section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Work scope</h2><p class="mt-3 whitespace-pre-line text-slate-700">{{ $ticket->description ?: 'No work scope recorded.' }}</p>@if($ticket->customer_visible_summary)<h3 class="mt-5 text-sm font-bold uppercase tracking-[.1em] text-slate-500">Customer-visible summary</h3><p class="mt-2 whitespace-pre-line text-slate-700">{{ $ticket->customer_visible_summary }}</p>@endif</section>
            <section class="surface overflow-hidden">
                <div class="flex items-center justify-between border-b border-slate-200 p-5"><h2 class="text-lg font-bold">Visits</h2></div>
                @forelse($ticket->visits as $visit)
                    <div class="border-b border-slate-200 p-5 last:border-0">
                        <div class="flex flex-wrap justify-between gap-3"><div><p class="font-bold">Visit #{{ $visit->id }} @if($visit->return_of_visit_id)<span class="text-brand-orange">· Return of #{{ $visit->return_of_visit_id }}</span>@endif</p><p class="mt-1 text-sm text-slate-600">{{ ucfirst(str_replace('_',' ',$visit->status)) }} · {{ $visit->scheduledStartLocal()?->format('M j, Y g:i A T') ?? 'Unscheduled' }}@if($visit->scheduledEndLocal()) – {{ $visit->scheduledEndLocal()->format('g:i A T') }}@endif</p><p class="mt-1 text-sm text-slate-500">{{ $visit->assignments->map(fn($a) => ($a->is_lead ? 'Lead: ' : '').$a->membership->user->name)->join(', ') ?: 'No crew assigned' }}</p></div><div class="flex flex-wrap gap-2">@can('execute', $visit)<button type="button" class="button-primary" data-dialog-open="execution-visit-{{ $visit->id }}">Open execution</button>@endcan @if($activeMembership->hasCapability('dispatch.manage') && !in_array($visit->status,['en_route','on_site','canceled']))<a class="button-secondary" href="{{ route('office.visits.edit', $visit) }}">Schedule / assign</a>@endif</div></div>
                        @if($activeMembership->hasCapability('dispatch.manage') && !in_array($visit->status, ['canceled', 'pending_closeout', 'customer_unavailable'], true))
                            <div class="mt-4 grid gap-3 md:grid-cols-2">
                                <form method="POST" action="{{ route('office.visits.cancel', $visit) }}" class="space-y-2">@csrf<div class="flex gap-2"><input class="form-input" name="reason" required placeholder="Cancellation reason"><button class="button-secondary">Cancel visit</button></div>@if($visit->timeEntries->whereNull('ended_at')->isNotEmpty())<label class="flex min-h-11 items-center gap-3 rounded-lg border border-orange-300 bg-orange-50 px-3"><input type="checkbox" name="confirm_stop_active_timers" value="1"><span class="text-sm font-semibold">Stop {{ $visit->timeEntries->whereNull('ended_at')->count() }} active timer(s) and cancel</span></label>@endif</form>
                                @if($visit->status === 'on_site')<form method="POST" action="{{ route('office.visits.return', $visit) }}" class="flex gap-2">@csrf<input class="form-input" name="reason" required placeholder="Return reason"><button class="button-secondary">Create return</button></form>@endif
                            </div>
                        @endif
                        @if($visit->currentCloseout)
                            @php($timeSeconds = $visit->timeEntries->sum(fn ($entry) => $entry->ended_at ? $entry->started_at->diffInSeconds($entry->ended_at) : 0))
                            <div class="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><p class="text-sm font-bold">Field closeout: {{ ucfirst($visit->currentCloseout->status) }}</p><p class="mt-1 text-sm text-slate-600">Crew time: {{ number_format($timeSeconds / 3600, 2) }} hours</p>
                            @if($visit->currentCloseout->status==='submitted' && $activeMembership->hasCapability('closeouts.inspect'))<a class="mt-3 inline-flex min-h-11 items-center font-bold text-brand-blue" href="{{ route('office.closeout-reviews.show',$visit->currentCloseout) }}">Open review packet</a>@endif
                            @if($visit->currentCloseout->status==='submitted' && $activeMembership->hasCapability('closeouts.inspect'))<div class="mt-3 space-y-2 text-sm"><p><strong>Outcome:</strong> {{ ucfirst(str_replace('_',' ',$visit->currentCloseout->outcome)) }}</p><p><strong>Diagnosis:</strong> {{ $visit->currentCloseout->diagnosis ?: '—' }}</p><p><strong>Work performed:</strong> {{ $visit->currentCloseout->work_performed ?: '—' }}</p><p><strong>Exceptions:</strong> {{ $visit->currentCloseout->exceptions ?: '—' }}</p><p><strong>Recommendations:</strong> {{ $visit->currentCloseout->recommendations ?: '—' }}</p><p><strong>Acknowledgment:</strong> {{ $visit->currentCloseout->representative_name ?: ucfirst(str_replace('_',' ',$visit->currentCloseout->ack_unavailable_category ?? 'fallback recorded')) }}</p><p><strong>Evidence:</strong> {{ $visit->currentCloseout->media->where('state','stored')->count() }} photos · {{ $visit->currentCloseout->parts->whereNull('removed_at')->count() }} proposals</p><div class="flex flex-wrap gap-2">@foreach($visit->currentCloseout->media->where('state','stored') as $media)<a class="button-secondary" href="{{ route('field.media.show',$media) }}">{{ ucfirst(str_replace('_',' ',$media->category)) }}</a>@endforeach</div>@foreach($visit->currentCloseout->parts->whereNull('removed_at') as $part)<p><strong>{{ $part->description }}</strong> · {{ $part->quantity }} {{ $part->unit }} · {{ ucfirst(str_replace('_',' ',$part->billing_treatment)) }}</p>@endforeach</div>@else<p class="mt-2 text-xs text-slate-500">Draft narrative and evidence remain field-only until submission.</p>@endif</div>
                        @endif
                        @can('execute', $visit)@include('office.service-tickets._execution-dialog', ['visit' => $visit])@endcan
                    </div>
                @empty<div class="p-6 text-sm text-slate-500">No visits yet. This ticket remains in the unscheduled ticket list until a visit is created.</div>@endforelse
            </section>
            <section class="surface p-5"><h2 class="text-lg font-bold">Internal notes</h2>
                @if($activeMembership->hasCapability('dispatch.manage'))<form method="POST" action="{{ route('office.service-tickets.notes.store', $ticket) }}" class="mt-4">@csrf<label class="form-label" for="body">Add note</label><textarea class="form-textarea" id="body" name="body" required maxlength="10000"></textarea><button class="button-primary mt-3">Add note</button></form>@endif
                <div class="mt-5 space-y-4">@forelse($ticket->notes->sortByDesc('created_at') as $note)<article class="border-l-4 border-slate-200 pl-4"><p class="whitespace-pre-line text-sm text-slate-700">{{ $note->body }}</p><p class="mt-2 text-xs font-semibold text-slate-500">{{ $note->author?->name ?? 'Former user' }} · <x-local-time :value="$note->created_at" :timezone="$activeOrganization->timezone" /></p></article>@empty<p class="text-sm text-slate-500">No internal notes.</p>@endforelse</div>
            </section>
        </div>
        <aside class="space-y-6">
            @if($activeMembership->hasCapability('dispatch.manage') && $ticket->status !== 'canceled')
                <section class="surface p-5"><h2 class="font-bold">Ticket status</h2><form method="POST" action="{{ route('office.service-tickets.transition', $ticket) }}" class="mt-4 space-y-3">@csrf<select class="form-input" name="status" aria-label="New ticket status">@if($ticket->status==='open')<option value="on_hold">Put on hold</option>@endif @if($ticket->status==='on_hold')<option value="open">Reopen</option>@endif<option value="canceled">Cancel ticket</option></select><textarea class="form-textarea" name="reason" placeholder="Reason required for hold or cancellation"></textarea>@php($activeTicketTimers = $ticket->visits->flatMap->timeEntries->whereNull('ended_at'))@if($activeTicketTimers->isNotEmpty())<label class="flex min-h-11 items-center gap-3 rounded-lg border border-orange-300 bg-orange-50 px-3"><input type="checkbox" name="confirm_stop_active_timers" value="1"><span class="text-sm font-semibold">Stop {{ $activeTicketTimers->count() }} active timer(s) if canceling</span></label>@endif<button class="button-secondary w-full">Update status</button></form></section>
            @endif
            <section class="surface p-5"><h2 class="font-bold">History</h2><div class="mt-4 space-y-4">@forelse($events as $event)<div><p class="text-sm font-semibold text-slate-700">{{ str_replace(['.','_'],' ',ucfirst($event->event_type)) }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->actor?->name ?? 'System' }} · <x-local-time :value="$event->occurred_at" :timezone="$activeOrganization->timezone" format="M j, g:i A T" /></p></div>@empty<p class="text-sm text-slate-500">No history yet.</p>@endforelse</div></section>
        </aside>
    </div>
</x-layouts.office>
