<x-settings-layout title="Billing settings">
    <h2 class="text-2xl font-bold">Billing</h2><p class="mt-2 text-slate-600">Invoice defaults, labor calculation policy, travel charges, and payment connections. Seller identity comes from the Organization tab.</p>
    <section class="surface mt-6 p-5"><x-billing-profile-readiness :organization="$organization" />@if(!$organization->isBillingProfileComplete() && $activeMembership->hasCapability('organization.settings.manage'))<a class="button-secondary mt-4" href="{{ route('office.settings.organization.edit') }}">Complete organization profile</a>@endif</section>
    <form method="POST" action="{{ route('office.settings.billing.update') }}" class="surface mt-6 p-5" data-offline-write>@csrf @method('PUT')<h3 class="text-xl font-bold">Tax default</h3><div class="mt-4 max-w-sm"><label class="form-label" for="default_tax_rate_percent">Default tax rate (%)</label><input class="form-input" id="default_tax_rate_percent" name="default_tax_rate_percent" inputmode="decimal" value="{{ old('default_tax_rate_percent',number_format($settings->default_tax_rate_basis_points/100,2,'.','')) }}" required></div><button class="button-primary mt-5">Save billing defaults</button></form>
    <section class="surface mt-6 p-5">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="text-xl font-bold">Labor billing policy</h3><p class="mt-1 text-sm text-slate-600">Catalog owns labor prices. These settings control how approved time and trip recommendations are calculated.</p></div><a class="button-secondary" href="{{ route('office.catalog.services.index') }}">Manage labor services</a></div>
        @if($activeMembership->hasCapability('billing.settings.manage'))
            <form method="POST" action="{{ route('office.settings.billing.labor-policy.update') }}" class="mt-5 space-y-6" data-offline-write>@csrf @method('PUT')
                <div class="grid gap-4 lg:grid-cols-2">
                    <div><label class="form-label" for="default-labor-service">Default labor service</label><select class="form-input" id="default-labor-service" name="default_labor_catalog_service_id"><option value="">Not configured</option>@foreach($laborServices as $service)<option value="{{ $service->id }}" @selected((string) old('default_labor_catalog_service_id',$settings->default_labor_catalog_service_id)===(string) $service->id)>{{ $service->name }} — ${{ number_format($service->default_price_cents/100,2) }}/hr</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Only active, priced hourly Services using the Hour unit are available.</p></div>
                    <div><label class="form-label" for="labor-increment">Billing increment</label><select class="form-input" id="labor-increment" name="labor_billing_increment_minutes">@foreach([0=>'Exact / no increment',15=>'15 minutes',30=>'30 minutes',60=>'60 minutes'] as $value=>$label)<option value="{{ $value }}" @selected((int) old('labor_billing_increment_minutes',$settings->labor_billing_increment_minutes)===$value)>{{ $label }}</option>@endforeach</select></div>
                    <div><label class="form-label" for="labor-rounding">Rounding rule</label><select class="form-input" id="labor-rounding" name="labor_rounding_rule">@foreach(['up'=>'Round up','nearest'=>'Nearest increment','down'=>'Round down'] as $value=>$label)<option value="{{ $value }}" @selected(old('labor_rounding_rule',$settings->labor_rounding_rule)===$value)>{{ $label }}</option>@endforeach</select></div>
                    <div><label class="form-label" for="minimum-billable">Minimum billable labor</label><select class="form-input" id="minimum-billable" name="minimum_billable_minutes">@foreach([0=>'None',15=>'15 minutes',30=>'30 minutes',60=>'1 hour'] as $value=>$label)<option value="{{ $value }}" @selected((int) old('minimum_billable_minutes',$settings->minimum_billable_minutes)===$value)>{{ $label }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Zero approved labor always remains zero.</p></div>
                </div>
                <fieldset class="border-t border-slate-200 pt-5"><legend class="text-lg font-bold">Travel / trip charges</legend><div class="mt-3 grid gap-4 lg:grid-cols-2"><div><label class="form-label" for="trip-charge-service">Trip charge service</label><select class="form-input" id="trip-charge-service" name="trip_charge_catalog_service_id"><option value="">Not configured</option>@foreach($tripServices as $service)<option value="{{ $service->id }}" @selected((string) old('trip_charge_catalog_service_id',$settings->trip_charge_catalog_service_id)===(string) $service->id)>{{ $service->name }}</option>@endforeach</select></div><div class="space-y-2"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="suggest_trip_charges" value="1" @checked(old('suggest_trip_charges',$settings->suggest_trip_charges))><span>Suggest trip charges during billing review</span></label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="auto_select_trip_charges" value="1" @checked(old('auto_select_trip_charges',$settings->auto_select_trip_charges))><span>Automatically select the suggested charge</span></label><p class="text-xs text-slate-500">Suggestions remain visible and reversible before approval. Automatic selection is off by default.</p></div></div></fieldset>
                <button class="button-primary">Save labor billing policy</button>
            </form>
        @else
            <dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Default labor</dt><dd class="font-bold">{{ $settings->defaultLaborService?->name ?? 'Not configured' }}</dd></div><div><dt class="text-slate-500">Calculation</dt><dd class="font-bold">{{ $settings->labor_billing_increment_minutes ? $settings->labor_billing_increment_minutes.' minute increments' : 'Exact minutes' }} · {{ ucfirst($settings->labor_rounding_rule) }}</dd></div><div><dt class="text-slate-500">Minimum</dt><dd class="font-bold">{{ $settings->minimum_billable_minutes ? $settings->minimum_billable_minutes.' minutes' : 'None' }}</dd></div><div><dt class="text-slate-500">Trip suggestions</dt><dd class="font-bold">{{ $settings->suggest_trip_charges ? 'Enabled' : 'Disabled' }}</dd></div></dl>
        @endif
        @if($rates->isNotEmpty())<div class="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><p class="font-bold">Legacy labor rates retained</p><p class="mt-1">{{ $rates->count() }} legacy {{ Str::plural('rate',$rates->count()) }} remain available for historical invoice compatibility. New labor pricing is managed in Catalog.</p></div>@endif
    </section>

    <section class="surface mt-6 p-5">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-xl font-bold">Hosted payment providers</h3><p class="mt-1 text-sm text-slate-600">Connect the organization's provider account through provider-hosted authorization. Tokens remain encrypted and are never displayed.</p></div><span class="rounded-md border border-slate-300 px-3 py-2 text-sm font-bold">No live charges authorized</span></div>
        <div class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                <div><h4 class="font-bold text-slate-950">Organization default processor</h4><p class="mt-1 text-sm text-slate-600">Used for new electronic checkouts when an invoice is not already financially locked to a provider. Cash and check are unaffected.</p></div>
                @if($activeMembership->hasCapability('payments.settings.manage'))
                    <form method="POST" action="{{ route('office.settings.billing.payments.default') }}" class="flex w-full flex-col gap-2 sm:w-auto sm:min-w-80" data-offline-write>@csrf @method('PUT')
                        <label class="form-label sr-only" for="default-payment-provider">Default electronic payment provider</label>
                        <div class="flex gap-2"><select class="form-input" id="default-payment-provider" name="default_payment_provider"><option value="">No default provider</option>@foreach(['square','stripe'] as $provider)<option value="{{ $provider }}" @selected($settings->default_payment_provider===$provider) @disabled(!($providers[$provider]??null)?->isReady())>{{ ucfirst($provider) }}{{ ($providers[$provider]??null)?->isReady() ? '' : ' — not connected and enabled' }}</option>@endforeach</select><button class="button-secondary shrink-0">Save default</button></div>
                    </form>
                @else
                    <p class="font-bold text-slate-900">{{ $settings->default_payment_provider ? ucfirst($settings->default_payment_provider) : 'No default provider' }}</p>
                @endif
            </div>
        </div>
        <div class="mt-5 grid gap-5 xl:grid-cols-2">
            @foreach($providers as $provider => $configuration)
                <article class="rounded-lg border border-slate-300 p-5">
                    <div class="flex items-center justify-between gap-3"><h4 class="text-lg font-bold">{{ ucfirst($provider) }}</h4><span class="rounded-md px-3 py-2 text-sm font-bold {{ $configuration->isReady() ? 'bg-emerald-100 text-emerald-900' : 'bg-amber-100 text-amber-900' }}">{{ $configuration->isReady() ? 'Ready' : ucfirst(str_replace('_',' ',$configuration->connection_status)) }}</span></div>
                    <dl class="mt-4 grid grid-cols-2 gap-3 text-sm">
                        <div><dt class="text-slate-500">Environment</dt><dd class="font-bold">{{ ucfirst($configuration->environment) }}</dd></div>
                        <div><dt class="text-slate-500">Connection</dt><dd class="font-bold">{{ $configuration->connection_method === 'oauth' ? 'Provider hosted' : ($configuration->credential_fingerprint ? 'Legacy secured' : 'Not connected') }}</dd></div>
                        @if($configuration->credential_fingerprint)<div><dt class="text-slate-500">Safe fingerprint</dt><dd class="font-bold">{{ $configuration->credential_fingerprint }}</dd></div>@endif
                        <div><dt class="text-slate-500">Account</dt><dd class="font-bold">{{ $configuration->external_account_name ?: ($configuration->external_account_id ?: 'Not detected') }}</dd></div>
                        <div><dt class="text-slate-500">Connected</dt><dd class="font-bold">@if($configuration->connected_at)<x-local-time :value="$configuration->connected_at" :timezone="$organization->timezone" />@else Not connected @endif</dd></div>
                        @if($provider==='square')<div><dt class="text-slate-500">Merchant</dt><dd class="break-all font-bold">{{ $configuration->external_account_id ?: 'Not detected' }}</dd></div><div><dt class="text-slate-500">Payment location</dt><dd class="font-bold">{{ $configuration->location_name ?: ($configuration->location_id ?: 'Not selected') }}</dd></div>@endif
                        @if($provider==='stripe')<div><dt class="text-slate-500">Account</dt><dd class="break-all font-bold">{{ $configuration->external_account_id ?: 'Not connected' }}</dd></div><div><dt class="text-slate-500">Payments enabled</dt><dd class="font-bold">{{ $configuration->payments_enabled === null ? 'Not verified' : ($configuration->payments_enabled ? 'Yes' : 'No') }}</dd></div>@endif
                    </dl>
                    <p class="mt-3 break-all text-xs text-slate-500">{{ $configuration->connection_method === 'oauth' ? 'Connected webhook' : 'Legacy webhook' }}: {{ $configuration->connection_method === 'oauth' ? route('payments.webhook.canonical',$provider) : route('payments.webhook',[$provider,$configuration->public_id]) }}</p>

                    @if($activeMembership->hasCapability('payments.settings.manage'))
                        @if($provider==='square')
                            @if($configuration->connection_method === 'oauth' && $configuration->external_account_id)
                                @if(count($configuration->available_locations ?? []) > 1)
                                    <form method="POST" action="{{ route('office.settings.billing.square.location') }}" class="mt-5" data-offline-write>@csrf @method('PUT')<label class="form-label" for="square-payment-location">Square payment location</label><div class="flex gap-2"><select class="form-input" id="square-payment-location" name="location_id">@foreach($configuration->available_locations as $location)<option value="{{ $location['id'] }}" @selected($configuration->location_id===$location['id'])>{{ $location['name'] }}</option>@endforeach</select><button class="button-secondary shrink-0">Update</button></div></form>
                                @endif
                                <div class="mt-5 grid gap-3 sm:grid-cols-2"><form method="POST" action="{{ route('office.settings.billing.square.refresh') }}">@csrf<button class="button-secondary w-full">Refresh connection</button></form><form method="POST" action="{{ route('office.settings.billing.square.connect') }}">@csrf<input type="hidden" name="environment" value="{{ $configuration->environment }}"><button class="button-secondary w-full">Reconnect</button></form></div>
                                <form method="POST" action="{{ route('office.settings.billing.payments.toggle','square') }}" class="mt-3">@csrf<input type="hidden" name="enabled" value="{{ $configuration->enabled ? 0 : 1 }}">@if($configuration->environment==='production')<label class="mb-2 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="confirm_live" value="1"> Confirm live activation</label>@endif<button class="{{ $configuration->enabled ? 'button-danger' : 'button-primary' }} w-full">{{ $configuration->enabled ? 'Disable Square' : 'Enable Square' }}</button></form>
                                @if(!$configuration->enabled)<form method="POST" action="{{ route('office.settings.billing.square.disconnect') }}" class="mt-4 border-t border-slate-200 pt-4">@csrf @method('DELETE')<label class="form-label" for="disconnect-square">Enter DISCONNECT SQUARE to revoke access</label><div class="flex gap-2"><input class="form-input" id="disconnect-square" name="confirmation" required autocomplete="off"><button class="button-danger shrink-0">Disconnect Square</button></div></form>@endif
                            @else
                                <form method="POST" action="{{ route('office.settings.billing.square.connect') }}" class="mt-5 space-y-3" data-offline-write>@csrf<div><label class="form-label" for="square-connect-environment">Square environment</label><select class="form-input" id="square-connect-environment" name="environment"><option value="sandbox" @selected($configuration->environment==='sandbox')>Sandbox</option>@if(app()->environment('production'))<option value="production" @selected($configuration->environment==='production')>Production</option>@endif</select></div><button class="button-primary w-full">Connect Square</button><p class="text-xs text-slate-600">You will continue to Square to authorize the organization account. No access token is pasted into this portal.</p></form>
                                @if($configuration->connection_method === 'legacy_credentials' && $configuration->api_secret)<p class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">A secured legacy Square connection remains available for rollback until hosted authorization is completed.</p>@endif
                            @endif
                        @else
                            @php($stripeApplicationReady = filled(config("payments.connections.stripe.{$configuration->environment}.client_id")) && filled(config("payments.connections.stripe.{$configuration->environment}.platform_secret")))
                            @if($configuration->connection_method === 'oauth' && $configuration->external_account_id)
                                <div class="mt-5 grid gap-3 sm:grid-cols-2">
                                    @if($configuration->isReady() && $settings->default_payment_provider !== 'stripe')<form method="POST" action="{{ route('office.settings.billing.payments.default') }}">@csrf @method('PUT')<input type="hidden" name="default_payment_provider" value="stripe"><button class="button-primary w-full">Set Default</button></form>@endif
                                    <form method="POST" action="{{ route('office.settings.billing.stripe.refresh') }}">@csrf<button class="button-secondary w-full">Refresh connection</button></form>
                                    @if(!$configuration->enabled)<form method="POST" action="{{ route('office.settings.billing.stripe.connect') }}">@csrf<input type="hidden" name="environment" value="{{ $configuration->environment }}"><button class="button-secondary w-full">Reconnect</button></form>@endif
                                </div>
                                <form method="POST" action="{{ route('office.settings.billing.payments.toggle','stripe') }}" class="mt-3">@csrf<input type="hidden" name="enabled" value="{{ $configuration->enabled ? 0 : 1 }}">@if($configuration->environment==='live')<label class="mb-2 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="confirm_live" value="1"> Confirm live activation</label>@endif<button class="{{ $configuration->enabled ? 'button-danger' : 'button-primary' }} w-full">{{ $configuration->enabled ? 'Disable Stripe' : 'Enable Stripe' }}</button></form>
                                @if(!$configuration->payments_enabled)<p class="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Stripe is connected, but the account is not yet enabled to accept payments. Complete the requirements in Stripe, then refresh the connection.</p>@endif
                                @if(!$configuration->enabled)<form method="POST" action="{{ route('office.settings.billing.stripe.disconnect') }}" class="mt-4 border-t border-slate-200 pt-4">@csrf @method('DELETE')<label class="form-label" for="disconnect-stripe">Enter DISCONNECT STRIPE to revoke access</label><div class="flex gap-2"><input class="form-input" id="disconnect-stripe" name="confirmation" required autocomplete="off"><button class="button-danger shrink-0">Disconnect Stripe</button></div></form>@endif
                            @elseif($stripeApplicationReady)
                                <form method="POST" action="{{ route('office.settings.billing.stripe.connect') }}" class="mt-5 space-y-3" data-offline-write>@csrf<div><label class="form-label" for="stripe-connect-environment">Stripe environment</label><select class="form-input" id="stripe-connect-environment" name="environment"><option value="test" @selected($configuration->environment==='test')>Test</option>@if(app()->environment('production'))<option value="live" @selected($configuration->environment==='live')>Live</option>@endif</select></div><button class="button-primary w-full">Connect Stripe</button><p class="text-xs text-slate-600">You will continue to Stripe to sign in and authorize the intended existing account. No Stripe secret key is entered in this portal.</p></form>
                                @if($configuration->connection_method === 'legacy_credentials' && $configuration->api_secret)<p class="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">A secured legacy Stripe connection remains available for rollback until hosted authorization is completed.</p>@endif
                            @else
                                <div class="mt-5 rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><p class="font-bold">Stripe Connect setup required</p><p class="mt-1">Configure the Stripe Connect client ID, platform secret, and this callback URL in the Stripe application before connecting an account:</p><p class="mt-2 break-all font-mono text-xs">{{ route('office.settings.billing.stripe.callback') }}</p></div>
                            @endif
                        @endif
                    @else
                        <p class="mt-5 rounded-lg bg-slate-50 p-4 text-sm">You can view readiness. A Super Admin manages connections, testing, and activation.</p>
                    @endif
                </article>
            @endforeach
        </div>
    </section>
</x-settings-layout>
