<x-settings-layout title="Billing settings">
    <h2 class="text-2xl font-bold">Billing</h2><p class="mt-2 text-slate-600">Tax and labor configuration. Seller identity comes from the Organization tab.</p>
    <section class="surface mt-6 p-5"><x-billing-profile-readiness :organization="$organization" />@if(!$organization->isBillingProfileComplete() && $activeMembership->hasCapability('organization.settings.manage'))<a class="button-secondary mt-4" href="{{ route('office.settings.organization.edit') }}">Complete organization profile</a>@endif</section>
    <form method="POST" action="{{ route('office.settings.billing.update') }}" class="surface mt-6 p-5" data-offline-write>@csrf @method('PUT')<h3 class="text-xl font-bold">Tax default</h3><div class="mt-4 max-w-sm"><label class="form-label" for="default_tax_rate_percent">Default tax rate (%)</label><input class="form-input" id="default_tax_rate_percent" name="default_tax_rate_percent" inputmode="decimal" value="{{ old('default_tax_rate_percent',number_format($settings->default_tax_rate_basis_points/100,2,'.','')) }}" required></div><button class="button-primary mt-5">Save billing defaults</button></form>
    <section class="surface mt-6 p-5"><h3 class="text-xl font-bold">Named labor rates</h3><div class="mt-4 space-y-3">@foreach($rates as $rate)<form method="POST" action="{{ route('office.settings.billing.rates.update',$rate) }}" class="grid items-end gap-3 border-b border-slate-200 pb-3 md:grid-cols-[1fr_180px_auto_auto_auto]">@csrf @method('PUT')<p class="min-h-11 py-3 font-bold">{{ $rate->name }}</p><div><label class="form-label" for="rate-{{ $rate->id }}">Hourly rate</label><input class="form-input" id="rate-{{ $rate->id }}" name="hourly_rate" value="{{ number_format($rate->hourly_rate_cents/100,2,'.','') }}" required></div><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="active" value="1" @checked($rate->active)> Active</label><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="is_default" value="1" @checked($rate->is_default)> Default</label><button class="button-secondary">Update</button></form>@endforeach</div><form method="POST" action="{{ route('office.settings.billing.rates.store') }}" class="mt-6 grid items-end gap-3 md:grid-cols-[1fr_180px_auto_auto]">@csrf<div><label class="form-label" for="rate-name">Rate name</label><input class="form-input" id="rate-name" name="name" placeholder="Standard" required></div><div><label class="form-label" for="hourly-rate">Hourly rate</label><input class="form-input" id="hourly-rate" name="hourly_rate" inputmode="decimal" placeholder="125.00" required></div><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="is_default" value="1"> Default</label><button class="button-primary">Add rate</button></form></section>
    <section class="surface mt-6 p-5">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-xl font-bold">Hosted payment providers</h3><p class="mt-1 text-sm text-slate-600">Secrets are encrypted and never shown again. Local and CI environments accept test credentials only.</p></div><span class="rounded-md border border-slate-300 px-3 py-2 text-sm font-bold">No live charges authorized</span></div>
        <div class="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4">
            <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                <div><h4 class="font-bold text-slate-950">Organization default processor</h4><p class="mt-1 text-sm text-slate-600">Used for new electronic checkouts when an invoice is not already financially locked to a provider. Cash and check are unaffected.</p></div>
                @if($activeMembership->hasCapability('payments.settings.manage'))
                    <form method="POST" action="{{ route('office.settings.billing.payments.default') }}" class="flex w-full flex-col gap-2 sm:w-auto sm:min-w-80" data-offline-write>@csrf @method('PUT')
                        <label class="form-label sr-only" for="default-payment-provider">Default electronic payment provider</label>
                        <div class="flex gap-2"><select class="form-input" id="default-payment-provider" name="default_payment_provider"><option value="">No default provider</option>@foreach(['square','stripe'] as $provider)<option value="{{ $provider }}" @selected($settings->default_payment_provider===$provider) @disabled(!($providers[$provider]??null)?->isReady())>{{ ucfirst($provider) }}{{ ($providers[$provider]??null)?->isReady() ? '' : ' — not connected and enabled' }}</option>@endforeach</select><button class="button-secondary shrink-0">Save default</button></div>
                    </form>
                @else
                    <p class="font-bold text-slate-900">{{ $settings->default_payment_provider ? ucfirst($settings->default_payment_provider) : 'No default provider' }}</p>
                @endif
            </div>
        </div>
        <div class="mt-5 grid gap-5 xl:grid-cols-2">
            @foreach($providers as $provider => $configuration)
                <article class="rounded-lg border border-slate-300 p-5">
                    <div class="flex items-center justify-between gap-3"><h4 class="text-lg font-bold">{{ ucfirst($provider) }}</h4><span class="rounded-md px-3 py-2 text-sm font-bold {{ $configuration->isReady() ? 'bg-emerald-100 text-emerald-900' : 'bg-amber-100 text-amber-900' }}">{{ $configuration->isReady() ? 'Ready' : ucfirst($configuration->connection_status) }}</span></div>
                    <dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt class="text-slate-500">Environment</dt><dd class="font-bold">{{ ucfirst($configuration->environment) }}</dd></div><div><dt class="text-slate-500">Credentials</dt><dd class="font-bold">{{ $configuration->credential_fingerprint ? 'Configured · '.$configuration->credential_fingerprint : 'Not configured' }}</dd></div><div><dt class="text-slate-500">Account</dt><dd class="font-bold">{{ $configuration->external_account_id ?: 'Not detected' }}</dd></div><div><dt class="text-slate-500">Last test</dt><dd class="font-bold">{{ $configuration->last_tested_at ? $configuration->last_tested_at->timezone($organization->timezone)->format('M j, Y g:i A T') : 'Never' }}</dd></div></dl>
                    <p class="mt-3 break-all text-xs text-slate-500">Webhook: {{ route('payments.webhook',[$provider,$configuration->public_id]) }}</p>
                    @if($activeMembership->hasCapability('payments.settings.manage'))
                        <form method="POST" action="{{ route('office.settings.billing.payments.update',$provider) }}" class="mt-5 space-y-3" data-offline-write>@csrf @method('PUT')
                            <div><label class="form-label" for="environment-{{ $provider }}">Environment</label><select class="form-input" id="environment-{{ $provider }}" name="environment">@foreach($provider==='square' ? ['sandbox','production'] : ['test','live'] as $environment)<option value="{{ $environment }}" @selected($configuration->environment===$environment)>{{ ucfirst($environment) }}</option>@endforeach</select></div>
                            @if($provider==='square')<div><label class="form-label" for="location-{{ $provider }}">Location ID</label><input class="form-input" id="location-{{ $provider }}" name="location_id" value="{{ $configuration->location_id }}" required></div>@endif
                            <div><label class="form-label" for="secret-{{ $provider }}">{{ $provider==='square' ? 'Access token' : 'Secret key' }}</label><input class="form-input" id="secret-{{ $provider }}" name="api_secret" type="password" autocomplete="new-password" placeholder="Leave blank to retain the configured secret"><p class="mt-1 text-xs text-slate-500">Blank retains the existing value.</p></div>
                            <div><label class="form-label" for="webhook-{{ $provider }}">Webhook signing secret</label><input class="form-input" id="webhook-{{ $provider }}" name="webhook_secret" type="password" autocomplete="new-password" placeholder="Leave blank to retain the configured secret"></div>
                            <button class="button-primary w-full">Save {{ ucfirst($provider) }} credentials</button>
                        </form>
                        <div class="mt-3 grid gap-3 sm:grid-cols-2"><form method="POST" action="{{ route('office.settings.billing.payments.test',$provider) }}">@csrf<button class="button-secondary w-full">Test connection</button></form><form method="POST" action="{{ route('office.settings.billing.payments.toggle',$provider) }}">@csrf<input type="hidden" name="enabled" value="{{ $configuration->enabled ? 0 : 1 }}">@if(in_array($configuration->environment,['production','live'],true))<label class="mb-2 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="confirm_live" value="1"> Confirm live activation</label>@endif<button class="{{ $configuration->enabled ? 'button-danger' : 'button-secondary' }} w-full">{{ $configuration->enabled ? 'Disable' : 'Enable' }}</button></form></div>
                        @if(!$configuration->enabled)<form method="POST" action="{{ route('office.settings.billing.payments.clear',$provider) }}" class="mt-4 border-t border-slate-200 pt-4">@csrf @method('DELETE')<label class="form-label" for="clear-{{ $provider }}">Enter CLEAR {{ strtoupper($provider) }} to remove credentials</label><div class="flex gap-2"><input class="form-input" id="clear-{{ $provider }}" name="confirmation" required><button class="button-danger">Clear</button></div></form>@endif
                    @else
                        <p class="mt-5 rounded-lg bg-slate-50 p-4 text-sm">You can view readiness. A Super Admin manages credentials, testing, and activation.</p>
                    @endif
                </article>
            @endforeach
        </div>
    </section>
</x-settings-layout>
